### ISSUE TITLE
Relay buffer not filling?

### ISSUE THREAD

**Issue by ghost** [Qmunity/BluePower#134]
I have a relay hooked up to an input tube, and I am expecting it to fill the buffer (in the gui), but it is not. Not really sure why...

Assuming there is no other place for the output to send items... the buffer should fill shouldn't it? 

Rendering issue?

**Comment by mikiones** [comment]
Well this is not entirely true. consider relay in setup where you want use like hopper, but when internal buffer is stuffed the block will not accept more items from tube network even if there are still free slots in inventory in it. The red power version this was possible. The output side when stuffed not output more items to aj inventory or pipe. The input sides are hover accepting items when gui slots are free. this block is kind of congestion of filter attached to chest(buffer).
