### ISSUE TITLE
[Suggestion] Coloured lights API integration

### ISSUE THREAD

**Issue by planetguy32** [Qmunity/BluePower#143]
www.minecraftforum.net/topic/2502193-/

This API allows blocks to have coloured lights. The two important classes of CL API are in the package:

https://github.com/CptSpaceToaster/CptsModdingLight/tree/1.7.2/src/main/java/coloredlightscore/src/api

CLBlock.java contains methods that are patched into Block.class using ASM, and CLApi.java contains utilities for generating coloured light values.

**Comment by amadornes** [comment]
Already done! Forgot to close this yesterday :P
