### ISSUE TITLE
Bad interaction with artifacts display cases.

### ISSUE THREAD

**Issue by Claycorp** [Qmunity/BluePower#161]
http://pastebin.com/a2gPaMK1

If you make a deployer place Display cases in front of block breaker it will duplicate the block and throws the above error.

**Comment by amadornes** [comment]
Is this still a thing? This is an ancient bug report and it might have been fixed. Could somebody test it?

I'm going to close this because we haven't had news about it in a long long time but if it still happens I'll open it again.

**Comment by Draco18s** [comment]
As I was cleaning up my own repository, I ran across [this issue](https://github.com/Draco18s/Artifacts/issues/4) (I don't remember it being reported) which references this one.

I looked at the code on my end and my question is: does the deployer count as type EntityPlayer? (I cannot find the relevant class in your repo).
