### ISSUE TITLE
[Suggestion] Air Block

### ISSUE THREAD

**Issue by DrSoda** [Qmunity/BluePower#20]
A block that is completely invisible, and you can walk through it, and basically acts like air with a hitbox. You can then make microblocks of this and you have an invisible bluestone wire blocker, and looks as if nothing is there. Possibly you can see it when holding a screwdriver or something.

**Comment by K-4U** [comment]
Probably going to cause more issues than that it's worth. People might not be able to see this air block and start to wonder why wires don't connect.

Even more so: "Why can't i place a block here" might be mentioned a lot.
