### ISSUE TITLE
Question related to Bluestone API

### ISSUE THREAD

**Issue by Victorious3** [Qmunity/BluePower#203]
I'm currently trying to add BluePower support to my mod [IntegratedCircuits](https://github.com/Victorious3/Integrated-Circuits). In order to do that, I'd like to support BluePower's bundled wires as well, those may connect to the circuits, depending on how it is configured. The circuit itself is a multipart. Here's an image to illustrate what I'm talking about (Project:Red interacts just fine):

![Circuit](http://puu.sh/cJZfp/5b37359fe5.png)

I looked around the API for a while and I don't think it's yet possible, correct me if I'm wrong. Another thing I noticed is that your wires don't seem to call `canConnectRedstone(int arg0)` from `IRedstonePart` which results in wires connecting to the wrong sides where only bundled should be allowed.

**Comment by amadornes** [comment]
NewMultipart has already been merged into master but I wouldn't suggest using the bundled API yet. I'm still working on it ^^
