### ISSUE TITLE
Relais orientation change/ output side

### ISSUE THREAD

**Issue by Kropter** [Qmunity/BluePower#208]
Placing a relais wrong, the rotating doesnt prevent items to flow in the output side when connected to the network with placing.
Easy solution is to place and rotate the Relay first, then connect to the tubes, but thats not the intended way i think.

**Comment by MineMaarten** [comment]
I'm not sure what you're saying btw (and also sorry for the 2 months wait). 'Changing the relay wrong'? Placing it not facing a tube? and then rotating it after? it seems to work for me? Could you explain how to reproduce it?

**Comment by Quetzi** [comment]
I think I get what you are saying, tubes will insert into the output side of the relay as the buffer lives in the output side and items in tubes with no destination will go to the closest buffer. I'm going to close this for now, let me know if there is still an issue @Kropter
