### ISSUE TITLE
Circuit Table crash

### ISSUE THREAD

**Issue by jem991** [Qmunity/BluePower#233]
http://pastebin.com/U0WeKAZ5

**Comment by amadornes** [comment]
Could you provide more information, please? What were you doing when the crash happened? What version of BluePower and QmunityLib were you using?
Thanks ^^

**Comment by Quetzi** [comment]
It's bluepower 811 and lib 64 according to the log. This kind of error I'm inclined to blame on optifine though

**Comment by amadornes** [comment]
Oh, didn't see those, sorry :P
And yeah, there's many mods in that pack that could cause issues with it and OF is one of them

**Comment by jem991** [comment]
I'm delete optifine and same crash
http://pastebin.com/Q3diBr1y
