### ISSUE TITLE
Bug Flax Crop

### ISSUE THREAD

**Issue by Xee1** [Qmunity/BluePower#234]
With latest version of BluePower and QmunityLib (CurseForge) I've found this:
Flax crop grow ever higher!
Edit: This bug was present before the new release
![2015-01-01_14 15 21](https://cloud.githubusercontent.com/assets/8685029/5592220/c690b77c-91c0-11e4-8c93-e3c95dfadf71.png)

**Comment by amadornes** [comment]
Weird... Flax shouldn't have changed in the last release...

**Comment by Xee1** [comment]
@amadornes This thing was there before, I waited this release to check if it was still present

**Comment by Quetzi** [comment]
Flax bugs should have all been worked out, maybe they got missed somehow. Steps to replicate?

**Comment by Xee1** [comment]
@Quetzi Simple, plant a flax seed and use bone meal to grow!

**Comment by Quetzi** [comment]
Ok, I'll try take a look once I've put my PC back together

**Comment by Xee1** [comment]
Thanks, and happy new year everyone!

**Comment by Quetzi** [comment]
Can I just check, do you have hunger overhaul installed?

**Comment by Xee1** [comment]
Oh, yes, it's hunger overhaul?

**Comment by Quetzi** [comment]
Yes, not much I can do about it, they change right click behaviour on plants.

**Comment by Xee1** [comment]
Okay, Sorry for the mistake!
