### ISSUE TITLE
Reinforced glass can be destroyed by wither head projectiles

### ISSUE THREAD

**Issue by GamingMortal** [Qmunity/BluePower#237]
Just to let you all know the glass is still destroyed by wither projectiles

**Comment by amadornes** [comment]
Wither projectiles... Uhhh... I actually didn't test that... Added to my TODO list for today :P

**Comment by amadornes** [comment]
Okay, I could not confirm this before but after watching Dire's video today it seems like in hard difficulty wither heads override the block breaking protection we're using (No, he didn't use reinforced sapphire glass, but Tema was around and mentioned it) :P

**Comment by GamingMortal** [comment]
Cool I'm glad the problem was mentioned do you know how to fix it?

**Comment by amadornes** [comment]
I do not! But I'll check EnderIO's source to see how they did their reinforced obsidian block :P
