### ISSUE TITLE
Some rendeing bug in "multipart" update.

### ISSUE THREAD

**Issue by fhntv24** [Qmunity/BluePower#239]
http://snag.gy/te9HX.jpg
Black pipe
http://snag.gy/TIlGf.jpg
Some sides arent rendeing properply ( in inventory while you break pipe in world )
http://snag.gy/dqa4M.jpg
Lightning issue

**Comment by amadornes** [comment]
The last one is not a lighting issue, it's just how lighting is calculated in our multipart system. The other othe is confirmed :P

**Comment by fhntv24** [comment]
Its a litle bit strange one for me... then I have to get used to

**Comment by amadornes** [comment]
Not a problem anymore. Switching over to models. We might add a mode that will allow you to use the old renderer when we go modular (Everything will stay in the same jar, but it'll be split into modules in-code so you can disable/configure them individually)
