### ISSUE TITLE
Big frame drop in the "preview" of the gate place:

### ISSUE THREAD

**Issue by CubeWrench202** [Qmunity/BluePower#241]
When you have a gate in your hand the game perfomance is good, however when you look at any block with a gate in your hand you get a preview, which gives a big frame drop:
![2015-01-01_18 47 56](https://cloud.githubusercontent.com/assets/8869399/5594339/f8a31028-9226-11e4-9525-8f6d3886d8af.png)
![2015-01-02_05 24 00](https://cloud.githubusercontent.com/assets/8869399/5594340/f8a66278-9226-11e4-9b3f-72d3f79b125a.png)
![2015-01-02_05 24 14](https://cloud.githubusercontent.com/assets/8869399/5594341/f8a6ae40-9226-11e4-9240-f6890d335563.png)
![2015-01-01_18 47 51](https://cloud.githubusercontent.com/assets/8869399/5594342/f8a7e85a-9226-11e4-900f-315fbb12e8c2.png)

**Comment by CubeWrench202** [comment]
As you can see, without a gate preview the game is at 30 FPS, but with preview it falls into 8 FPS.
And with the analogic gate (Comparator) the same happens.
(It happens with all the gates :P).

**Comment by amadornes** [comment]
I would expect that, yeah, as it renders the gate again every render tick. This is not a bug but I will add a way to cache the rendering so it doesn't need to be re-rendered every time :P

**Comment by TheJulianJES** [comment]
They also look a bit funny in all F5 modes.

**Comment by MoreThanHidden** [comment]
No longer an issue with newer versions see Work in progress / Project for further details.
