### ISSUE TITLE
Alloy Furnace recycling recipes missing in new release:

### ISSUE THREAD

**Issue by CubeWrench202** [Qmunity/BluePower#242]
As the name says, the recycling recipes of the alloy furnace don't seems to be working in the new release, here is a picture of all the recipes, using the NEI plugin:
![2015-01-02_05 30 28](https://cloud.githubusercontent.com/assets/8869399/5594389/01461c2e-9228-11e4-8833-6a6b8d468d8f.png)
(By the way, this is NOT a NEI plugin bug, i already test this bug by myself placing a iron chestplate in the alloy furnace and nothing happens).

**Comment by amadornes** [comment]
This is one of the many things broken in the update due to things in the mod starting up in weird orders
