### ISSUE TITLE
Missing recipe for some things:

### ISSUE THREAD

**Issue by CubeWrench202** [Qmunity/BluePower#243]
-Silky screwdriver.
-Freestanding wire(s).
-Marble and basalt tile.
-Bundled cable (Currently disabled, i know, but the red alloy wire is also disable and has a recipe through).

**Comment by amadornes** [comment]
Insulated wire recipes are also broken

**Comment by amadornes** [comment]
Fixed!

**Comment by CubeWrench202** [comment]
Fixed by Amadornes 31472706802ab5e14f14731c0d552c4dcc653120

**Comment by CubeWrench202** [comment]
lol, we did it at the same time ._.
