### ISSUE TITLE
Freestanding color wires broken

### ISSUE THREAD

**Issue by CubeWrench202** [Qmunity/BluePower#252]
They connect one to each other, this is not intended, right?
![2015-01-08_15 36 01](https://cloud.githubusercontent.com/assets/8869399/5668183/85785038-974c-11e4-8121-870bfb15ee6f.png)

**Comment by amadornes** [comment]
WAT :|
I coded them specially to NOT do that...

**Comment by CubeWrench202** [comment]
Haha, no problem ama :).

**Comment by amadornes** [comment]
Just pushed a huge 51-commit chunk of code which includes a fix for this :P
