### ISSUE TITLE
Null cell (Bluestone and Insulated teslatite) doesn't works properly:

### ISSUE THREAD

**Issue by CubeWrench202** [Qmunity/BluePower#254]
First, all this bugs happens with the 2 null cell types, so keep that in mind:

1 - Cannot be powered by a lever, redstone torch, pressure plate or button, oh, also redstone wire!:
-Null cells can only be powered by BP wires- :
![2015-01-08_16 11 45](https://cloud.githubusercontent.com/assets/8869399/5668791/1f3b1f62-9751-11e4-9b94-4663385d5ed8.png)
![2015-01-08_16 11 46](https://cloud.githubusercontent.com/assets/8869399/5668792/1f3fbb44-9751-11e4-91ea-67ecfb6d7f0e.png)
![2015-01-08_16 11 52](https://cloud.githubusercontent.com/assets/8869399/5668795/29f48da8-9751-11e4-8451-03b9bd65fa63.png)
![2015-01-08_16 11 50](https://cloud.githubusercontent.com/assets/8869399/5668796/2e180d60-9751-11e4-92bb-28987b4ebf6a.png)
![2015-01-08_16 11 56](https://cloud.githubusercontent.com/assets/8869399/5668797/30ce0474-9751-11e4-827e-3052ed552395.png)
I don't know if this is intented, because levers, redstone torches, pressure plates, buttons and redstone wires transport redstone signals, and the null cells transport bluestone signal, correct?
If that's correct the first bug is not a bug, just an intented feature, sorry, if not, this is a bug.

2 - They not transport bluestone/infused teslatite signal to other null cells:
![2015-01-08_16 18 24](https://cloud.githubusercontent.com/assets/8869399/5668899/e8b9066a-9751-11e4-9c59-64e29291edaa.png)
![2015-01-08_16 18 31](https://cloud.githubusercontent.com/assets/8869399/5668900/e8ba6230-9751-11e4-98dd-1a8482545375.png).

**Comment by amadornes** [comment]
You already reported it the other day (though it was on my stream or on twitter, and not through the issue reporter).
Them not interacting with redstone signals is more of an unimplemented feature than a bug and not connecting to eachother I still have to find out, but it should have an easy fix :P

**Comment by amadornes** [comment]
Fixed!

![](http://i.gyazo.com/9a04e3d610421f7a5c7416078ee85f4c.png)
