### ISSUE TITLE
[Suggestion] A couple of 'blue' mobs.

### ISSUE THREAD

**Issue by MrKickkiller** [Qmunity/BluePower#257]
My idea is to make like a couple of blue tinted mobs.
- Blue creeper: Drops Teslatite dust.
- Blue zombie : Wears sapphire /ruby/emerald armour/weapons. (May already happen due to vanilla)
...

I'll take a look into making it work in my free time, but it was just a fun idea I came up with.

MrKickkiller

**Comment by CubeWrench202** [comment]
A little bit weird, doesn't makes so much play with the mod, like, it is a tech mod, so add mobs is not what they are looking for i think, however make that the vanilla zombie spawns with ruby/amethyst/sapphire swords is a good idea.

**Comment by MrKickkiller** [comment]
I believe the zombie spawns should already happen with BP armour, not 100% sure of that though.
If not, I could try and make it happen.

It was just an idea + a reason to get me into java again. (The exams made me do Bash, and I don't like Bash :/)

**Comment by Quetzi** [comment]
> I believe the zombie spawns should already happen with BP armour

Unlikely, we don't add armour ;)
Blue mobs don't really fit with what we are doing though, maybe something that could be done in an addon/separate project though.

**Comment by MrKickkiller** [comment]
Ok Np, Q
It was just a thougt that sprung to my mind
