### ISSUE TITLE
[Suggestion] Minor tweak for opaque pneumatic tubes

### ISSUE THREAD

**Issue by Linkinexe** [Qmunity/BluePower#258]
Since pneumatic tubes require glass for their recipe and the opaque variant requires silver I suggest to tweak the recipe for latter for balance purposes. Silver is way harder to come by than glass so I suggest to use stone instead for opaque pneumatic tubes.
People with a less powerful computer should't be punished by forcing them to go mining for quite a rare substance.

**Comment by ds84182** [comment]
Or maybe a config option to disable items rendering in pipes, maybe just
draw lines on the inside of the pipe to indicate transfer

**Comment by amadornes** [comment]
@ds84182: There is already an option to disable item rendering in tubes or just render a cube instead of the items, so that's already done ;)
The recipe has changed, so no need to worry about it anyways :P
