### ISSUE TITLE
[Suggestion] Upgradable Project Table

### ISSUE THREAD

**Issue by Linkinexe** [Qmunity/BluePower#259]
I'd like to suggest an upgrade system for project tables to store recipes for quick access similar to the ones from Redpower2. The only downside to those was that the blueprints had to be placed into the table every time one wished to craft different items. I'd suggest to get an upgrade system going opening up a tab in which you can put blueprints and search through recipes via a search bar or showing you the available recipes similar to Applied Energistics and all you have to do is request a certain amount of items provided that the items for that respective recipe are in the table.

**Comment by Quetzi** [comment]
We have something else in mind for crafting

**Comment by CubeWrench202** [comment]
@Linkinexe If i'm not wrong they have in mind an Blutricity(Coming soon ;D) powered automatic crafting table.

**Comment by Linkinexe** [comment]
@CubeWrench202  Thanks for the info, I already suspected something like this along these lines :D

**Comment by CubeWrench202** [comment]
:D
