### ISSUE TITLE
Pneumatic tube recipe 

### ISSUE THREAD

**Issue by CubeWrench202** [Qmunity/BluePower#260]
It works fine, but i have a question, why Pneumatic tubes look like silver which is grey/white when they are made with brass which is brown :P?.
I have no problems with change the recipe of pneumatic tubes to silver and then make a PR, tell me.

**Comment by Quetzi** [comment]
It is not worth changing the recipe ahead of moving to fluid crafting for them. Also silver is a terrible choice for a pneumatic tube, sorry.
