### ISSUE TITLE
[Suggestion] Frames

### ISSUE THREAD

**Issue by Linkinexe** [Qmunity/BluePower#261]
Do you plan to implement frames which go with the motors there seem to be planned or do you rather add support for frame mods like Framez and Funky Locomotion? Or possibly none or both of these options?

**Comment by CubeWrench202** [comment]
Please DUDE, a lot of people have request this already and this is the answer from me or any BP dev:
"Amadornes' framez will be merged to Bluepower in 1.8".
So yeah, Amadornes mod will be all in one package in 1.8, but you have to wait, now please close this and try to search if someone report what you are going to report already, so there won't be a lot of issues looking for the same thing.

**Comment by Linkinexe** [comment]
I am deeply sorry for bothering you, but I did search for this request in the wrong place obviously. For some reason I could not find an issue on this topic so I decided to open one. Apparently some kind of  filters were applied on my search bar. Next time I'm gonna check twice before posting. Sorry for wasting your time.

**Comment by CubeWrench202** [comment]
No no no!I'm here to help you, i'm just telling this to you because other people will instantly answer you in a hater way xD

**Comment by amadornes** [comment]
@CubeWrench202 Who told you they were going to get merged? Because nobody told me

**Comment by CubeWrench202** [comment]
Ama, you told me that, remember you make a page and you ask if release framez as a single mod, merge it for BP, or merge it in the future to BP and release now.
People request release it now and merge it in the future, weeks later i told that was time to port Framez to BP and you say: "i might do it in 1.8".
https://twitter.com/amadornes/status/525278658689511424

**Comment by amadornes** [comment]
"Might" doesn't mean "going to"

**Comment by Linkinexe** [comment]
So as far as I understand this conversation you didn't decide yet?

**Comment by amadornes** [comment]
Yeah, it's not been decided yet, but your best bet for now would either be Framez or FunkyLocomotion (or both, as since the last Framez update both work together perfectly ;D).
The advantage of Framez is that it allows you to use a lot of different power systems (and will support BP's power system when it's done) where as FL only runs on RF :P

**Comment by Linkinexe** [comment]
@amadornes  Thanks for the info. Actually I am using framez for quite a while already ;D
Seems as if I definitely decided for the right mod straight from the beginning for my personal mod pack XD

**Comment by amadornes** [comment]
Nice to hear that :D
