### ISSUE TITLE
Wireless Redstone [Chicken-Bones] is bugged with Bluestone Wires

### ISSUE THREAD

**Issue by TheJulianJES** [Qmunity/BluePower#264]
Works (looks bugged):
![2015-01-13_21 09 44](https://cloud.githubusercontent.com/assets/6409465/5728348/dbe623ac-9b69-11e4-9116-54922c8b245b.png)

Doesn't work (looks good):
![2015-01-13_21 09 31](https://cloud.githubusercontent.com/assets/6409465/5728350/e2d63152-9b69-11e4-9d37-05ea5ce3768b.png)

**Comment by GirafiStudios** [comment]
What looks bugged about it?

**Comment by amadornes** [comment]
That shouldn't happen... Have you tried causing a block update to the wire to see if it connects again? There's a bug with multiparts not getting updated when converting them to FMP multiparts or placing them in an existing FMP part (will be fixed in the next version)

**Comment by TheJulianJES** [comment]
I placed Cobble after I placed it,  Wire and Transmitter, not working.

**Comment by amadornes** [comment]
I was talking about the first issue, but yeah... I'll take a look at it in my development environment as soon as I have some free time (hopefully today or tomorrow) ;)

**Comment by TheJulianJES** [comment]
Thank you for your work and nice support ;)

**Comment by amadornes** [comment]
Funny fact, rewriting the wires the exact opposite happens xD

**Comment by TheJulianJES** [comment]
@amadornes Nice ;) - For my it crashes: #285 :D - I saw your stream, the new BluePower stuff is sooo fancy! Nice work!

**Comment by MoreThanHidden** [comment]
No longer an issue with newer versions see Work in progress / Project for further details.
