### ISSUE TITLE
[Bug] Disappearing Items in Project table

### ISSUE THREAD

**Issue by tntblockman** [Qmunity/BluePower#267]
Version: BluePower 1.7.10-0.2.835
Location: Qmunity Sub Server

If you have say for instance have a crafting recipe for bronze(Forestry; 3 Copper + 1 Tin) on the crafting grid, and you then click the "X" button to remove those items.  You'll find that the copper ingots will be placed back to the Project table's inventory, but the remaining tin ingots will just vanish.  Both the player's inventory and Project table's have plenty of spare slots for items to placed back.  Also could not find any other recipe where this issue occurs, but could be more out there.

**Comment by MineMaarten** [comment]
Fixed with https://github.com/Qmunity/BluePower/commit/a2b4c6fe47d44e1f07c94b99dc17197577b76916
