### ISSUE TITLE
should have more information to provide to users

### ISSUE THREAD

**Issue by nayfaan** [Qmunity/BluePower#268]
should make wikis and guides e.g. starter guides
not much people knows how this things works, especially those different from redpower, e.g. what is used to power the sorting machine etc...

**Comment by amadornes** [comment]
Most of the things work exactly as they did in RedPower and some of them even have extra documentation, so I don't really get your point.
About the wiki... we're waiting until we get what we're working on done and then we'll get working on a wiki. It'll probably be maintained by the community, but there'll be both a wiki for players and devs

**Comment by nayfaan** [comment]
I know most of the things work as in redpower, but what confuses me is those although small parts that doesn't work exactly as in redpower. e.g. I still can't figure out how to power the sorting machine.

**Comment by Quetzi** [comment]
@nayfaan the sorting machine currently doesn't require power. That part of the mod is not yet implemented. It is high on the list of things to get done, for now anything with power is free to use for a limited time ;)

**Comment by nayfaan** [comment]
Oic those little things are bugging me...
So I am not really familiar with redpower....
So BTW do you kniw where I can find a guide for setting up the sorter? (Suggestion: maybe we can have a discussion page on here so that we can have general discussions that are not necessarily issues? E.g. asking for help, making guides , etc.) Things I find on other source are too complicated for me to comprehend like the different sorting modes.... 
And the texture confuses me as well... as the redpower wiki identifies the input and output of the machine using its texture.... so maybe you could provide some of these information in the to-be-made wiki too..
