### ISSUE TITLE
World Gen Structure Crash

### ISSUE THREAD

**Issue by ChatFawkes** [Qmunity/BluePower#271]
Some people who use my modpack seem to be getting this crash: https://gist.github.com/ChatFawkes/35b22d462723f7b658c7. That happens when using BluePower 0.1.766.

I updated BluePower to 0.2.835 my latest pack update and some users are getting this crash: http://pastebin.com/uG6V1gKQ. That doesn't point towards BluePower, but it seems similar to the other crash linked above.

I have searched the issues and this seems similar to #170

**Comment by GirafiStudios** [comment]
What are you doing, when you get this crash?

**Comment by ChatFawkes** [comment]
According to the players who got this crash they were just exploring the world when it happened. Then whenever they attempt to go back in the world they crash on load.

**Comment by GirafiStudios** [comment]
Hmm, sounds very weird. Is it the same they are saying with both be cases?

**Comment by Quetzi** [comment]
I don't think this is BluePower related at all, I've seen quite a few crashes like this with various mods in the trace depending on what happened to generate right before the crash.

**Comment by MoreThanHidden** [comment]
Not actively supporting the 1.7.10 version anyone can fork the last version and support it if they want to.
