### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by boredompwndu** [Qmunity/BluePower#272]
My action before the crash: Just before the crash, i sneak right clicked a RFTools Crafter (Tier 1) with a crescent hammer. (Breaking an removing it) There was a BluePower Manager connected to this, particularly on the output face of the manager. I broke the crafter, and then everything crashed. I had broken the crafter before without the crescent hammer, and no crash had occured.

Crash Report:
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 1/15/15 8:40 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at com.bluepowermod.helper.IOHelper.insert(IOHelper.java:243)
    at com.bluepowermod.helper.IOHelper.insert(IOHelper.java:228)
    at com.bluepowermod.tile.tier3.TileManager.acceptItemFromTube(TileManager.java:51)
    at com.bluepowermod.part.tube.TubeLogic.update(TubeLogic.java:173)
    at com.bluepowermod.part.tube.PneumaticTube.update(PneumaticTube.java:143)
    at uk.co.qmunity.lib.tile.TileMultipart.func_145845_h(TileMultipart.java:423)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.bluepowermod.helper.IOHelper.insert(IOHelper.java:243)
    at com.bluepowermod.helper.IOHelper.insert(IOHelper.java:228)
    at com.bluepowermod.tile.tier3.TileManager.acceptItemFromTube(TileManager.java:51)
    at com.bluepowermod.part.tube.TubeLogic.update(TubeLogic.java:173)
    at com.bluepowermod.part.tube.PneumaticTube.update(PneumaticTube.java:143)
    at uk.co.qmunity.lib.tile.TileMultipart.func_145845_h(TileMultipart.java:423)

-- Block entity being ticked --
Details:
    Name: qmunitylib.blocks.multipart // uk.co.qmunity.lib.tile.TileMultipart
    Block type: ID #653 (tile.qmunitylib:multipart // uk.co.qmunity.lib.block.BlockMultipart)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (42,8,-46), Chunk: (at 10,0,2 in 2,-3; contains blocks 32,0,-48 to 47,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Actual block type: ID #653 (tile.qmunitylib:multipart // uk.co.qmunity.lib.block.BlockMultipart)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: New World
    All players: 1 total; [EntityPlayerMP['boredompwndu'/35, l='New World', x=40.71, y=4.00, z=-44.09]]
    Chunk stats: ServerChunkCache: 725 Drop: 0
    Level seed: -8190849623944529957
    Level generator: ID 01 - flat, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (46,4,-47), Chunk: (at 14,0,1 in 2,-3; contains blocks 32,0,-48 to 47,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 314638 game time, 314638 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 7970 (now: false), thunder time: 85625 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.7.0_67, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 422766560 bytes (403 MB) / 1468530688 bytes (1400 MB) up to 2863661056 bytes (2731 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -XX:MaxPermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1277 Minecraft Forge 10.13.2.1277 62 mods loaded, 62 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1277} [Forge Mod Loader](modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1277} [Minecraft Forge](modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.4.83} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    appliedenergistics2{rv1-stable-1} [Applied Energistics 2](appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    iChunUtil{4.1.3} [iChunUtil](iChunUtil-4.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BackTools{4.0.0} [BackTools](BackTools-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    baublelicious{1.0.4} [Baublelicious](Baublelicious-1.7.10-1.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.9.2} [BiblioCraft](BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    qmunitylib{1.0} [QmunityLib](QmunityLib-1.7.10-0.1.69-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bluepower{0.2.835} [Blue Power](BluePower-1.7.10-0.2.835-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.7.10R3.0.0B9} [CoFH Core](CoFHCore-[1.7.10]3.0.0B9-40.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{6.3.1} [BuildCraft](buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{6.3.1} [BC Transport](buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{6.3.1} [BC Silicon](buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{6.3.1} [BC Builders](buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{6.3.1} [BC Energy](buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{6.3.1} [BC Factory](buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available

**Comment by MrKickkiller** [comment]
I had the same error, but in my case it envolved a pneumatic tube, a relay and a chest. The relay was dumping it's contents in the chest(They were only seperated by the tube). Crash happened when I broke the chest. World has become corrupt now. Crashes everytime I try to load in. Luckily was a test world :D

**Crash is reproducable.**
Error log: http://pastebin.com/7wuajA28
Minecraft was run from a dev environment, logged in and only using the files on this Github

**Comment by TheJulianJES** [comment]
Something in #276

**Comment by sylphio** [comment]
We got the same problem when somebody destroyed a chest used by a sorter.

**Comment by Quetzi** [comment]
When this happens is B:"Enable Tube Caching" set to true or false?

**Comment by Quetzi** [comment]
When this happens is B:"Enable Tube Caching" set to true or false?

**Comment by skuff84** [comment]
false

**Comment by MrKickkiller** [comment]
In my case: Enable Tube Caching is set to true

**Comment by MoreThanHidden** [comment]
Not actively supporting the 1.7.10 version anyone can fork the last version and support it if they want to.
