### ISSUE TITLE
Crash with bluepower

### ISSUE THREAD

**Issue by ReDesignedHD** [Qmunity/BluePower#277]
Something do to with the alloy furnace blacklist, http://pastebin.com/4kb0N0Ba

**Comment by ReDesignedHD** [comment]
when am i getting a reply here, i was told to post this here.

**Comment by Quetzi** [comment]
This looks like you have an invalid recipe in your instance. Minetweaking gone wrong perhaps?

**Comment by ReDesignedHD** [comment]
thank you for the help that seemed to solve the issue :D

**Comment by amadornes** [comment]
Solved? Closing :P
