### ISSUE TITLE
Logic Gate Error

### ISSUE THREAD

**Issue by Mattabase** [Qmunity/BluePower#279]
Transparent latches do not function as intended.

https://dl.dropboxusercontent.com/u/15990261/ShareX/2015/02/2015-02-01_22-04-38.mp4

Left Side - Correct 

Right Side - Not Correct

**Comment by amadornes** [comment]
The problem there is that our gates didn't use to have delays. They will from now on. They are being rewritten and transparent latches are some of the ones that still need to be finished. I'll close this issue as soon as I push everything to GitHub :P

**Comment by Mattabase** [comment]
Sounds good,was going to sit down and test all the gates. however I shall wait until the merge. 


Thank you sir.

**Comment by Pilad** [comment]
How long wait fix this : Disable some items that are still WIP (Red Alloy, Bundled Wire and Wireless transceivers) ?

**Comment by amadornes** [comment]
Those will hopefully be fully done and ready to play with in the next update :P

**Comment by Pilad** [comment]
And how long wayt ? Few days, week ?

**Comment by TheJulianJES** [comment]
#263 Some info.

**Comment by amadornes** [comment]
Derp. Forgot this is one of the gates I haven't fixed yet and I marked it as pending release xP
It might be ready next week, but I cannot give an exact date yet, I have some real life stuff to take care of too :/

**Comment by TheJulianJES** [comment]
@amadornes Okay but thanks for all the other work!

**Comment by TheJulianJES** [comment]
@amadornes But if you have some time you could probaly make it so that we can compile BluePower :)

**Comment by amadornes** [comment]
I will. It was another small derp on my side, I forgot to add the ColoredLights API :P
Oh, and feel free to join our IRC channel: #BluePower on esper.net. We're usually around there, if you want to ask anything/chat :P

**Comment by amadornes** [comment]
Forgot to close this when we pushed the release. Doing it now :P
