### ISSUE TITLE
[0.2.835] Recipe Mishap: White Lamp

### ISSUE THREAD

**Issue by AppleConnoiseur** [Qmunity/BluePower#282]
In this version you apparently create White Lamps with Black Lumar. Probably fixed in the coming version. ![Derpy recipe](https://dl.dropboxusercontent.com/u/547140/pix2/2015-02-06_03.20.22.png)

**Comment by Linkinexe** [comment]
I already reported this issue in #256 as there are more recipes which are related to colour based items and use the wrong respective type of wool or lumar.

**Comment by Quetzi** [comment]
Was sure the fix for this had already been released, apparently not so I just pushed an update.
