### ISSUE TITLE
Sapphire class in chisel 2

### ISSUE THREAD

**Issue by BuckitHead** [Qmunity/BluePower#283]
running the latest version of BP, running the latest Chisel 2. Both Sapphire glass are in chisel. When trying to make the ender io clear glass it turns into Reinforced Sapphire. Not sure what is the issue here but seems to be a issue. Reporting on both mods. Did some research and found that this was taken care of sometime ago, but looks to be back.

**Comment by Quetzi** [comment]
Was sure this fix had already been released, just pushed an update to Curse so this is now fixed.
