### ISSUE TITLE
Can't change Timer's interval. + some more things I found out

### ISSUE THREAD

**Issue by Seekula** [Qmunity/BluePower#287]
Hi there guys,
Like the title says, I can't change the Timer's interval. Is this an individual bug or do yu know about it ? If you need any info from me ask me (I just don't know what info I could add, becouse it's not crash ^.^)
-Jackob

+ I can't see blue wire I put on walls, and if I put in on walls I can't break it ..

**Comment by amadornes** [comment]
The gates and wires have been rewritten and they're being tested now. An update will probably be released in the next week or two.
