### ISSUE TITLE
Crash and error in console

### ISSUE THREAD

**Issue by Xee1** [Qmunity/BluePower#289]
I was testing the latest versions of BluePower / QmunityLib compiling by myself the mods (compiled 10min ago), and have appeared all these errors:
https://gist.github.com/Xee1/7b97f2d206dbff7bfced
https://gist.github.com/Xee1/0d841ab30cdb4c3c3764
http://pastebin.com/7pGjj1PB
http://pastebin.com/DzbuR0CN

And a crash:
http://pastebin.com/J4uCnaR5

**Comment by K-4U** [comment]
Sorry, we don't support crashreports from mods that you compiled yourself.

**Comment by Xee1** [comment]
Oh ok, thanks for the answer!
