### ISSUE TITLE
Volcano generation with other world generators

### ISSUE THREAD

**Issue by Firehead94** [Qmunity/BluePower#290]
Well you may or may not have seen my post on reddit about huge ass volcanoes (which I love) but its becoming a bit ridiculous in my honest opinion (speaking as a player and a server host). I assume the volcanoes height is determined by the biomes height or surrounding blocks due to how I see them generating now. When combined with mods like BoP or other custom world generators, volcanoes get so huge they A) cant even fully generate as they hit build height with ease and B) will disconnect players from servers due to networking issues, [See here](http://pastebin.com/NGpdaX0J). You will see that error 2 or 3 times minimum before you can log back in. That happened during initial generation of the landscape and [this](http://pastebin.com/JCbeRUbq) happened while trying to reload those chunks.

Its really not much of a problem when it comes to lower level biomes but once you get a volcano generating anywhere close to a mountain range or heaven forbid, Alps and Crags, you run into some seriously huge volcanoes/groups of volcanoes which devour a good 400-500 block radius which leaves lots of straight up and down walls of basalt on the volcano sides. 

I'd suggest a biome blacklist or something but even then, the volcanoes are big enough to cross over between biomes more often then not. 

Edit: I am also not 100% if fastcraft would cause these errors when it comes to world gen but its a bit late for me to be testing anything at the moment as I have school in the AM.

**Comment by Quetzi** [comment]
Last night I made some adjustments to volcano behaviour, they won't try and generate above world height anymore and the default config I've reduced the spawn frequency by 50%. Not sure what is going on with that error though, will look into it.

**Comment by Quetzi** [comment]
The crashes are caused by us trying to generate loot chests above world height, coincidentally my commits last night will also prevent that from happening.

**Comment by Quetzi** [comment]
While this isn't a biome blacklist, it will prevent volcano generation at extreme heights so should alleviate most of the concerns.
