### ISSUE TITLE
Add redstone tubes

### ISSUE THREAD

**Issue by Jhary** [Qmunity/BluePower#291]
Today I was playing around with bluepower and funky locomotion and suddenly realized there are no redstone pneumatic tubes. Could you please add them? That would be awesome

**Comment by Quetzi** [comment]
Already done, just not in the current release. Soon ;)

**Comment by planetguy32** [comment]
Are they in the current release? I'm playing with v0.2.962 and can't seem to find anything about them in-game, and this issue was as close as I could find on Google.

**Comment by amadornes** [comment]
They don't show up as a different item. You just need to place a tube and right-click it with a wire :)

**Comment by planetguy32** [comment]
Awesome, works perfectly. Thanks for the help.

**Comment by amadornes** [comment]
No problem :)
The reworked version of BluePower we're currently working on will show them in the creative tab (and in NEI) and will also have a crafting recipe to add wire to the tube, to avoid any further doubts ;)
