### ISSUE TITLE
wires don't connect

### ISSUE THREAD

**Issue by LiEyWe** [Qmunity/BluePower#292]
Well, bluestone wires aren't connecting to anything
![2015-02-20_16 49 28](https://cloud.githubusercontent.com/assets/4921509/6289440/8bb1de4c-b920-11e4-858f-50ef62519e74.png)

**Comment by Quetzi** [comment]
Try using QmunityLib build 69, should fix this issue for now.

**Comment by amadornes** [comment]
As @Quetzi said, downgrade to QmunityLib 0.1.69 and it'll be fixed. It's just a rendering issue :P
