### ISSUE TITLE
basalt volcano generation

### ISSUE THREAD

**Issue by dazsim** [Qmunity/BluePower#293]
I'm currently testing the mod in a private pack and I was hoping there might be a way to change size of the volcano's spawning in the world.  I'm flying around in creative and finding them spawning as close as every 500 blocks (if not closer).  With the volcano sizes being so massive this leads to a world with many volcano's in quick succession.  If we could change the size it would help with getting the worldgen to match the pack the mod is being used in.

**Just edited post as I found a config to reduce spawn rates but they are currently still way way too massive for my liking. Otherwise, MASSIVE thanks for this mod, its so nice to see how much you've already added!

thanks
daz
(@workshopcraft)

**Comment by Quetzi** [comment]
If you see #290 you will see that there are several changes to volcano gen pending release. We're hoping to get the next update out this weekend.
