### ISSUE TITLE
Newest version says Redstone Tubes are in - They are not

### ISSUE THREAD

**Issue by Jhary** [Qmunity/BluePower#298]
Hello!

Today I downloaded the newest version and was very happy to see "Redstone Tubes were added". Ingame I was not able to find these.
After digging through your sourcecode on Github it seems that you forgot to register these?

**Comment by amadornes** [comment]
Place a tube and click it with a wire. We'll add a way to craft them directly in the next one

**Comment by Jhary** [comment]
oh my god ok *lol* thanks for the info
