### ISSUE TITLE
4 bugs  v891

### ISSUE THREAD

**Issue by Crazy-KSK** [Qmunity/BluePower#299]
http://i.imgur.com/ZZlqzp6.jpg

~~1: if you remove the block under any blue power component they stay and don't fall off and every time that floating construct then gets updated it spews parts~~

~~2:removing and replacing this torch somehow updates 1
I have tried placing blocks around it to make sure there are no ghost blocks there still happens
it has to be a redstone torch though normal block does not do it~~

Edit: those things got fixed 

3: this seems to be an issue with the null cell all the other gates work fine in that regard

4: a redstone torch in the same block as a wire does not power the wire

Edit:  http://i.imgur.com/uMtL35I.png http://i.imgur.com/MeP7cYX.jpg this happens when removing a bundled wire

**Comment by amadornes** [comment]
Fixed 3 and 4. Thanks for reporting them! :D
