### ISSUE TITLE
bundled wire does not connect through hollow covers 

### ISSUE THREAD

**Issue by Crazy-KSK** [Qmunity/BluePower#300]
http://i.imgur.com/Rsu4SEz.jpg
edit: yes I mean the freestanding variant of course
I also found some other oddities 
http://i.imgur.com/5ujVy1L.png
the stone corner is preventing the lower left and right wires from connecting 
the upper right one is more of a  "would be nice if that worked" (its a freestanding wire going through a hollow cover)
same as this http://i.imgur.com/DN2kEpS.png
and placing wires and gates on the inside of covers ^_^

**Comment by amadornes** [comment]
The issue with freestanding wires has been fixed, but not the issue with the corners. I'll look into it now.
The wires going over eachother will hopefully be a thing at some point. We're planning on adding our own microblock that acts as a normal cover, but lets wires through (I guess that's what you wanted) ;)

**Comment by Crazy-KSK** [comment]
yeah that sounds like it would make that possible awesome! =D

**Comment by amadornes** [comment]
Made a temporary fix for this. It'll be properly fixed when the multipart system gets refactored :)
