### ISSUE TITLE
Mod Description?

### ISSUE THREAD

**Issue by Gambigobilla** [Qmunity/BluePower#302]
Please add some sort of mod description, you don't seem to have some sort of decent wiki page or a forum post. From what i gather it's some sort of tech mod but i don't know why i should choose your mod over the main contenders (like TE4, EIO, MFR, XU)

**Comment by CubeWrench202** [comment]
XU?

**Comment by GirafiStudios** [comment]
Extra Utilities

**Comment by CubeWrench202** [comment]
Oh.....Anyway you should change the name from "Mod description" to "Mod info", since a description is already done in the github readme/curseforge overview.

**Comment by Quetzi** [comment]
This has come up a few times, we are aware of a lack of documentation. We are still in a stage of fairly heavy development so a lot of the docs would be outdated quite quickly. As for the general type of tech mod we are, it is fairly widely known, though not explicitly stated that we, along with Project Red, replicate a lot of the features from Red Power 2. As such Blue Power can happily sit alongside other tech mods.
