### ISSUE TITLE
[Enhancement]3 Power Levels and other minor suggestion/ideas:

### ISSUE THREAD

**Issue by CubeWrench202** [Qmunity/BluePower#303]
Just a little idea to @K-4U, my idea is to have:

 - The 5kv power wire ( Low voltage cable ).

 - The 10kv power wire ( Medium voltage cable ).

 - The 20kv power wire (High voltage cable).

A new level of power means also a new transformer, to change from HV to MV.
I don't know what you have planned for recipes, but considering that blue alloy ingot + wool was the old blue alloy wire recipe and now is used on the white bluestone wire you will have to think the recipe, so these are my 3 ideas : 

 - Rubber trees, which will work like the MFR trees, they drop the wood piece and a piece of rubber, i think who may be the best for this job is @MineMaarten.

 - Teslatite Ingot, created with the alloy furnace via combining Blue alloy ingot + Infused Teslatite.

 - Or simply think in a recipe involving blue alloy ingots.

**Comment by Quetzi** [comment]
I would actually like the bluestone wire to change so that it includes redstone as part of the recipe somehow, which leaves pure teslatite type recipes free for power. Rubber trees we've already discussed and I think we'll be going with a process of draining rubber fluid from rubber trees eventually.

**Comment by Quetzi** [comment]
Actually, going to close this as all of these ideas have been extensively discussed internally already.

**Comment by CubeWrench202** [comment]
Sounds good :), i'm interesting to see what you'll came out with.
