### ISSUE TITLE
[Bug] Duplication bug with Industrial craft + Bluepower

### ISSUE THREAD

**Issue by tntblockman** [Qmunity/BluePower#304]
Mods involved:
Bluepower 1.7.10-0.2.890
industrialcraft-2-2.2.681
Fastcraft 1.7.10-3.4.0.7 also installed

Uncovered in my opinion a major ore duplication bug.  Setup involves any of the Industrialcraft ore processing machines fitted with "Ejector Upgrade", which in turn is ejecting to BP "Sorting Machine".  With this setup, ores which are been ejected to Bluepower sorting machine seem to get infinity duplicated per tick.  

So example there are 64x "Purified Crushed Lead Ore" located in output slot of "Ore Washing Plant" with a installed "Ejector Upgrade", ejecting into a BP "Sorting machine" == 64x (per tick) infinity amounts of "Purified Crushed Lead Ore" injected into tube system.

Also the ore located inside any ic2 ore processing machine remains there.

**Comment by MoreThanHidden** [comment]
Not actively supporting the 1.7.10 version anyone can fork the last version and support it if they want to.
