### ISSUE TITLE
world breaking crash v892

### ISSUE THREAD

**Issue by Crazy-KSK** [Qmunity/BluePower#305]
http://i.imgur.com/njE9Rz8.jpg I'm pretty sure the right wire is supposed to be powered?
break the stone
http://i.imgur.com/8YzGr5B.jpg
crash just after the screenshot http://pastebin.com/MpimU429
crash on trying to reload the world http://pastebin.com/LHNQ4MAA

**Comment by amadornes** [comment]
No, the wire is not supposed to be powered as a wire cannot be powered by another one unless they're connected directly.
That dupe bug is the same you reported yesterday and got fixed right after that (even you marked it as already being fixed before I could tell you), so just update BluePower and it should be fixed.

**Comment by Crazy-KSK** [comment]
I have the newest version available on curse forge 0.2.892 and yes the previous bug does not happen anymore on this version

**Comment by amadornes** [comment]
Oh? :|

**Comment by Crazy-KSK** [comment]
place 2 pieces of blue wire on a block and break it and it crashes with wire spew overload, one wire alone does not suffice 
I'm on irc btw if that's more convenient

**Comment by amadornes** [comment]
I think I somehow fixed it a while ago. If it still happens let me know and I'll open the issue again :)
