### ISSUE TITLE
Crash Report: Updating Screen Events

### ISSUE THREAD

**Issue by stephenmc608** [Qmunity/BluePower#309]
I was using the Calcinator from EE3 to create Minium Dust. I put 8 Diamonds in the input slot and some Coal in the fuel slot. When I tried to take the Minium Dust out of the Calcinator, my game crashed with this report:
https://gist.github.com/stephenmc608/268534d0a8937bb9f52f

I submitted this to the EE3 GitHub, but they told me to submit it here.

BluePower Version: 0.2.892
EE3 Version: 0.2.433.
Forge Version: 10.13.2.1307

**Comment by GirafiStudios** [comment]
Can you log into your world again after this?
Can you make a pastebin of your EE3 config too?

**Comment by Quetzi** [comment]
This is fixed as of https://github.com/Qmunity/BluePower/commit/5147ffa4d3c5576586298f16b216cc0c6a147eee although there isn't a release version with this fix in yet. We'll get one out this weekend.

**Comment by stephenmc608** [comment]
Ok. Thank you for the quick response!

GirafiStudios: I was able to log into my world, but every time that I tried to remove an item from the Calcinator or Aludel, I crashed.
Here is the EE3 Config: https://gist.github.com/stephenmc608/62221e4c4d6ad28ac0be

**Comment by GirafiStudios** [comment]
Try to break the Calcinator or Aludel instead ^^^
Your config looks just fine btw. ^^

**Comment by Dynious** [comment]
FYI The Calcinator inventory length is 4. The line added in that commit won't change behavior for the Calcinator and (if that is the only change to fix this) still crash.

**Comment by amadornes** [comment]
What should I have done instead, @Dynious? :P

**Comment by Dynious** [comment]
A quick (dirty) fix could be add a inv.getSizeInvetory() > y * 3 + x check before this line:
https://github.com/Qmunity/BluePower/blob/5147ffa4d3c5576586298f16b216cc0c6a147eee/src/main/java/com/bluepowermod/recipe/RecipeNullCell.java#L72

No ideal, the best thing to do is not assume the crafting area is 3*3, but that will probably require a lot of changes.

**Comment by amadornes** [comment]
@Quetzi, that'll make it so it doesn't work in the player's crafting grid (and that's something I wanted to work). I'll try to tweak it a bit so it also works in the player's inventory, but that should at least prevent the crash from happening

**Comment by Quetzi** [comment]
I considered putting that check in the getItemAt method but I figured that method shouldn't be getting called unnecessarily anyway.

**Comment by Dynious** [comment]
Wouldn't checking the 3x3 crash (or mess with) the player inventory crafting anyways?
What I'd do: 
1. Check if the IInventory given by the event is an instance of InventoryCrafting.
2. Check the size of the inventory and decide if it's 2x2, 3x3 (or none of those (return null))
3. Handle 2x2s and 3x3s with it's own code (you could get the up, down, left, right slots and have the same code for 2x2 and 3x3 after that).
