### ISSUE TITLE
Sorting machine

### ISSUE THREAD

**Issue by mikiones** [Qmunity/BluePower#310]
The sorting machine when on non redstone driven node should be able to be disabled with redstone signal(red power behaviour) consider setup when you have tube loop and you need temporarily disable sorting machine.

**Comment by philipgiuliani** [comment]
How have you built the sorting machine? I dont know how to power it without project red... No solar panels ect..?

**Comment by TrupJP2** [comment]
I was also puzzled by the lack of bluetricity items. Turns out that all the advanced items simply work without requiring any power. It would probably be helpful to remove the charge bar from the GUI.

**Comment by MoreThanHidden** [comment]
No longer an issue with newer versions see Work in progress / Project for further details.
