### ISSUE TITLE
Items deleted from tubes

### ISSUE THREAD

**Issue by Brycey92** [Qmunity/BluePower#315]
One of my admins was performing a test of BluePower by pumping items from a BC quarry to some chests when he noticed items disappearing from the pneumatic tubes and never showing up in the chests.

**Comment by GirafiStudios** [comment]
What version of BluePower are you using?

**Comment by Brycey92** [comment]
0.1.766. Should I try updating to a newer version?

**Comment by GirafiStudios** [comment]
Yeah try updating to the latest version of Blue Power and Qmunity Lib. It's recommended that you take a backup of your world first tho.

**Comment by Brycey92** [comment]
Updating from 766 directly to latest BP and QmunityLib causes a freeze after the world begins loading, as does updating from 766 to BP 832 and QmunityLib 69. My world is 6.5GB, if that makes a difference.

**Comment by MoreThanHidden** [comment]
No longer an issue with newer versions see Work in progress / Project for further details.
