### ISSUE TITLE
Filters doesn't use ghost items

### ISSUE THREAD

**Issue by zlepper** [Qmunity/BluePower#317]
In inventory where you can specify what items the filter should allow trough items are stored, it is not just ghost items, which would make more sense considering the sorting machine does that.

**Comment by amadornes** [comment]
This is intended. We want to allow the players to be able to configure the filter with anything that can do item I/O such as tubes.
We have considered making it a config option or something that you can toggle in the GUI of each machine but we still haven't decided it. If we make it a config option, it'll probably be added in the "Modular Update", which should happen relatively soon (we can't give an ETA yet, but it'll probably be before we update to 1.8.
