### ISSUE TITLE
Constant server crashing.

### ISSUE THREAD

**Issue by Kirimato** [Qmunity/BluePower#318]
We are on ver.892 and qmunitylib .92 and we have been experiencing this crash for the past couple of worlds and it is continuously crashing the server.

http://pastebin.com/UWpBYht5

**Comment by lewile1** [comment]
We are experiencing the same issue, this is occurring trying to startup the FTB Pathfinder server as well.

http://pastebin.com/F1L18LuU

Additionally, there are more loggings in the load screen regarding FML being unable to lookup bluepower items and it asks "Is there something wrong with the registry?"  Below is a link to the FML Server in google drive.

https://drive.google.com/file/d/0B0TVdrEScoNjeHdfeThWeWFRb28/view?usp=sharing

**Comment by Kirimato** [comment]
Update: Updated to the latest versions of BluePower and QmunityLib.
Still the same error. 
http://pastebin.com/MMLcr9hX

**Comment by amadornes** [comment]
I really have no idea what is causing it. I've looked through all the code and I can't find it :/
I'll continue looking for it, but I'm not sure what the issue could be

**Comment by Kirimato** [comment]
UPDATE
http://prntscr.com/6r10oa
These crashes have all been happening within 5-10 minutes of each other.

**Comment by Optimus22Prime** [comment]
It may be https://github.com/Qmunity/BluePower/issues/412 related.
Also this http://forums.technicpack.net/topic/229342-server-crashes-on-startup-with-javalangnullpointerexception-exception-in-server-tick-loop/ help me a lot, -Djava.awt.headless=true fixed this issue for me.

**Comment by MoreThanHidden** [comment]
No longer an issue on newer versions
