### ISSUE TITLE
Crash with BiblioCraft 1.10.0

### ISSUE THREAD

**Issue by xeronut** [Qmunity/BluePower#321]
http://pastebin.com/Wzh4Uap2 - using BiblioCraft 1.10.0 and BluePower 0.2.892.  Crash occurs when I pull a paneled furniture piece from the output slot of the Paneler GUI.  Tested with Chisel2 limestone & hex plating, Colored Lights glowstone, Thaumcraft Arcane Stone & vanilla cobblestone, same log.  Thank you for your time!

**Comment by GirafiStudios** [comment]
From what i know, the null cell issue is already fixed. A new release of BluePower is just not out yet.

**Comment by amadornes** [comment]
As Girafi was saying, this has already been fixed. A new build will be pushed out as soon as we get a couple of other fixes ready :)
