### ISSUE TITLE
Server freeze on world load after update

### ISSUE THREAD

**Issue by Brycey92** [Qmunity/BluePower#322]
Updating from 766 directly to latest BP and QmunityLib causes a freeze after the world begins loading, as does updating from 766 to BP 832 and QmunityLib 69. My world is 6.5GB, if that makes a difference.

This issue was discovered while trying to update BP in attempt to solve #315.

**Comment by Quetzi** [comment]
Does this happen every time you start the world or just the first time? There is a world upgrade process that needs to run on old saves so if you have a large save you may notice it more than others

**Comment by Brycey92** [comment]
It happens every time I start the world. Eventually, the server just acts as if it's stopped, and McMyAdmin restarts it. It never appears to complete the upgrade process.

**Comment by Quetzi** [comment]
You have a console log for it?

**Comment by Brycey92** [comment]
Sure, they're at http://repo.galaxy-craft.com/logs/

**Comment by Xaethon** [comment]
I've had this as well, server hanging immediately after startup on the latest builds. Downgrading to 766 and QmunityLib to 166 immediately resolved the issue. This was also a cauldron server and both of the latest builds were on the server for several days without issue before the problem occured. Logs show nothing unusual from BluePower or any other mods.

**Comment by Brycey92** [comment]
For me, the problem occurred upon every server start with the builds I mentioned, and downgrading to anything but my original version resulted in the same issue.

**Comment by MoreThanHidden** [comment]
No longer an issue on newer versions.
