### ISSUE TITLE
rendering issue

### ISSUE THREAD

**Issue by Trixz2018** [Qmunity/BluePower#325]
with my custom pack of 200 mods i recently added the latest bluepower and qmunity lib an noticed that items are not rendering in the tubes or magtubes for some odd reason, also this pack is on a server if that helps.

**Comment by aldra2012** [comment]
ok a lil bit more testing and this is weird like for example when a transposer ejects items, the tubes won't render the items but if i break a tube before the items reach the chest but when the items are bouncing back to the transposer the items are rendering.

**Comment by amadornes** [comment]
Yeah, that's a known issue. They don't render until they reach an intersection. We're still trying to figure out why.

**Comment by MRebhan** [comment]
Hmm this doesn't occur to me

**Comment by MoreThanHidden** [comment]
No longer an issue with newer versions see Work in progress / Project for further details.
