### ISSUE TITLE
GL Render related crash

### ISSUE THREAD

**Issue by VapourDrive** [Qmunity/BluePower#328]
Playing the latest version of Bluepower as of yet - 1.7.10-0.2.918 with shaders.
Regardless of what shaderpack you are using (or none), if you select a gate in your hotbar and the in world render initiates for seeing the orientation of it being placed the game freezes up and the following few lines cycle through the console:
[21:49:28] [Client thread/ERROR]: ########## GL ERROR ##########
[21:49:28] [Client thread/ERROR]: @ Post render
[21:49:28] [Client thread/ERROR]: 1286: Invalid framebuffer operation
GL error 0x0506: Invalid framebuffer operation (Fb status 0x8CDD) at pre beginRender
GL error 0x0506: Invalid framebuffer operation (Fb status 0x8CDD) at shadow endRender
GL error 0x0506: Invalid framebuffer operation (Fb status 0x8CDD) at pre-renderCompositeFinal
GL error 0x0506: Invalid framebuffer operation (Fb status 0x8CDD) at pre-useProgram
GL error 0x0506: Invalid framebuffer operation (Fb status 0x8CDD) at pre-final
GL error 0x0506: Invalid framebuffer operation (Fb status 0x8CDD) at renderCompositeFinal
GL error 0x0506: Invalid framebuffer operation (Fb status 0x8CDD) at pre-useProgram
I also have the latest version of the shaders mod.

**Comment by amadornes** [comment]
Yeah, the shaders mod causes issues with the ghost image of the gates... It's going to be hard to debug because I don't think you can install it on a dev environment, but I'll try to find a way to fix it :)

**Comment by VapourDrive** [comment]
Any update on this? have you managed to narrow down the issue Amadornes?

**Comment by amadornes** [comment]
I haven't figured out why it happens yet, no :/

**Comment by Jimbob15082** [comment]
I seem to be having the same issue with bluepower and shaders, only with a slightly different error message:

[17:54:27] [Client thread/ERROR]: ########## GL ERROR ##########
[17:54:27] [Client thread/ERROR]: @ Post render
[17:54:27] [Client thread/ERROR]: 1286: Invalid framebuffer operation
GL error 0x0506: Invalid framebuffer operation (Fb status 0x8CDD) at pre-final
GL error 0x0506: Invalid framebuffer operation (Fb status 0x8CDD) at renderCompositeFinal
GL error 0x0506: Invalid framebuffer operation (Fb status 0x8CDD) at pre-useProgram

**Comment by MoreThanHidden** [comment]
Not actively supporting the 1.7.10 version anyone can fork the last version and support it if they want to.
