### ISSUE TITLE
Ability to Disable Marble Generation

### ISSUE THREAD

**Issue by Waremaster** [Qmunity/BluePower#334]
I was reading earlier posts from last year about this issue and you replied with a new configurable option as a solution.  I was wondering if you've removed that functionality?  I am not seeing it anywhere in the configuration file, which is quite small, so i doubt i'm overlooking it. I also tried regenerating a new config and to no avail. 

Thanks :)

**Comment by Quetzi** [comment]
It hasn't been removed, just set marble vein size to zero

**Comment by Waremaster** [comment]
Where at Quetzi? I apologize but, i feel you didn't fully read issue.

**Comment by Waremaster** [comment]
I can post the newly generated configuration file if you like?

**Comment by Waremaster** [comment]
Nevermind! Sorry.. found it!  I figured I would look one last time. It runs into the configuration with the volcano stuff.  I was overlooking. Sorry for being a noob.. haha
