### ISSUE TITLE
Wires do not (fully) work on doors

### ISSUE THREAD

**Issue by ghost** [Qmunity/BluePower#339]
19 seconds video demonstrating the bug: http://youtu.be/l9ZSZAAnzgc (All wire types are used)
Forge 10.13.3.1395, BP 0.2.928, QmunityLib 0.1.107.
Only BP is installed.

**Comment by amadornes** [comment]
Interesting... Hadn't seen that one before... I'll try to fix it today :)

**Comment by TheJulianJES** [comment]
I don't know this fully but I'm thinking doors close if an adjacent block updates. But I'm not sure :)

**Comment by ninehous** [comment]
I tried forcing an update but it didn't work.

**Comment by TheJulianJES** [comment]
Well, pistons are working different.

**Comment by MoreThanHidden** [comment]
No longer an issue with newer versions see Work in progress / Project for further details.
