### ISSUE TITLE
Reinforced sapphire glass not see-trough

### ISSUE THREAD

**Issue by partytown** [Qmunity/BluePower#345]
When i craft reinforced sapphire glass its see-trough in my inventory and has the texture it normally would have but when i place it down it isnt see-trough at all and is just solid 1 colour, except for the borders. I am using bluepower version 0.2.928 and default configs.

**Comment by amadornes** [comment]
Are you using Optifine? Somebody had the same issue with it installed

**Comment by partytown** [comment]
yes i am and i just tested and that was indeed the problem. thank you for help

**Comment by amadornes** [comment]
No worries :)
