### ISSUE TITLE
Crash When Placing Pneumatic Tube 

### ISSUE THREAD

**Issue by joeknex** [Qmunity/BluePower#349]
The game crashes when you place any of the Pneumatic Tube 
Edit: This is also the Accelerator and MagTube
http://openeye.openmods.info/crashes/e04cebf9188faa21387c087efeccc391

**Comment by Xee1** [comment]
See this: https://github.com/Qmunity/BluePower/issues/348
Already fixed.

**Comment by Quetzi** [comment]
Pushed a new QmunityLib to resolve this. You need at least 0.1.109

**Comment by joeknex** [comment]
Just to confirm this is fixed :)
