### ISSUE TITLE
Forge Multi-part Integration Crash

### ISSUE THREAD

**Issue by carTloyal123** [Qmunity/BluePower#355]
Version 0.2.9.38, ForgeMultipart-1.7.10-1.2.0.344-universal

Mousing placed red alloy wire with a stone cover in hand crashes client.
Crash Report:http://pastebin.com/y265wwWb

**Comment by abalabahaha** [comment]
Downgrading to ForgeMultipart 1.1.x.xxx worked for me

**Comment by Tencao** [comment]
For the record, it's impossible to downgrade ForgeMultipart, since it auto-updates to 1.2.x
We really need an update on this

**Comment by amadornes** [comment]
This was fixed a while ago and I thought it had already been pushed. Sorry for the delay! :S
It'll be available here as soon as the file is approved: http://minecraft.curseforge.com/mc-mods/224785-qmunitylib/files/2241123

**Comment by amadornes** [comment]
It's available now :)
