### ISSUE TITLE
Forge multipart crash

### ISSUE THREAD

**Issue by Tencao** [Qmunity/BluePower#359]
http://pastebin.com/E9v1KGWG

Forge version 1403
Bluepower 0.2.938
QmunityLib 0.1.109
CodeChickenCore 1.0.7.45
NEI - 1.0.5.110
CodeChickenLib - 1.1.3.138
ForgeMultipart - 1.2.0.344

**Comment by abalabahaha** [comment]
Downgrading ForgeMultipart to 1.1.x.xxx worked for me

**Comment by Tencao** [comment]
I'm going to close this issue, since it was fixed, but the dev forgot to confirm it fixed and close it.
