### ISSUE TITLE
Red Alloy Wire

### ISSUE THREAD

**Issue by abalabahaha** [Qmunity/BluePower#360]
Placing more red alloy wire to extend active red alloy wire in multiplayer seems to delay everything else (chat messages, mob movements, etc.) until all the new red alloy wire shows up, which takes quite a while.
Edit: Placing/removing something that causes a block update in a multipart block containing active red alloy wire also seems to delay stuff

**Comment by TheJulianJES** [comment]
QmunityLib is currently being rewritten. So it can take some time until this bug is fixed. I also have some lag problems but I would recommend to use BlueStone Wire which has no signal lose and works a bit better. :)

**Comment by MoreThanHidden** [comment]
No longer an issue with newer versions see Work in progress / Project for further details.
