### ISSUE TITLE
Red alloy wire funkyness

### ISSUE THREAD

**Issue by MrKickkiller** [Qmunity/BluePower#363]
Evidence nr.1 :http://gyazo.com/f43ec0ffbee1e79ab2d7174035b3bd7c
Evidence nr.2 :https://www.dropbox.com/sh/utoyfsyu65u7h7h/AAD__c8H0OmE0b-Pd1epEhHTa?dl=0

It seems that it either decides to:
- Go from signal strength 1, straight to 254
- Go from signal strength 82 (before a corner piece) to 170, continues counting UP untill it reaches 255 and then suddenly going back down again

PS: That gate in evidence nr.1 is my work (currently using same layout as AND-Gate)
PS2: The world is created in my dev environment with the code for the before mentioned gate. Yet there are no gates in that world, nor are there any changes to the code other than in PartManager (registering), my own Class, a png and a psd.
See :http://gyazo.com/02aae6ddf3d715ae654063235079fb1e

**Comment by SoniEx2** [comment]
torch -> single wire, works fine

torch -> 2 wire, has strength 1 glitched

torch -> 3 wire, has strengths 1 and 2 glitched

torch -> n wire, has strengths from 1 to n-1 glitched.

**Comment by MrKickkiller** [comment]
Closed in recent commit: 34f30acb46dfae77392c500d873c83bc11eb8a26
