### ISSUE TITLE
Crash with (bundled) red alloy wire and RGB lamp

### ISSUE THREAD

**Issue by SoniEx2** [Qmunity/BluePower#364]
![](http://i.imgur.com/FHvOZF9.png)

Powering the wire and switching that lever crashes

Oh and it kills the world. Don't do it in worlds you care about.

**Comment by Quetzi** [comment]
Any kind of stacktrace for this crash?

**Comment by SoniEx2** [comment]
Yeah but it's a lot of propagate(). Infinite recursion.

**Comment by amadornes** [comment]
Caused by #363

**Comment by SoniEx2** [comment]
They're still 2 separate issues as they have very different behavior...

**Comment by amadornes** [comment]
But they are caused by the same issue in the code, so they can be considered the same. Multiple case scenarios which prove it doesn't work as it should just shows that it needs a fix, but it doesn't make them two different issues.
