### ISSUE TITLE
issue between BluePower project table and Malisis Doors

### ISSUE THREAD

**Issue by dankfrog** [Qmunity/BluePower#366]
http://paste.feed-the-beast.com/view/210da1e6

dont know who's end its on but i will be reporting it to Malisis Doors dev as well.

**Comment by GirafiStudios** [comment]
What are you doing, to make this crash occur?

**Comment by abalabahaha** [comment]
Apparently has to do with a rusty hatch from Malisis failing to render in a GUI/Inventory slot. Line 86 is 
```
if (renderType == RenderType.ITEM_INVENTORY)
```
It feels like Malisis can't detect what type of inventory slot the Project Table is when trying to render the hatch in the slot...

**Comment by MoreThanHidden** [comment]
No longer an issue on newer versions.
