### ISSUE TITLE
Issue with air/stacking?

### ISSUE THREAD

**Issue by SortYourModOut** [Qmunity/BluePower#367]
Every time I try and stack or create something using air in WorldEdit, my client (not server) instantly crashes to desktop. This is the latest crash log.

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 08/06/15 11:41
Description: Rendering Block Entity

java.lang.ClassCastException: com.bluepowermod.blocks.worldgen.BlockStoneOre cannot be cast to com.bluepowermod.blocks.machines.BlockLamp
	at com.bluepowermod.client.renderers.RenderLamp.func_147500_a(RenderLamp.java:207)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.bluepowermod.client.renderers.RenderLamp.func_147500_a(RenderLamp.java:207)

-- Block Entity Details --
Details:
	Name: bluepower.lamp // com.bluepowermod.tileentities.tier1.TileLamp
	Block type: ID #1317 (tile.bluepower:basalt_brick // com.bluepowermod.blocks.worldgen.BlockStoneOre)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-27,53,-1230), Chunk: (at 5,3,2 in -2,-77; contains blocks -32,0,-1232 to -17,255,-1217), Region: (-1,-3; contains chunks -32,-96 to -1,-65, blocks -512,0,-1536 to -1,255,-1025)
	Actual block type: ID #1317 (tile.bluepower:basalt_brick // com.bluepowermod.blocks.worldgen.BlockStoneOre)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['PhunkyPoptarts'/21460, l='MpServer', x=-3.92, y=52.62, z=-1228.10]]
	Chunk stats: MultiplayerChunkCache: 380, 380
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-31,57,-392), Chunk: (at 1,3,8 in -2,-25; contains blocks -32,0,-400 to -17,255,-385), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 6173257 game time, 6399355 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 12 total; [EntitySpider['Spider'/331, l='MpServer', x=-63.35, y=-0.06, z=-3.10], EntityClientPlayerMP['PhunkyPoptarts'/21460, l='MpServer', x=-3.92, y=52.62, z=-1228.10], EntityCow['Cow'/21463, l='MpServer', x=7.11, y=66.00, z=-1261.27], EntityCow['Cow'/21465, l='MpServer', x=0.94, y=65.00, z=-1284.91], EntityItem['item.tile.sapling.spruce'/21466, l='MpServer', x=-51.75, y=70.13, z=-1194.19], EntityChicken['Chicken'/21470, l='MpServer', x=-29.59, y=67.00, z=-1281.47], EntityChicken['Chicken'/21471, l='MpServer', x=37.34, y=68.00, z=-1273.32], EntitySheep['Sheep'/21473, l='MpServer', x=35.63, y=64.00, z=-1279.31], EntityChicken['Chicken'/21474, l='MpServer', x=42.53, y=62.00, z=-1288.67], EntitySheep['Sheep'/21478, l='MpServer', x=27.00, y=63.00, z=-1168.90], EntitySheep['Sheep'/21490, l='MpServer', x=51.52, y=68.69, z=-1194.34], EntitySpider['Spider'/252, l='MpServer', x=6.63, y=-8.62, z=57.71]]
	Retry entities: 0 total; []
	Server brand: cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 60296384 bytes (57 MB) / 1532493824 bytes (1461 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -Xms256M -Xmx2048M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1263 Minecraft Forge 10.13.2.1263 105 mods loaded, 105 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.85.1263} [Forge Mod Loader] (forge-1.7.10-10.13.2.1263-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1263} [Minecraft Forge] (forge-1.7.10-10.13.2.1263-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	appliedenergistics2-core{rv2-alpha-26} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Aroma1997Core{1.0.2.13} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NotEnoughItems{1.0.3.67} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.67-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IC2{2.2.654-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.654-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	appliedenergistics2{rv2-alpha-26} [Applied Energistics 2] (appliedenergistics2-rv2-alpha-26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AromaBackup{0.0.0.5} [AromaBackup] (AromaBackup-1.7.10-0.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	bdlib{1.5.1.32} [BD Lib] (bdlib-mc1710-1.5.1.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BetterTitleScreen{1.7.10-1.1} [Better Title Screen] (BetterTitleScreen-1.7.10-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BiblioCraft{1.9.1} [BiblioCraft] (BiblioCraft[v1.9.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CoFHCore{1.7.10R3.0.0B8} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B8-36.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Core{6.2.4} [BuildCraft] (buildcraft-6.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forestry{3.1.1.259-unstable} [Forestry for Minecraft] (forestry_1.7.10-3.1.1.259-unstable.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	bluepower{0.1.766} [Blue Power] (BluePower-1.7.10-0.1.766-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Transport{6.2.4} [BC Transport] (buildcraft-6.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Silicon{6.2.4} [BC Silicon] (buildcraft-6.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Builders{6.2.4} [BC Builders] (buildcraft-6.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Energy{6.2.4} [BC Energy] (buildcraft-6.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Factory{6.2.4} [BC Factory] (buildcraft-6.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CarpentersBlocks{3.3.3} [Carpenter's Blocks] (Carpenter's Blocks v3.3.3 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ChickenChunks{1.3.4.14} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.14-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ChiselFacades{2.1} [Chisel Facades] (ChiselFacades-1.7.10-2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ComputerCraft{1.65} [ComputerCraft] (ComputerCraft1.65.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CustomOreGen{1.2.13} [Custom Ore Generation] (CustomOreGen-1.7.10-1.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Enchiridion{1.1} [Enchiridion] (Enchiridion-1.7.X-1.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	EnderStorage{1.4.5.25} [EnderStorage] (EnderStorage-1.7.10-1.4.5.25-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	EE3{0.2.362} [Equivalent Exchange 3] (EquivalentExchange3-1.7.10-0.2.362.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Baubles{1.0.1.8} [Baubles] (Baubles-1.7.10-1.0.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ForgeMultipart{1.1.0.314} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ExtraUtilities{1.2.0} [Extra Utilities] (extrautilities-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	factorization.notify{1.0} [Factorization Notification System] (Factorization-1.7.10-0.8.88.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	factorization{1.7.10-0.8.88.2} [Factorization] (Factorization-1.7.10-0.8.88.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	factorization.misc{1.7.10-0.8.88.2} [Factorization Miscellaneous Nonsense] (Factorization-1.7.10-0.8.88.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded{1.7.10R2.8.0RC5} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	gendustry{1.4.2.46} [GenDustry] (gendustry-mc1710-1.4.2.46.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThermalExpansion{1.7.10R4.0.0B6} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B6-16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	advgenerators{0.9.6.27} [Advanced Generators] (generators-mc1710-0.9.6.27.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Thaumcraft{4.2.1.4} [Thaumcraft] (Thaumcraft-1.7.10-4.2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	harvestcraft{1.7.10b} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Railcraft{9.4.0.0} [Railcraft] (Railcraft_1.7.10-9.4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	gregtech{MC1710} [GregTech] (gregtech_1.7.10-5.06.06.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IC2NuclearControl{2.0.8c} [Nuclear Control 2] (IC2NuclearControl-2.0.8c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	inpure|core{1.7.10R1.0.0B7} [INpureCore] (INpureCore-[1.7.10]1.0.0B7-19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Waila{1.5.5} [Waila] (Waila-1.5.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	JABBA{1.1.4} [JABBA] (Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC5} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC4} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC5} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC4} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC4} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC4} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC5} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC4} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC4} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mystcraft{0.11.0.00} [Mystcraft] (mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC4} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC4} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC4} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC4} [MFR Compat: RP2] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC4} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC5} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC4} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC5} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC5} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ModTweaker{0.6} [ModTweaker] (ModTweaker-1.7.X-0.6-0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons{1.12.2.9} [NEI Addons] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|Botany{1.12.2.9} [NEI Addons: Botany] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|Forestry{1.12.2.9} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|CraftingTables{1.12.2.9} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|ExNihilo{1.12.2.9} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	neiintegration{1.0.1} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ObsidiPlates{3.0.0.18} [ObsidiPlates] (ObsidiPlates-1.7.10-universal-3.0.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-268.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-513.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	RedstoneArsenal{1.7.10R1.1.0RC1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0RC1-19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	xreliquary{1.2} [Reliquary] (Reliquary-1.2.223.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.376.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-161.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Translocator{1.1.1.13} [Translocator] (Translocator-1.7.10-1.1.1.13-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	WailaHarvestability{1.1.0} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	wawla{1.0.9} [What Are We Looking At] (Wawla-1.0.9_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	McMultipart{1.1.0.314} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ForgeMicroblock{1.1.0.314} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	AE2 Version: alpha rv2-alpha-26 for Forge 10.13.2.1230
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, MJ6:OFF, MJ5:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:ON, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3621, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Quetzi** [comment]
Cauldron/mcpc/bukkit is unsupported, re-open if you can replicate in a forge environment.

**Comment by Quetzi** [comment]
Also, you could try to use a version a little newer than one that we released 9 months ago before opening a bug report.
