### ISSUE TITLE
Bluepower and WirelessRedstone - BlockUpdate bug

### ISSUE THREAD

**Issue by JasonMcRay** [Qmunity/BluePower#371]
Not entirely sure if its WR or BP issue, so just in case posting it on both:
https://github.com/Chicken-Bones/WirelessRedstone/issues/17

While using wireless reciver conected with red alloy wire it it seems like the cable is waiting for block update. When I block update the cable near receiver by placing a bock near it, it starts to work.

![](https://cloud.githubusercontent.com/assets/12836717/8095637/866ab06c-0fd8-11e5-8eb7-2f5889ac6a9c.png)
![](https://cloud.githubusercontent.com/assets/12836717/8095638/866b8bcc-0fd8-11e5-8f99-b16eb8b50789.png)
![](https://cloud.githubusercontent.com/assets/12836717/8095636/8669ac76-0fd8-11e5-8459-f7917a0a0712.png)
![](https://cloud.githubusercontent.com/assets/12836717/8095639/866de1c4-0fd8-11e5-8787-14928c4d1d84.png)

**Comment by GirafiStudios** [comment]
Similiar to issue #264 .

**Comment by amadornes** [comment]
It's more like #363. Red Alloy Wire isn't working as it used to, for some reason. If you don't need to specifically use Red Alloy Wire in your builds I'd suggest using Bluestone until it gets fixed

**Comment by Landstryder** [comment]
I'm getting the same issue with bluestone wire

**Comment by MoreThanHidden** [comment]
No longer an issue on newer versions
