### ISSUE TITLE
forge multipart incompatibility crash

### ISSUE THREAD

**Issue by zortag** [Qmunity/BluePower#372]
i posted this issue in qmunity lib github too
http://pastebin.com/THHuQzpD
the world is not corrupted, but looking at a bluepower freestanding red alloy wire with any forge multipart microblock in hand generate this crash. tested with some microblocks but only with that wire.
when reloading the world is at a moment before i'll looking the wire.

**Comment by amadornes** [comment]
Update QLib. A fix for this was released the other day.
