### ISSUE TITLE
Server crash using redstone torch

### ISSUE THREAD

**Issue by Viperwow** [Qmunity/BluePower#376]
Hello, I took a crash on a server using a redstone scheme using 1 lever, 2 wooden pressure plates, 2 bluepower repeaters(1 tick and 8 ticks), between them 1 bluepower pulse former and 1 inverter somewhere in scheme.
I put 1 redstone torch in a scheme between two red allow wire with different states and it cause a crash..

I know it's hard to reproduce a crash for the specific situation like this.. but seems there is may be a bug with infinite ticks of redstone in a looped part of scheme.

So in scheme I tried to connect red alloy wire with another wire through block using restone torch.

Server crashlog: http://pastebin.com/fxSdAH8S

**Comment by abalabahaha** [comment]
Screenshot?

**Comment by Viperwow** [comment]
As I didn't forget scheme it was something like this:
http://i.imgur.com/QQub8lU.png

Redstone torch was somewhere near plates on a block and at the top of a block was red alloy wire

World still being corrupted..

**Comment by abalabahaha** [comment]
Have you tried updating Bluepower? You have .945, latest is .947

**Comment by MoreThanHidden** [comment]
No longer an issue on newer versions.
