### ISSUE TITLE
[Suggestion] config addition for blacklisting non BP alloy furance smelting recipes

### ISSUE THREAD

**Issue by tntblockman** [Qmunity/BluePower#378]
Hi,
I propose a suggestion to add a config option to block all recipes that are not Bluepwer related to smelting via "Alloy Furnace".  The reason for this suggestion is that its kind of annoying if you have 250+ valid smelting recipes, with each having to be blacklisted, can be frustrating and time consuming. Hopefully this config addition would prove very useful to have.

**Comment by tntblockman** [comment]
Another additional config option would be to blacklist all "Alloy furnace" smelting recipes from specific mod(s).

**Comment by MoreThanHidden** [comment]
No longer an issue on newer versions.
