### ISSUE TITLE
Crash when placing pneumatic tube

### ISSUE THREAD

**Issue by Xen1290** [Qmunity/BluePower#379]
Hi, @amadornes @Quetzi ,
 with latest version of Bluepower and qmunity lib I get that crash when I place a tube:
https://gist.github.com/Xen1290/9b05ba5da90de0545d8d

**Comment by abalabahaha** [comment]
Screenshot/drawing of tube configuration?

**Comment by Xen1290** [comment]
Only placed a tube.

**Comment by Quetzi** [comment]
Can you replicate without Optifine? (My guess is no)

**Comment by Quetzi** [comment]
Actually, I'm just going to close this as it is Optifine that is crashing. In the unlikely event you can replicate without it then I'll reopen.

**Comment by Xen1290** [comment]
Yeah, optifine issue... sorry!
