### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by Gideonseymour** [Qmunity/BluePower#380]
Version 0.2.945, Forge 1448
http://pastebin.com/mpwisxS7

**Comment by amadornes** [comment]
That damn bug won't go away no matter how many times we squash it... >_<
I'll have a look at it, give me a moment...

**Comment by amadornes** [comment]
I was looking through the closed issues to see how I fixed this last time... turns out I didn't fix it :/
Though I think the people who were having issues with it stopped having them... I really don't know, I'll have a more in-depth look at it later today

**Comment by wrycu** [comment]
I'm having the same issue on Ubuntu 14.04 x64 using the FTB Horizons Daybreaker pack.  Did you get a chance to look into this?

**Comment by MoreThanHidden** [comment]
No longer an issue on newer versions.
