### ISSUE TITLE
[MyTown2-1.7.10-189-dev] NoClassDefFoundError: com/bluepowermod/part/tube/TubeStack

### ISSUE THREAD

**Issue by brunyman** [Qmunity/BluePower#384]
Using FTB Direwolf20 with KCauldron-1.7.10-1420.117

I got this crash: http://pastebin.com/2qY2jGZ3

**Comment by brunyman** [comment]
oops sorry, i wanted to post this on mytown mod, i was in a hurry and posted it into the wrong tab

**Comment by Quetzi** [comment]
Will reopen if you can replicate in a clean forge environment
