### ISSUE TITLE
freezing screen

### ISSUE THREAD

**Issue by Migul90** [Qmunity/BluePower#385]
for an example: when i try to put a toggle latch on the ground or somewhere else my screen freezes immediately, happens with all like the timer , the sequencer and so on but game is still running, when i log back in to the game the toggle latch is on the wall and the game runs how it should, happens only when i hold it in hands, maybe it´s a bug in the projection before you put it somewhere

**Comment by amadornes** [comment]
Does it crash when you do it? If so, can we get the crash?
Also, what mods are you using?
(Please, use pastebin/gist)

**Comment by Migul90** [comment]
sorry no crash log, game still running just frreezing screen

and here is the mod list

https://gist.github.com/Migul90/4fdf1d78e6be02775dc6

everything on mc 1.7.10

**Comment by Quetzi** [comment]
The problem is likely to be shaders, can you reproduce without them?

**Comment by Migul90** [comment]
turned of the shaders same problem

**Comment by Migul90** [comment]
ok got it, shadersmodcore is the problem, after uninstall it works

**Comment by MoreThanHidden** [comment]
No longer an issue on newer versions.
