### ISSUE TITLE
Items vanishing with crossmod interaction

### ISSUE THREAD

**Issue by JasonMcRay** [Qmunity/BluePower#388]
I was playing with sorting system and I have found few serious issues.

1) When I was inputing items into Iron Chest (from Iron Chest mod) the items were literaly vanishing. I was transfering number of different items and when they hit the chest, they did not appeared inside a chest. Tried to reload the game, to make sure its not just graphical glitch, but they were really gone. Items were "painted" white with Sorting Machine. They landed successfuly in some of the Iron Chests, but not in all.

2) When I try to insert items into Sorting Machine via Buildcraft pipe, the items vanish and are not pushed through the Sorting Machine (they also aren't stuffed in the machine).

3) Similiar as 2. I tried EnderIO Item Conduits to push items into Sorting Machine. EnderIO conduits are transfering 4 items at the time but always only 1 item made it through. I was transfering to sorting machine stack (64) of cobblestone and in the chest after Sorting Machine I got only 21+/-. Again cobblestone was not stuffed in the sorting machine. Also when there was just 1-3 items of the same type in input chest. The enderIO conduit did not grab those items.

I havent tried other mods pipes (like ExU Transfer Pipes or GregTech Brass Item Pipes, but I suspect, they will cause same issue)

If you want me to split this into multiple "issue posts" I can do it.

Using:
Forge: 1420
BluePower: 954
Modpack: InfiTech 2

**Comment by Quetzi** [comment]
The relay is the intended way to get items into the system from other transport options.

**Comment by JasonMcRay** [comment]
Ok, but that still doesnt excuse the vanishing items when not using Relay. If the relay is a NEED for combining transport methods, the other methods should not work at all (read: should not connect to Sorting Machine and others).

Also does that mean that If I want to insert items from BluePower tube network into mod container I need to use relay as well?

**Comment by Quetzi** [comment]
> Ok, but that still doesnt excuse the vanishing items when not using Relay. If the relay is a NEED for combining transport methods, the other methods should not work at all (read: should not connect to Sorting Machine and others).

I didn't say it did

> Also does that mean that If I want to insert items from BluePower tube network into mod container I need to use relay as well?

How could you possibly infer that from what I said? No

Clearly something is wrong and it will be looked into, in the meantime, the intended 'bridge' between transport mods and a tube network is the relay (which is why it is called that)

**Comment by MineMaarten** [comment]
After testing, neither BC pipes or EnderIO pipes insert into a Sorting Machine (like expected).
https://www.dropbox.com/s/tj77bb27z8yhmv1/2015-07-13_17.41.58.png?dl=0

Also, no items seem to disappear for me when using Iron Chests.

For modded --> BP transport conversion, use the Relay.
For BP --> modded let the tubes route into a chest and use the modded mechanic to take it out of the chest.

**Comment by JasonMcRay** [comment]
@MineMaarten you have the enderIO conduit connected to sorting machine in extract mode. Also make sure that the Extract mode connected to chet is set to ignore redstone signal (always working)

**Comment by MineMaarten** [comment]
oh yes, I just took that screenshot to show you my test set-up, I did that after testing and removing the set-up though. I've put it back and took the screenshot (and forgot to properly set the config).

But no, it did not insert whatsoever (I put a chest instead of the sorting machine to make sure the insertion actually worked)

**Comment by JasonMcRay** [comment]
Ok.. little bit more info about the issue.
BC:
Set the sorting machine to: Pull Mode: Automatic; Sort mode: Any Stack with Default => Item traveling through the BC pipe will dissapear

eIO: Set the sorting machine to: Pull Mode: doesnt matter; Sort Mode: Any Item

**Comment by JasonMcRay** [comment]
@MineMaarten were you able to recreate the issue with setting the sorting machine to the modes i posted above? Just asking if it is issue with BP, or there is something borked in my modpack. Thanks

**Comment by MoreThanHidden** [comment]
See work in progress for newer versions.
