### ISSUE TITLE
Teslatite Ore Generation in new chunks in a pre generated world

### ISSUE THREAD

**Issue by SuperSandro2000** [Qmunity/BluePower#389]
I don't seem to find any Blue Power Ores in new chunks because I already explored a large area in my overworld I went to the Deep Dark. Ores in the Deep Dark are doubled but I still found no Teslatite after half an hour searching. I search between 7 and 18.

**Comment by Quetzi** [comment]
If there is actually a problem here then it is going to be in Extra Utilities. If teslatite wasn't generating we would know about it by now.

**Comment by SuperSandro2000** [comment]
I generated a New World and found it after 1 minute. I trie to regen it with COFH Core.
