### ISSUE TITLE
Gates and other tiles are strange in WAILA for a moment

### ISSUE THREAD

**Issue by gabor6505** [Qmunity/BluePower#390]
Sometimes I can catch the thing shown below in the picture in WAILA, for a moment. It seems like WAILA displays the QmunityLib multipart first, then shows the actual tile (gate, wire, lamp, etc.)

![2015-07-18_19 45 02](https://cloud.githubusercontent.com/assets/12859334/8762955/4ff2d1b8-2d88-11e5-86d9-dd5fc8b72deb.png)

It's just a little visual issue.

**Comment by amadornes** [comment]
Yeah, we know about this. I've been working on the multiparts a lot lately and I think I've managed to fix this already, but I'll have to check. However, the fix isn't out yet and I don't really know when it will be since it involves a complete rewrite of QLib and a big chunk of BP

**Comment by gabor6505** [comment]
Okay, thanks! :smile:

**Comment by MoreThanHidden** [comment]
See work in progress for newer versions.
