### ISSUE TITLE
Light Fixture/Caged Lamp bug

### ISSUE THREAD

**Issue by SniperHauss89** [Qmunity/BluePower#392]
Hello, I was working on putting together a private modpack for a group of friends when I noticed a strange "bug" with the light fixtures and caged lamps. it is primarily with the non inverted ones but the inverted ones play a role in the overall bug. Firstly at night when a redstone signal is sent to the fixture/lamp's they don't show a change in light level and look dim but they do put off light level if it's mid day and a little bit when it's morning which is strange, If this behavior is supposed to be here it is reversed it seems. Secondly, if you put an inverted fixture/lamp next to a non inverted fixture/lamp it lights the non inverted on up how it should be. It's a bit hard to show in screenshots but I got two that should show some of the problem.
![2015-07-21_01 58 24](https://cloud.githubusercontent.com/assets/9005067/8794086/70c40986-2f4d-11e5-883c-da77aedbec61.png)
![2015-07-21_01 58 57](https://cloud.githubusercontent.com/assets/9005067/8794085/70c3e302-2f4d-11e5-9173-dc8641c77831.png)

BluePower version: 0.2.954
QmunityLib version: 0.1.114
Forge version: 1490
Forge Multipart version: 1.1.1.345

**Comment by TheJulianJES** [comment]
QmunityLib is currently in a rewrite. So it can take a while until this bug gets fixed.

**Comment by MoreThanHidden** [comment]
No longer an issue in newer versions.
