### ISSUE TITLE
Toggle Latch crash

### ISSUE THREAD

**Issue by JasonMcRay** [Qmunity/BluePower#396]
When I applied a steady redstone signal with lever to an input of Toggle Latch, minecraft crashed: https://gist.githubusercontent.com/JasonMcRay/c3a4049b482ed273f426/raw/922e60ea616c21991cf3d54dc71a138eb37e06dd/Bluepower%2520Crashlog

**Comment by JasonMcRay** [comment]
Did bit more testing. The crash occurs just with this simple setup: http://i.imgur.com/4WaWMPb.jpg
Able to recreate that 100% time. It corrupts the world until the latch is removed from the game (either with MCEdit, or via Forge function to remove erroring entities)

**Comment by amadornes** [comment]
I can confirm that toggle latches are really derpy. I think I've already fixed this in one of my dev branches which will be merged in the next couple of weeks (there's some very indev stuff in there that I don't want players fiddling with, else I'd push it right now). I think this should be relatively easy to fix if that's not the case :)

**Comment by JasonMcRay** [comment]
Honestly if this was just a crash, I would not care that much if the version which will fix this will come today, tomorrow or week later (speaking from Modpack Developer perspective), but since it is able to completely destroy the world (server will just not start and always crash when the chunk containing bugged out latch is loaded), where player needs to be somewhat aware of how to remove erroring blocks via McEdit, I would prefer this merge to be either sped up, or just fixed this single issue.

**Comment by amadornes** [comment]
I'll see what I can do... :)
