### ISSUE TITLE
BluePower/Qmunity Lib/EnderIO stall reports

### ISSUE THREAD

**Issue by AiwendilCiunio** [Qmunity/BluePower#397]
Hello, I'm a player on Infitech 2 modpack server:
http://forum.feed-the-beast.com/threads/1-7-10-infitech-2-modpack-v3-1-5-gregtech-balanced-hard-mode-modpack-updated-7-26-2015.50185/
http://infitech.enjin.com/

We've been dealing with severe lag problems since quite some time, and are trying to fix the issue.
I looked at stall reports, and each one of them under SERVER THREAD has Qmunity Lib and Bluepower listed, along with (usually) Enderio.

Because I'm not a programmer my question is - is this possible that one of the mod, or maybe interaction between them (likely something to do with redstone) is the cause of our lag? Please look at these stall reports and tell me what you get out of them:
http://pastebin.com/vp52CGCK (that's how it look most of the time)
http://pastebin.com/1YV9Rs4m (this is a bit unusual as there's no enderio on the list)

**Comment by AiwendilCiunio** [comment]
EnderCore -> 0.0.1.13
Enderio -> 2.2.8.381
BluePower -> 0.2.954
QmunityLib -> 0.1.114

**Comment by TheJulianJES** [comment]
QmunityLib is currently being rewritten, so it can take a while until this bug is fixed. I also had a bit of a lag problem with QmunityLib parts.
Also about EnderIO:
Their conduits are ticking every tick and are not good for performance. :)

**Comment by MoreThanHidden** [comment]
No longer an issue in newer versions.
