### ISSUE TITLE
Timer Min Time

### ISSUE THREAD

**Issue by Nentify** [Qmunity/BluePower#398]
Can we have a config to set a minimum time of the timer? The same as RP2 and RedLogic have.

**Comment by Quetzi** [comment]
From memory the only timer configs in RP2 were about sounds on/off. Minimum timer time can be configured int he gates GUI.

**Comment by Nentify** [comment]
Maybe it was just in the Bukkit version, but there was a config to set the minimum timer length to a number of ticks, such as 20. RedLogic also has this. Would it not be possible to add something like this?

**Comment by Quetzi** [comment]
What point would there be? You can easily make a 1 tick timer in vanilla if that is what you want.

**Comment by Nentify** [comment]
To help prevent lag - having many 1 tick timers running at once with various operations isn't good (on a server). We sometimes find vanilla clocks too which we have to deal with as well as they are no better.

**Comment by Quetzi** [comment]
I'm normally not opposed to having more configurability. In this case it would just add additional clutter to the configs without actually achieving anything. There is no sense limiting the mod to prevent it doing something already available in vanilla, for which there are already tools available to help track down. There is no benefit in doing this, you just shift the problem somewhere else.

**Comment by Nentify** [comment]
The problem isn't being shifted anywhere - most people will use BP timers as their go to instead of vanilla redstone timers and will understand the lower limit. It's hardly clutter at all, and all RP mods have had this option for this reason. It would be of great benefit to me and perhaps other players or server owners as well.
