### ISSUE TITLE
Inverted RGB Lamp Black

### ISSUE THREAD

**Issue by djoveryde** [Qmunity/BluePower#400]
I am having trouble trying to get the inverted RGB Lamp to light. When its placed it just turns black.
I have tried lever switching, redstone torch.
Currently out of ideas. Any light on what im doing wrong here?

Edit: RGB Lamps also do the same

**Comment by amadornes** [comment]
RGB Lamps use bundled wire and you control the brightness of the red, green and blue components with the input from the corresponding bundled signals :)
Also, RGB lamps are quite derpy, I don't know how I should make them work. They'll probably get removed :P
