### ISSUE TITLE
Crash on Ticking block entity/ Bluepower.lamp

### ISSUE THREAD

**Issue by UberAffe** [Qmunity/BluePower#401]
I'm not sure if this is an issue for you guys or for open blocks so I'm letting both know.

This is from a horizons daybreak server, it was running just fine the last time anyone had been on the server and a backup was made immediately after the last player logged off. The server was off when I checked back on it and this was the crash report: 
http://pastebin.com/FLcWEqDN
I restored to the back up and was able to connect but the server immediately crashed and gave this report:
http://pastebin.com/sTHMS6ji

**Comment by Rubbertjuh** [comment]
Having the same issue, did you manage to fix it ?

**Comment by UberAffe** [comment]
I had to get nbtexplorer and remove the block from the region file.

**Comment by Robotia** [comment]
it's an open blocks issue from what I can tell

**Comment by MoreThanHidden** [comment]
No longer an issue in newer versions.
