### ISSUE TITLE
Crash: Canvas Bag??? 

### ISSUE THREAD

**Issue by ScarecrowKrone** [Qmunity/BluePower#402]
Singleplayer

Mac OS X 10.10.4

Version of Java: 1.8.0_51 64-Bit

Pack version: 4.0.4

Description of problem: I think I tried to throw out a blue power canvas bag using the NEI right menu while I was in said bag's inventory? It was lagging a bit so I'm not sure if I even managed to do anything with that bag. It could just as easily have been something else. 

Steps to reproduce problem: ???

Crash/error report: 

http://paste.ubuntu.com/11946479/ for crash report, 
http://paste.ubuntu.com/11946497/ for terminal stuff.

**Comment by CubeWrench202** [comment]
lies

**Comment by TheFjonG** [comment]
You shouldnt be able to move around with the bag while in its inventory.. I'm using the same version of NEI and CCC.. Cant reproduce at all with the version of this git

**Comment by Quetzi** [comment]
What likely happened is you've tried to pick an item while something was already on your cursor (the bag) The issue looks to be on NEI's side in any case. I'd use an empty area of screen to try and drop things until CB can fix it.
