### ISSUE TITLE
Transposer not working after crash

### ISSUE THREAD

**Issue by Molinist** [Qmunity/BluePower#403]
After I had this crash the transposer would no longer pull items from a chest when given a redstone signal (i tried buttons, timer, lever etc). There is a way to fix it, but the consequences of this are unpleasant. I have to remove bluepower mod from the pack, load the world, quit game, add bluepower back to the modpack again and load the world once more. But all blocks get sucked out of the world so thats not a viable solution  

Crash:

http://paste.ubuntu.com/12121730/

**Comment by TheJulianJES** [comment]
Update Computronics and OpenComputers.

**Comment by MoreThanHidden** [comment]
No longer an issue in newer versions
