### ISSUE TITLE
Microblock Cover with lever connecting

### ISSUE THREAD

**Issue by McBrown** [Qmunity/BluePower#405]
I can't seem to let a lever connect through a cover, only on a block.

![2015-09-07_16 47 12](https://cloud.githubusercontent.com/assets/539121/9718922/21cdf518-5580-11e5-9f39-ae7826c87c5c.png)

I've looked for multiple solutions, but I can't seem to "solder" with an blue-wire or aim the "Freestanding Bluestone Wire" with a screwdriver.

I hope I'm just doing something wrong, I've used this mechanic a lot with RP.

**Comment by amadornes** [comment]
I just double-checked and this is how it worked in RedPower. I'm not sure if the "Wire Covers" we have planned could allow this functionality, but for now you'll have to place a solid block with normal wire and then connect that to freestanding wire, just like with the bottom lever in your image.

![](http://ss.amadornes.com/ama-1441638370-33.png)

**Comment by McBrown** [comment]
Guess it'll have to do for now. Great to hear you guys are working on it :)
