### ISSUE TITLE
startup crash.

### ISSUE THREAD

**Issue by stclaus4** [Qmunity/BluePower#406]
http://pastebin.com/WThvmUWw
I got this crash on startup and I can make no sense of it except for the Bluepower words so I am hoping you can help me.

**Comment by Cypher121** [comment]
Recipe you pull from registry has null as output. Actually, I was the one who made that recipe (oops), but you still should check for that.

**Comment by stclaus4** [comment]
How do I check/ change it out of game?                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Cypher121Sent: Monday, September 14, 2015 12:58 AMTo: Qmunity/BluePowerReply To: Qmunity/BluePowerCc: stclaus4Subject: Re: [BluePower] startup crash. (#406)Recipe you pull from registry has null as output. Actually, I was the one who made that recipe (oops), but you still should check for that.

—Reply to this email directly or view it on GitHub.

**Comment by Cypher121** [comment]
That wasn't meant for you, that was for whoever is going to fix that.

**Comment by stclaus4** [comment]
OK thanks                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Cypher121Sent: Monday, September 14, 2015 7:52 AMTo: Qmunity/BluePowerReply To: Qmunity/BluePowerCc: stclaus4Subject: Re: [BluePower] startup crash. (#406)That wasn't meant for you, that was for whoever is going to fix that.

—Reply to this email directly or view it on GitHub.

**Comment by MoreThanHidden** [comment]
Invalid recipe getting made from another mod, no longer relevant.
