### ISSUE TITLE
Please refer to net.minecraftforge.oredict.RecipeSorter

### ISSUE THREAD

**Issue by bookerthegeek** [Qmunity/BluePower#409]
````
[Client thread/INFO] [FML]:   Unknown recipe class! com.bluepowermod.recipe.RecipeNullCell Modder please refer to net.minecraftforge.oredict.RecipeSorter
````
Repost from: https://github.com/MyM-ModpackTeam/B2B/issues/6

**Comment by bookerthegeek** [comment]
My apologize if this was not the correct place to post this. Am I missing information that you needed or is this a non-issue?

**Comment by Quetzi** [comment]
Please refer to the big reporting guidelines

**Comment by bookerthegeek** [comment]
Will do, and thank you.
