### ISSUE TITLE
minecraft crash when using to many bluepower blocks

### ISSUE THREAD

**Issue by TheJelmega** [Qmunity/BluePower#411]
I'm trying to build a minecraft computer with bluepower and started on the screen, but it seems like I'm using to much wires, now in total I have a 48 x 84 grind of alternating wires (blue and red alloy), but when I start the world I get an error

log:
http://pastebin.com/T6tQKKNb

**Comment by MoreThanHidden** [comment]
See work in progress but no longer an issue on newer versions.
