### ISSUE TITLE
isUseableByPlayer not checking for absence of TileEntity/DUPE Bug

### ISSUE THREAD

**Issue by MaPePeR** [Qmunity/BluePower#413]
Found in [Workbench](https://github.com/Qmunity/BluePower/blob/master/src/main/java/com/bluepowermod/tile/tier1/TileProjectTable.java#L212-L216). Check all your containers. See how Vanilla Tile Entitys implement the method.

Will cause the GUI to stay open when the block is broken, which allows to craft an item without loosing the ingredients.

**Comment by MoreThanHidden** [comment]
No longer an issue on modern versions.
