### ISSUE TITLE
Fake Player name has a space

### ISSUE THREAD

**Issue by juniorjunior** [Qmunity/BluePower#416]
The fake player for the deployer has a space in it which is causing issues with at least GriefPrevention(Plus) and I would expect others as well. "[BP Deployer]" should probably be "[BPDeployer]".

**Comment by Quetzi** [comment]
No stacktrace?

**Comment by juniorjunior** [comment]
There's no stack trace to be had. With a space in the fake player name I haven't been able to get any of the protection plugins to take the name. Admittedly, this could also be fixed in the protection plugins, but since I've never seen a fake player name with a space in it anywhere else this seemed like a good place to start.

**Comment by Quetzi** [comment]
Cauldron isn't a platform we support, sorry

**Comment by juniorjunior** [comment]
<sigh> How about if I say it's Forge Essentials? Or how about any comment on why you use a space in the fake player name when not one single other mod I can find does this (for very good reasons which have nothing to do with Cauldron/KCauldron/etc.)?

**Comment by Quetzi** [comment]
How about you provide a log with your issue, as per our issue reporting guidelines.

**Comment by juniorjunior** [comment]
I can't fabricate something relevant out of whole cloth. As I mentioned, there is no log. Not all "issues" generate logs. I've explained in quite sufficient detail the issue. However, I'm not totally dense. If there is no desire to address this I can maintain my own fork/builds.

Thank you for your time.
