### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by bookerthegeek** [Qmunity/BluePower#419]
Cross posted at [Jabba](https://bitbucket.org/ProfMobius/jabba/issues/156/duplication)

![Dupe Image](http://i.imgur.com/tNXZlGW.jpg)

When triggered will create infinite redstone (or any other block/item)

Modpack: Tekkit Legends 
Jabba-1.2.1a_1.7.10

**Comment by MoreThanHidden** [comment]
No longer an issue in latest versions
