### ISSUE TITLE
Amethyst Shovel can not right+click access an AE2 crafting terminal.

### ISSUE THREAD

**Issue by Hypocrisy** [Qmunity/BluePower#420]
I can right click it with a Ruby Axe. Not sure if it is specific to Amethyst or Shovel.

**Comment by GirafiStudios** [comment]
Well then do more testing before reporting, if you're not sure.

**Comment by Hypocrisy** [comment]
I'm sure that it doesn't work with an Amethyst Shovel. That should provide you with enough direction. I don't really care either way as it's not enough of an annoyance to hinder game play. 

I'm just reporting it to you in the event that *you* want it fixed, if so do your own research.

**Comment by GirafiStudios** [comment]
I don't in any way have anything to do with Blue Power. I'm sorry that my answer came out as rude as it did.
All I wanted to suggest with my reply, was that it would be nice of you did further testing, to figure out if it was related to amethyst or to shovels.

**Comment by Hypocrisy** [comment]
This is an issue with Applied Energistics. No shovel will work with a crafting terminal.
