### ISSUE TITLE
The gates are all fire

### ISSUE THREAD

**Issue by Barhandar** [Qmunity/BluePower#421]
Oh, and pretty much all BP-related renderers [EXPLODE](http://i.imgur.com/Ted12vQ.png) when viewed in inventory (or achievement screen), while trying to open Alloy Furnace nets me [the following error](http://pastebin.com/R4gSs5d7).

Given it happens with no other mod, I suspect you're doing something bad with rendering. Tommorow-ish I'm going to check by elimination what specifically pops that particular pithos open.

P.S. [Similar UI-explosions](http://i.imgur.com/BV66UlN.png) happen when one of the gates is in inventory (note - it's not placed, it's merely selected on hotbar), while looking at gate in-world has tendency to make parts of the world (whole chunks and non-cube blocks like chests) disappear.

**Comment by MoreThanHidden** [comment]
No longer an issue in latest versions
