### ISSUE TITLE
Blue Sapphire glass is not glass

### ISSUE THREAD

**Issue by killerscorpion** [Qmunity/BluePower#424]
MC 1.7
Forge 10.13.4.1517
BluePower 0.2.962

Reinforced sapphire glass is cool and all but it would be even cooler if it was glass and I could see through it. 
![2015-11-16_15 50 15](https://cloud.githubusercontent.com/assets/10732882/11198560/7b124ac6-8c7a-11e5-8e94-56a62071095f.png)

**Comment by GirafiStudios** [comment]
That issue is caused by Optifine.

**Comment by killerscorpion** [comment]
ah darn it, thats so lame. Dumb optifine. Thanks for the quick feedback.
