### ISSUE TITLE
Filters do not work

### ISSUE THREAD

**Issue by aathum** [Qmunity/BluePower#425]
With Drawn...Sorry guys.

**Comment by WarlowAus** [comment]
Can I ask why you've withdrawn? I'm experiencing the same issue

**Comment by aathum** [comment]
I found that the filter needs to have a receiving chest on the output side either at the end of the pneumatic tubes or adjacent to the block. As soon as I added this, the filter worked. If you have an incomplete tube system it wont pull. It will eject to the ground. Insure the direction of the filter is correct too.

**Comment by MoreThanHidden** [comment]
Please see WIP items for modern versions #466
