### ISSUE TITLE
Filters don't work #2?

### ISSUE THREAD

**Issue by WarlowAus** [Qmunity/BluePower#427]
Hey Guys,
I'm using the tekkit legends modpack, no added mods in addition to the base modpack.

I've been building a MFM, link to the guide im using here
http://tekkitclassic.wikia.com/wiki/Tutorial/Mass-Fab_Macerator

Link to a pic of my build here:
http://imgur.com/DUIHPNg

I can't seem to get my filters to respond to the redstone pulses. Whether they're empty, standing by themselves or attached to pipes with and without boxes, i've tried everything. 

Also strange is that when I reset my (gameservers) server they all rotate at random and I have to re-align them with the pipes etc, which makes me think they're rotating client side but not server side or something. I have no idea what's going on, can you help?

Ps. i noticed another guy posting that filters didnt work, but it was withdrawn without elaboration. I wished he'd expanded on how he got them working!

**Comment by WarlowAus** [comment]
Oh and you can see over on the right where I've just wrapped a Filter in cable trying to figure out if there was a particular face I needed to connect the cable to, or whether it was the way I'd connected it to the rest of the machine which was causing it.

**Comment by aathum** [comment]
I see the center filter is "Pulling" from the pneumatic tubes. I could not get this to work unless the filter was adjacent to the source block and not to a tube.

**Comment by WarlowAus** [comment]
The problem is none of the filters are working. It's not that the build doesn't function, it's that the filters aren't activating at all, there's no interface with the timer current

**Comment by MoreThanHidden** [comment]
Please see WIP items for modern versions #466
