### ISSUE TITLE
Geothermal generator loads items in the top even when pneumatic tubes are on bottom

### ISSUE THREAD

**Issue by aathum** [Qmunity/BluePower#429]
Geothermal generators will not load from pneumatic tubes from the bottom, so you cannot load lava cells to the bottom of the geothermal generator automatically. When pneumatic tubes are connected to a filter pulling lava cells from a chest, they only load to the top slot of the geothermal generator. If top slot is occupied by say an RE-Battery, the bottom slots still will not load

**Comment by MoreThanHidden** [comment]
Please see WIP items for modern versions #466
