### ISSUE TITLE
Deployers do not pull lava from tanks

### ISSUE THREAD

**Issue by aathum** [Qmunity/BluePower#430]
If you place a deployer next to a tank and send a redstone timer pulse, it will not fill buckets in its inventory with lava.

**Comment by TrupJP2** [comment]
Indeed deployers are also unable to deposit buckets into tanks. I just ended up using liquid transposers from Thermal Expansion as my main use of deployers was to pour buckets into tanks.

**Comment by MoreThanHidden** [comment]
I believe this has been fixed in modern versions.
