### ISSUE TITLE
ServerCrash: bluepowermod TubeLogic IllegalArgumentException

### ISSUE THREAD

**Issue by JasonMcRay** [Qmunity/BluePower#432]
The players that discovered it said: 

> "Placed a opaque tube at a side of a Manager while the whole thing was connected to a Retriever. Or maybe I broke some tube connected to that thing."

Unfortunately player already took it apart, i will try to get the screenshot of the setup from that player.

http://paste.ee/p/vJuBV
BP: 0.2.962

**Comment by ghoulsblade** [comment]
screenshots now in original thread : https://github.com/JasonMcRay/InfiTech-1.7/issues/436

**Comment by MoreThanHidden** [comment]
Please see WIP items for modern versions #466
