### ISSUE TITLE
Comparitor Bug[replicatable]

### ISSUE THREAD

**Issue by NanoCE** [Qmunity/BluePower#434]
http://puu.sh/lRC8S.png

This seems like a bug. examples in order
1. Your comparitor will read froma  dispensor even if there is a block between it.
2. Your comparitor will ignor the dispensor and check any inv(chest) which is behind it.
3. The comparitor is just working normally

This happens to both droppers and dispensors. This fuctionality is unlike the vannila comparitor.

For all I know this may be a intended feature but I doubt so because it isnt acting like the vannila version.

**Comment by MoreThanHidden** [comment]
Please see WIP items for modern versions #466
