### ISSUE TITLE
Pneumatic Tubes Excessive NBT Packets

### ISSUE THREAD

**Issue by sameer** [Qmunity/BluePower#435]
When a pneumatic tube system is overloaded with items, it spends too much time sending update packets to the client side (through uk.co.qmunity.lib.part.PartBase.sendUpdatePacket() ), overloading and lagging the server side.

**Comment by Robotia** [comment]
If anyone else encounters this issue... easiest temporary fix is to comment it out for now.

**Comment by Xen1290** [comment]
I think @amadornes is rewriting BluePower completly, so I think Will be fixed.

**Comment by Rubbertjuh** [comment]
I seem to be having the same issue.
The lagging tubes are always near a filter as well.

**Comment by Robotia** [comment]
@amadornes are you rewriting this?

**Comment by MoreThanHidden** [comment]
Please see WIP items for modern versions #466
