### ISSUE TITLE
Timer doesn't always send a signal?

### ISSUE THREAD

**Issue by Y2KNW** [Qmunity/BluePower#437]
I'm playing the TechNodeFirmaCraft pack, and while I know it's a rather memory intensive pack, I've found that the Timer doesn't always send a signal.  The little torch lights, the sound goes off, but no redstone signal is sent.

I'm getting a bit more luck sending the signal by putting a repeater after the timer, but it's still kinda touch and go.

**Comment by MoreThanHidden** [comment]
Please see WIP items for modern versions #466
