### ISSUE TITLE
deployer deploys deployers in inconsistent orientation

### ISSUE THREAD

**Issue by voxelbec** [Qmunity/BluePower#445]
The BluePower Deployer places most directional blocks (ie: hopper, dropper, piston) facing sideways however when placing another deployer block, it places them facing upwards.

This doesn't seem self-consistent or consistent in relation to other deployers such as Tubestuff deployers.
It's is also massively inconvenient should you want to use a deployer to 'print' another deployer and without involving orientation gymnastics.

Can this be changed please?

**Comment by MoreThanHidden** [comment]
Places objects in their default state in modern versions so is facing north, could possibly find a way of orienting them the same way if this is for some reason required.
