### ISSUE TITLE
A bug with "about to place a bluepower contraption"

### ISSUE THREAD

**Issue by PootisWizard** [Qmunity/BluePower#446]
Im not sure if this is me or not but im using this mod along with some other mods for 1.7.10

and when i hover a bluepower machine on the ground the screen goes all white but if i were to look at the bluepower machine with the bluepower machine, its normal...

is there a fix or not?

(Btw: liteloader was also used)

![screenshot 2016-04-06 13 52 21](https://cloud.githubusercontent.com/assets/18314248/14329093/7271cf96-fbff-11e5-86dd-4039600275c7.png)

(Added a Picture of The Currently used mods as of 4/6/16, this list may change later if I plan to add more mods for a Singleplayer survival)

**Comment by seeker2921** [comment]
I am having the same issue, With everything minus wires.

My mod list is very differnt than above list. The following mods are the same however, that may help narrow down the issue. (if it is conflicting mods related..)

Better HUD
BluePower
CodeChickenCore
CodeChickenLib
CoFHCore
IronChest
MineFactoryReloaded
NEI
Optifine(D6)
QuminityLib
Xaeros_MiniMap.

I have roughly 15 to 20 additional mods, but those mods are the same as PootisWizard.

**Comment by Wabbajack67** [comment]
I had the same problem, and it took me forever to solve. I issue is with optifine and the "ghost" machines that appear when you look at the ground.

**Comment by MoreThanHidden** [comment]
No longer an issue in 1.12 and was previously an Optifine compatibility issue.
