### ISSUE TITLE
[Bug] Infinite Dupe with Wool Card and Drawplate

### ISSUE THREAD

**Issue by Kraise** [Qmunity/BluePower#447]
Crafting together (tested with vanilla crafting bench and player inventory crafting) 2 of the diamond drawplate or wool card allows you to take as many as you want out without consuming them.

I noticed this on CrundeeCraft 1.0.22 on a Thermos55 server, but I have been able to reproduce it in singleplayer with just BluePower-1.7.10-0.2.962 and QmunityLib-1.7.10-0.1.114.

What is expected to happen: Both items in crafing grid are consumed to produce a less damaged copy.
What really happened: Items were not consumed, instead they just lost durability.

No crash log or anything as this didn't cause crashing/stalling at all, but the duping is an issue.

This is probably because they are instances of ItemLimitedCrafting, since they are the only ones and they are the only items with this issue. I would suspect it is due to [this method always returning false](https://github.com/Qmunity/BluePower/blob/master/src/main/java/com/bluepowermod/item/ItemLimitedCrafting.java#L42), even when they are being used in repair.

**Comment by MoreThanHidden** [comment]
Not working on the 1.7.10 versions and this isn't an issue on the current versions.
