### ISSUE TITLE
Redstone torch, NOT gate, Repeater (from the mod) causing server crash and world corruption.

### ISSUE THREAD

**Issue by Pytato** [Qmunity/BluePower#450]
Placing a NOT gate and a Repeater (the one from this mod) one block apart, where one of the NOT gate outputs is facing the repeater, then placing a redstone torch between them will corrupt a world, crashing the server. My server is running [Buttery Biscuit Base](http://www.technicpack.net/modpack/buttery-biscuit-bass.849374/) on Cauldron 1.7.10.

I expected to see no interaction between the NOT gate output and the redstone torch, and for the redstone torch to activate the repeater.

Crashlog is [here](http://pastebin.com/ebchfRHd).

If you need further info from me about the server or modpack, I will get back to you as soon as possible.

**Comment by Kamairo** [comment]
Since this comes close enough to my issue, I am also reporting in on this:
For me it is enough to even select an Inverter from the creative inventory in single player and the game seems to go into an infinite loop, world cannot be loaded anymore after that.

**Comment by MoreThanHidden** [comment]
No longer an issue in Modern Versions
