### ISSUE TITLE
Blue Power crash on server start

### ISSUE THREAD

**Issue by Y0ungSandwich** [Qmunity/BluePower#453]
Using:
- QmunityLib-1.7.10-0.1.114-universal.jar
- BluePower-1.7.10-0.2.962-universal.jar

Mod List
- https://www.atlauncher.com/pack/MechMagic

Crash: http://pastebin.com/kvcbp7L3

Server starts fine without Blue Power. Issue is consistent with several past versions of BP. 
Does not effect SSP and only affects some linux environments. Runs fine on my centos 7 box
but Akliz hosting can't get it to start.

**Comment by MoreThanHidden** [comment]
Not actively supporting the 1.7.10 version anyone can fork the last version and support it if they want to.
