### ISSUE TITLE
White screen when placing gates

### ISSUE THREAD

**Issue by pitrex29** [Qmunity/BluePower#455]
When I'm trying to place BluePower Gates on my modpack:
[video](https://github.com/Qmunity/BluePower/files/401355/huh.zip)

**Comment by Breadabix** [comment]
Having same issue

**Comment by Yuelia35** [comment]
@pitrex29 @Breadabix 
(I am not good at English, so I will use machine translation, which may be strange English)
Are you using OptiFine's Fast Render?
When it is turned off, it may not be a white screen.

**Comment by MoreThanHidden** [comment]
Not actively supporting the 1.7.10 version anyone can fork the last version and support it if they want to.
