### ISSUE TITLE
Inverters visually but not functionally disabled

### ISSUE THREAD

**Issue by ChocoPuppy** [Qmunity/BluePower#456]
What I mean is when I power an inverter it visually turns dark red (so do the cables it's powering), but any blocks connected to it in a seven block radius around it are powered anyway. I have tested this with both vanilla and modded blocks with the same results, I am running this on a modified version of FTB horizons daybreaker, which includes fastcraft. this problem begun when I updated to the latest version on curse: 0.2.962.
edit: It appears to occur when red allow wires connecting the power source to the inverter has become 17 blocks long
![2016-10-02_23 45 06](https://cloud.githubusercontent.com/assets/7753274/19020644/c6da37c0-88fa-11e6-8041-7f5e73d5c0e6.png)

**Comment by ChocoPuppy** [comment]
Updated with pictures (ignore the redstone dust on the lamp, I was just breaking stuff in survival before going into creative to test this)

**Comment by ChocoPuppy** [comment]
Further testing has revealed a few things, first of all that this bug applies to every kind of wire, second of all a simple lever doesn't seem to be causing the problems, I shall experiment further to find out which part of my system is causing this and update the post with the results

**Comment by ChocoPuppy** [comment]
The bug appears to occur when the cable connecting the power is 17 blocks long
![2016-10-02_23 45 06](https://cloud.githubusercontent.com/assets/7753274/19020633/52f2eabe-88fa-11e6-8756-55d838f304fb.png)

**Comment by MoreThanHidden** [comment]
See WIP Items here #466
