### ISSUE TITLE
ComputerCraft getBundledInput only reports last activated color

### ISSUE THREAD

**Issue by tprk77** [Qmunity/BluePower#457]
This is on Tekkit Legends, so this is Blue Power `1.7.10-0.2.962`. (Hopefully it's fairly recent?)

I have a setup like pictured below. A bundled cable is connected to a computer, and some colors are connected to switches. What I'm observing is that when I flip a switch, `getBundledInput` returns that color, but when I flip the next switch, `getBundledInput` forgets the last color and only reports the new color, instead of combining them.

For example:

Action | Switches | `getBundledInput`
-------|----------|-------------------
Initial setup | Both off | 0
Toggle white switch | White on, orange off | 1
Toggle orange switch | Both on | 2 (Expected 3)
Toggle orange switch | White on, orange off | 0 (Expected 1)
Toggle white switch | Both off | 0

Let me know if I can provide any other useful information.

---

![setup](https://cloud.githubusercontent.com/assets/896591/21739496/52b4d5f6-d46a-11e6-9c4f-60e1ecffae15.png)

**Comment by MoreThanHidden** [comment]
See WIP Items here #466
