### ISSUE TITLE
(Reinforced) Sapphire glass has a solid color as glass texture

### ISSUE THREAD

**Issue by Horthal** [Qmunity/BluePower#460]
I have a bit of an annoying problem, when placing down either Sapphire glass or Reinforced sapphire glass, the texture which should be a bit see-through is solid (See attached screenshot). I've looked into the texture files and the textures are made exactly as they should. The texture when it is in hand is normal and the solid color only appears when it's put down. I do not use optifine so that's not the issue, I've tested this with Sphax + Tekkit Legends Patch and the default minecraft texture pack in which the normal Sapphire glass works normal but the Reinforced Sapphire Glass had the same issue still. Below is all the important info;

UPDATE; Apparantly, when the sapphire glass is connected in the Vanilla Minecraft Resource pack, the solid blue color reappears

Minecraft Version; 1.7.10
Forge Version; 10.13.4.1614
BluePower mod Version; BluePower-1.7.10-0.2.962-universal (Latest)
QmunityLib installed?; Yes (QmunityLib-1.7.10-0.1.114-universal)
![2017-07-14_18 42 31](https://user-images.githubusercontent.com/30182223/28221604-3e9116c2-68c4-11e7-8fc6-817d367b3752.png)
![2017-07-14_18 42 52](https://user-images.githubusercontent.com/30182223/28221621-4ce03cd0-68c4-11e7-9cf3-a69c8a342ed9.png)

**Comment by MoreThanHidden** [comment]
No longer relevant in current version.
