### ISSUE TITLE
WHERE IS MY RUBBER TREE???????

### ISSUE THREAD

**Issue by Kelvely** [Qmunity/BluePower#461]
GIVE MY RUBBER TREE BACK!!!!!!!
I LOVED IT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVED IT!

**Comment by TheCodedOne** [comment]
i agree with this

**Comment by MoreThanHidden** [comment]
See WIP Items here #466
