### ISSUE TITLE
Project Table Issues

### ISSUE THREAD

**Issue by aznninja5996** [Qmunity/BluePower#475]
So I have run into this issue that spawns multiple issues on my server. The first is that whenever anything is crafted using the Project Table, the console is flooded with the same RuntimeException. However, the intended item to be crafted is still crafted, so that's good. Then there is the issue of when a player is in the Project Table GUI, the mouse-hover to see the item name and data is not there (both table inventory and player inventory). Once a player exits the table, all the hovering still works though. This next issue may not be a BluePower issue (and really isn't a big deal) but when using the project table to craft metal plates using a Forge Hammer (IC2), it duplicates the hammer (assuming because of hammer durability reduction).

### What were you doing when the issue happened? ###
Crafting using the Project Table
### What did you expect to happen? ###
The table to function as a standard crafting table with memory and inventory.
### What happened instead ###
Mentioned Above
### Crashlog on pastebin/gist ###
https://pastebin.com/45v4cRQV
### Forge and Minecraft version ###
Forge 14.23.5.2824 on MC 1.12.2
### Bluepower version and build number ###
BluePower-1.12.2-0.3.32

Thanks in advance for all the hard work your team has put into this mod, I really appreciate it!

**Comment by MoreThanHidden** [comment]
Thanks for the report, will check this out, am sure I tested this before so I probably broke it at some point.
