### ISSUE TITLE
[IDEA+Question] Blue power engine

### ISSUE THREAD

**Issue by MineTech123** [Qmunity/BluePower#476]
Is the Blue Power Engine going convert 1 blue power unit to 10 FE

also here’s some conversion rates if it is going to act as a power converter but not for FE https://gist.github.com/DeflatedPickle/403e1eb0bb0bed7f2509142e63630726/

**Comment by MoreThanHidden** [comment]
I believe so, not sure on the energy naming at this stage, in Red Power 1 kW was 1 MJ/t and they could do a maximum of 32MJ/t so will probably keep this similar. 1 Unit to 10FE from the engine, I may add less and more efficient ways of conversion just to screw with the system 😝.

**Comment by MineTech123** [comment]
[Idea 2]
Do upgrades 
you need the max amount of efficiency upgrades or whatever you want to name it to get the full
 10 FE from 1 Unit
