### ISSUE TITLE
Engine Upgrades Suggestion / Discussion

### ISSUE THREAD

**Issue by MineTech123** [Qmunity/BluePower#477]
{This is the reply to the previous comment [Idea+Question] that I accidentally closed}

Do upgrades
Let’s say you need the max amount of efficiency upgrades (or whatever you want to call it) to get the full
10 FE from 1 Blue power Unit

**Comment by MoreThanHidden** [comment]
Not currently required or planned as is a set efficiency and has no upper limit, just based on supply and consumption, may look into a tiered system for late game machines at some stage.
