### ISSUE TITLE
Energy Unit Suggestion / Discussion

### ISSUE THREAD

**Issue by MineTech123** [Qmunity/BluePower#478]
BF=Bluestone Flux/Blue Flux
BE=Bluestone Energy/ Blue Energy
Or even just BP=BluePower 

Let’s see what you think

Sorry if they are bad it’s night time here I can’t think of better names

**Comment by MoreThanHidden** [comment]
Bluepower Energy is more of an electrical type energy then the current Minecraft power types so the unit names wont likely correspond to the name of the energy itself I was originally thinking more Volts, Watts Scenario and kWh as a Max capacity measurement and Percentages to determine how full.

**Comment by MineTech123** [comment]
BlueVoltage/BlueWatts?
