### ISSUE TITLE
[Question] BluePower 1.12.2

### ISSUE THREAD

**Issue by Ushupiuck** [Qmunity/BluePower#481]
So, as a quick question. after the 1.14 branch (which you're working on) is finished, will more work go towards the 1.12.2 branch, or is 1.12.2 abandoned?

Mostly asking since I loved RedPower back in the day, and being able to use it to it's full extent in 1.12.2 would make my day.
Thanks for reading, keep up that great work! Read you later :P

**Comment by MoreThanHidden** [comment]
If possible I'll probably back port what I can when I get the chance, and will fix any major bugs ( I work full time so barely get enough time to work on as is.) Thanks for the support.

**Comment by MoreThanHidden** [comment]
Added Link to Discord in the Readme https://discord.gg/eSkYN8n
