### ISSUE TITLE
Stone Tile Recipe overwrites Vanilla Smooth Stone recipe

### ISSUE THREAD

**Issue by Darkere** [Qmunity/BluePower#485]
![image](https://user-images.githubusercontent.com/4283717/63951274-bf41e400-ca7d-11e9-9b64-5e29e3b3aa7e.png)

### Forge and Minecraft version ###
1.14
forge .55

### Bluepower version and build number ###
bluepower-1.14.4-0.3.100-alpha-universal

**Comment by MoreThanHidden** [comment]
Oh interesting guess I'll change this to an alloy smelter recipe.

**Comment by MoreThanHidden** [comment]
Or better yet Stonecutter recipe

**Comment by MoreThanHidden** [comment]
![image](https://user-images.githubusercontent.com/1351964/63953512-08ad2600-cab4-11e9-83e8-19f0a502ad8e.png)
![image](https://user-images.githubusercontent.com/1351964/63953549-1f537d00-cab4-11e9-8362-929d09c9d842.png)
