### ISSUE TITLE
Alloy Furnace Reverse smelting does not account for multiple Ouputs

### ISSUE THREAD

**Issue by Darkere** [Qmunity/BluePower#486]
![image](https://user-images.githubusercontent.com/4283717/63951592-5149ec80-ca7e-11e9-86cb-954ce10b814e.png)

![image](https://user-images.githubusercontent.com/4283717/63951603-56a73700-ca7e-11e9-9c5d-aec6a9b286d8.png)

### Forge and Minecraft version ###
1.14
forge .55
### Bluepower version and build number ###
bluepower-1.14.4-0.3.100-alpha-universal

**Comment by MoreThanHidden** [comment]
This is intentional is only supposed to give you the ingots back, is the cost for being able to reuse materials.

**Comment by Darkere** [comment]
Look at the recipes again very closely. Duping....

**Comment by MoreThanHidden** [comment]
Oh lol

**Comment by MoreThanHidden** [comment]
This is why I didn't close it straight away thought I was missing something.

**Comment by MoreThanHidden** [comment]
Fixed, thanks for reporting.
![image](https://user-images.githubusercontent.com/1351964/63960105-444ded00-cac0-11e9-8937-c32a825b30b4.png)
