### ISSUE TITLE
[1.14.4] Request to tag Marble and Basalt

### ISSUE THREAD

**Issue by kwpugh** [Qmunity/BluePower#487]
Hi,

I am the author of the Gobber mod. I have an item called the Ring of the Miner, that clears away vanilla stone and such, leaving ores exposed for mining.

I was wondering if you would consider tagging your Marble and Basalt with the Forge tag "STONE" so that I can easily identify them with if(Block.isRock() method?

isRock checks: net.minecraftforge.common.Tags.Blocks.STONE.contains(blockIn);

If you can add the forge tags for that block, it would make life a lot easier.

This would be a great help.

Thank you for considering.

Regards.

**Comment by MoreThanHidden** [comment]
Thanks for reporting have added the Tag.

**Comment by kwpugh** [comment]
Thank you kindly.
