### ISSUE TITLE
BluePower Engine recipe 

### ISSUE THREAD

**Issue by MineTech123** [Qmunity/BluePower#490]
Idk if you have figured this out but
Recipe idea for Blue Power engine

Steel, Cyan Lamp, Steel
Green Dye, Gear, Green Dye = BluePower Engine
Piston, Motor, Piston

The engine in both RedPower2 and BluePower are green so there has to be a source of that color so that’s the reason why there are green dye
And the same thing applies to the cyan lamp. The thing in the middle is cyan when active

**Comment by MoreThanHidden** [comment]
Current recipe may change in the future:
![image](https://user-images.githubusercontent.com/1351964/65348537-030ab200-dc14-11e9-901a-51467869deb4.png)
