### ISSUE TITLE
Canvas bag dupe

### ISSUE THREAD

**Issue by Darkere** [Qmunity/BluePower#491]
Canvas bags stack. You can put items inside close separate the stack. And dupe the items

Much better explained and in video form here: https://github.com/AllTheMods/ATM-4/issues/13

### Forge and Minecraft version ###
1.14.4 Forge 28.1.20
### Bluepower version and build number ###
0.3.123 alpha

**Comment by MoreThanHidden** [comment]
Thanks for reporting, fixed in [bluepower-1.14.4-0.3.125](https://www.curseforge.com/minecraft/mc-mods/blue-power/files/2795723)
