### ISSUE TITLE
Improve Volcano World Generation

### ISSUE THREAD

**Issue by MoreThanHidden** [Qmunity/BluePower#492]
### What were you doing when the issue happened? ###
Exploring the world. 😄 

### What did you expect to happen? ###
Volcanoes to have random widths, and for the secret room to be deeper inside the Volcano.

### What happened instead ###
Volcanoes all look similar and the room was too high and half cropped.

### Crashlog on pastebin/gist ###
Didn't Crash 👍 

### Forge and Minecraft version ###
Minecraft 1.14.4 - Forge 28.1.20

### Bluepower version and build number ###
1.14.4-0.3.125

**Comment by MoreThanHidden** [comment]
In my experience it actually isn't too bad may revisit this at some stage.

**Comment by Seegras** [comment]
They look like volcanoes drawn by a 4 year old.
