### ISSUE TITLE
Shift clicking items out of Bluelectric Furnace duplicates them

### ISSUE THREAD

**Issue by wieselkatze** [Qmunity/BluePower#494]
### What did you expect to happen? ###
Only the amount stored in the furnace transfering to inventory. When transfering without shift-clicking, everything works as intended.

### What happened instead ###
Double the amount transfered.

### Forge and Minecraft version ###
Forge 28.1.8, Minecraft 1.14.4

### Bluepower version and build number ###
Blue Power 0.3.127

**Comment by MoreThanHidden** [comment]
Fixed in bluepower-1.14.4-0.3.128-alpha
