### ISSUE TITLE
Crash when breaking lamp

### ISSUE THREAD

**Issue by RakSrinaNa** [Qmunity/BluePower#495]
### What were you doing when the issue happened? ###
Breaking a lamp on a dedicated server make other players (not the one that breaks it) crash (sometimes).

I don't know if it is more related to this mod or Optifine as it is also  in the stacktrace, though bluepower is higer up in it.

### What did you expect to happen? ###
No exception.

### What happened instead ###
Crash.

### Crashlog on pastebin/gist ###
https://pastebin.com/59PR1XJ0

### Forge and Minecraft version ###
1.14.4-28.1.26

### Bluepower version and build number ###
1.14.4-0.3.127

**Comment by MoreThanHidden** [comment]
Let me know if this happens again once the new version is available, wasn't able to replicate but it should be fixed in this update.
