### ISSUE TITLE
blue saphir galsses is not witherproof  at all.

### ISSUE THREAD

**Issue by mihwalk** [Qmunity/BluePower#496]
### What were you doing when the issue happened? ###
 
create a cage of this material to spawn a wither within

### What did you expect to happen? ###

to prevent the explosion from the wither 

### What happened instead ###

wither explose all the cage

### Forge and Minecraft version ###

curse forge on twitch mod pack ftb unstable minecraft 1.14.4

### Bluepower version and build number ###

1.14.4-0.3.129

**Comment by MoreThanHidden** [comment]
Well oops sorry about that 😅 I see what you mean, will get that fixed.

**Comment by MoreThanHidden** [comment]
Fixed in bluepower-1.14.4-0.3.133-alpha-universal.jar I've pushed the update to curse.
