### ISSUE TITLE
Sapphire Glass Renders Incorrectly Underwater

### ISSUE THREAD

**Issue by WenXin20** [Qmunity/BluePower#498]
### What did you expect to happen? ###
- Sapphire Glass should render similarly to how Minecraft Glass renders underwater

### What happened instead ###
- Sapphire Glass renders incorrectly underwater, with water flowing down it's sides.

### Image ###
![2019-10-11_21 18 26](https://user-images.githubusercontent.com/12000593/66693460-914fe200-ec6e-11e9-9669-defa4e19ef84.png)

### Forge and Minecraft version ###
`Forge v28.1.44`
`Minecraft v1.14.4`

### Bluepower version and build number ###
`Bluepower v0.3.134-alpha`

**Comment by MoreThanHidden** [comment]
Recurrence of MinecraftForge/MinecraftForge#4679 Forge/Vanilla bug with custom glass rendering, could be extended in forge again for 1.14 but we have a workaround.

**Comment by MoreThanHidden** [comment]
Will be fixed on the next curseforge release, just trying to finish a few more features to be added to the next upload.
