### ISSUE TITLE
Sapphire glass renders incorrectly behind smoke

### ISSUE THREAD

**Issue by wieselkatze** [Qmunity/BluePower#499]
### What did you expect to happen? ###
For the sapphire glass to be rendered behind the smoke

### What happened instead ###
Instead the frame of the sapphire glass rendered in front of the smoke (looks kinda trippy, though)
Other particles (or at least the ones from mobs dying I could see) seem to render correctly; can also be seen on the screenshot

### Forge and Minecraft version ###
Forge 28.1.61, Minecraft 1.14.4
### Bluepower version and build number ###
Blue Power 0.3.135

[Sapphire Glass Smoke](https://imgur.com/a/oydTqkn)

**Comment by MoreThanHidden** [comment]
Is a Vanilla or Forge issue:
![image](https://user-images.githubusercontent.com/1351964/67221131-86126880-f45d-11e9-9bac-0a8c425f8ba2.png)

![image](https://user-images.githubusercontent.com/1351964/67221196-a0e4dd00-f45d-11e9-8230-1f02ed8740e4.png)

**Comment by wieselkatze** [comment]
Confirmed: is a vanilla bug. Tried out plain forge (same thing happening) and vanilla (same as well).
The weirdest thing is: It only happens with stained glass, not normal glass:


![2019-10-21_17 53 58](https://user-images.githubusercontent.com/6273249/67222045-c73e5480-f42c-11e9-8fd9-177c8d22dea9.png)

Anyway, the issue can be closed then - vanilla is weird.

**Comment by MoreThanHidden** [comment]
Yeah, is any transparent blocks, regular glass is cutout, but looks like that was fixed in 1.14.1 maybe it's a forge bug.

**Comment by MoreThanHidden** [comment]
No just tested it happens on vanilla 1.14.4 aswell
