### ISSUE TITLE
Is it really an issue with JEI?

### ISSUE THREAD

**Issue by TheK0tYaRa** [Qmunity/BluePower#500]
### What were you doing when the issue happened? ###
Searched for "wire" in just enough items

### What did you expect to happen? ###
Finding placable wire

### What happened instead ###
Found a wire for brush

### Crashlog on pastebin/gist ###
Not needed

### Forge and Minecraft version ###
1.12.2, 14.23.5.2838

### Bluepower version and build number ###
0.3.38, dunno

**Comment by MoreThanHidden** [comment]
Haven't yet finished porting to 1.12 and will look at if this is required after 1.14 is finished. But no wire is available in 1.12 or 1.14 versions yet.

**Comment by TheK0tYaRa** [comment]
By throwing in all the JEI addons including the one that makes all recipes visible i found it, yay

**Comment by TheK0tYaRa** [comment]
And - yep, it's uncraftable
