### ISSUE TITLE
My Worlds won't load when Blue Power is loaded in 1.14.4

### ISSUE THREAD

**Issue by congueror** [Qmunity/BluePower#502]
### What were you doing when the issue happened? ###
After the latest update when I tried loading a world it didn't work, I kept the world loading for almost 1 hour but it still didn't load(the program was responsive)

### What did you expect to happen? ###
To load in my world and play as usual

### What happened instead ###
I couldn't get in my world

### Crashlog on pastebin/gist ###
Not really anything to put here since the game didn't actually crash, just prevented my world from loading.

### Forge and Minecraft version ###
MC Version: 1.14.4
Forge Version: 28.1.64

### Bluepower version and build number ###
Blue Power Version: 0.3.135

**Comment by MoreThanHidden** [comment]
Updating from what version to what version?
What other mods did you have installed?
Can you attach a log file?

Could be a memory usage issue but nothing has really changed, and has mostly improved.

**Comment by MoreThanHidden** [comment]
Should be fixed in 1.14.4-0.3.147-alpha and have just pushed to curse.
