### ISSUE TITLE
left hand issues in 1.12 version

### ISSUE THREAD

**Issue by bear989** [Qmunity/BluePower#503]
tools are backwards and not orientated properly if using left handed mode
![2019-10-27_02 46 02](https://user-images.githubusercontent.com/8433695/67630818-f2c5a280-f863-11e9-8feb-3650add5e570.png)

![2019-10-27_02 43 41](https://user-images.githubusercontent.com/8433695/67630810-d0cc2000-f863-11e9-8f83-72c0ebfc9e0b.png)

**Comment by MoreThanHidden** [comment]
Ah yeah haven't worked on the 1.12 version for a while is fixed in 1.14
