### ISSUE TITLE
Wire model baking issues

### ISSUE THREAD

**Issue by sverinn** [Qmunity/BluePower#504]
### What were you doing when the issue happened? ###
Loading minecraft instance

### What did you expect to happen? ###
Proper loading

### What happened instead ###
Console returns 
> Unable to bake model: 'bluepower:redalloy_wire#connected_back=false,connected_front=true,connected_left=false,connected_right=true,facing=up,powered=true': java.lang.RuntimeException: Unknown property 'active' on 'Block{bluepower:redalloy_wire}'

and etc. Sometimes it freezes to death, sometimes it loads fine, but in any case it takes very long because of these errors being processed (like ~35k of them every launch).

### Crashlog on pastebin/gist ###
[latest.log](https://github.com/Qmunity/BluePower/files/3775842/latest.log)

### Forge and Minecraft version ###
Minecraft: 1.14.4
forge-28.1.64

### Bluepower version and build number ###
bluepower-1.14.4-0.3.135-alpha-universal.jar

**Comment by MoreThanHidden** [comment]
Yes I'm working on an alternative for these due to how slow the vanilla multipart loader is with dynamic models, might just release a patch if it's going to take too long.

**Comment by sverinn** [comment]
Update: it actually freezes only if Optifine is present. Without optifine, the game loads, it just takes a long time.

**Comment by MoreThanHidden** [comment]
Ok thanks, Yeah it's running out of ram, but I'm changing the way these are done, so will get a fix out soon.

**Comment by MoreThanHidden** [comment]
Fixed in 1.14.4-0.3.147-alpha and have just pushed to curse, wires have been completely disabled for now until I have the logic fixed, will need to FML Confirm.
