### ISSUE TITLE
World Gen Crash

### ISSUE THREAD

**Issue by Novotisy** [Qmunity/BluePower#505]
### What were you doing when the issue happened? ###
Loaded the game, crashed after 10-20 seconds every time
I'm assuming its an incompatibility with biomes o plenty
### Crashlog on pastebin/gist ###
https://pastebin.com/HWVw8uq2
### Forge and Minecraft version ###
28.1.61 1.14, playing on latest version of FTB Unstable
### Bluepower version and build number ###
bluepower-1.14.4-0.3.135-alpha

**Comment by ProsperCraft** [comment]
We have had this quite a bit, and I have just not got around to reporting it.

Modpack- https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk
Version 1.1.18

Forge- forge-1.14.4-28.1.85

bluepower-1.14.4-0.3.135-alpha-universal

Crash logs-
https://gist.github.com/ProsperCraft/8f1bfdcf14bb1f642ee18ce034bec7d0
https://gist.github.com/ProsperCraft/6761722d93a70d3f46832955ae5eb4ed
https://gist.github.com/ProsperCraft/9ec5c82e76e7718046406ca9dcd6af77
https://gist.github.com/ProsperCraft/36e405fbf984eb48d21e22d0f8d22179
https://gist.github.com/ProsperCraft/282c732cdfae75a0b891fe7832656cf1

**Comment by MoreThanHidden** [comment]
Thanks, have a bit more to go on, currently away from home so my dev environment is slow, hopefully I'll get time to look at this tonight.

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/ff76536b847d53917dcff7d91829b299

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/e49efe23d5010b8950a84b1858488edd
https://gist.github.com/ProsperCraft/76ee08299517acc5dc3066605dd31276

**Comment by ProsperCraft** [comment]
This seems to have resolved with the fix, but then this started-
https://github.com/Qmunity/BluePower/issues/510
