### ISSUE TITLE
axes have the wrong damage and speed stats (1.12)

### ISSUE THREAD

**Issue by bear989** [Qmunity/BluePower#506]
![2019-11-01_23 53 49](https://user-images.githubusercontent.com/8433695/68065671-0610bc00-fd03-11e9-8081-02ef404c8df8.png)
![2019-11-01_23 53 50](https://user-images.githubusercontent.com/8433695/68065674-09a44300-fd03-11e9-8e44-2e4ec9af9cbe.png)
![2019-11-01_23 54 00](https://user-images.githubusercontent.com/8433695/68065677-0c9f3380-fd03-11e9-93f6-62879c77f201.png)

**Comment by MoreThanHidden** [comment]
Fixed in BluePower-1.12.2-0.3.148
