### ISSUE TITLE
[Enhancement] Flickering Furnaces cause massive FPS lag

### ISSUE THREAD

**Issue by wieselkatze** [Qmunity/BluePower#507]
When Blulectric Furnaces run out of power and flicker on and off, the graphic updates cause massive FPS lags (stutter).
Maybe the model can be updated after x amount of time to prevent this from happening when furnaces flicker so it's still visible they're ruynning, but don't cause this stutter.

![2019-11-03_18 32 41](https://user-images.githubusercontent.com/6273249/68089364-6cfbb580-fe68-11e9-94a7-5c4307f8dda4.png)

### Forge and Minecraft version ###
Minecraft 1.14.4 on Forge 28.1.79
### Bluepower version and build number ###
Blue Power 0.3.135

**Comment by MoreThanHidden** [comment]
Need to give them more power or you game dies :stuck_out_tongue_closed_eyes: 
Is now on my ever growing list of cleanup tasks.

**Comment by MoreThanHidden** [comment]
Fixed in bluepower-1.14.4-0.3.157-alpha uploaded to curse.
