### ISSUE TITLE
Exception loading blockstate definition

### ISSUE THREAD

**Issue by NillerMedDild** [Qmunity/BluePower#508]
### What were you doing when the issue happened? ###
Starting the game

### What did you expect to happen? ###
The log to be a bit shorter.

### What happened instead ###
Thousands of lines of `Exception loading blockstate definition` from BluePower - See attached log for details.

### Crashlog on pastebin/gist ###
https://gist.github.com/NillerMedDild/25eda0e0e6b97ee2a27ac679542bcb60
Please disregard the ToastControl crash that is also in that log :P

### Forge and Minecraft version ###
- Forge-1.14.4-28.1.79

### Bluepower version and build number ###
bluepower-1.14.4-0.3.135-alpha-universal

**Comment by Boomflex** [comment]
Can confirm: https://gist.github.com/Boomflex/2ad26d621d862f580ed5d2a317045533

Posted on to your Discord a couple hours ago.

Logs are getting up to 20-30mb full of the blockstate definition issues.

**Comment by MoreThanHidden** [comment]
Fixed in 1.14.4-0.3.147-alpha and have just pushed to curse, there are still a few error messages but this should be much better.
