### ISSUE TITLE
Allow more blocks to be Waterlogged

### ISSUE THREAD

**Issue by WenXin20** [Qmunity/BluePower#509]
### What did you expect to happen? ###
Currently, most blocks can't be waterlogged, which creates air spaces in water when blocks, such as lamps and multiblocks, are placed in water.
Allowing this could allow for new decoration enhancements

### Forge and Minecraft version ###
Forge v28.1.87
Minecraft v1.14.4

### Bluepower version and build number ###
Bluepower v0.3.135-alpha

**Comment by MoreThanHidden** [comment]
Lamps and Microblocks are now Waterloggable

**Comment by WenXin20** [comment]
Unless this is intentional, it looks like several blocks were missed from being waterloggable. This includes Blulectric Cable & Engine, Solar Panels, and the AND & NAND Gates.

**Comment by MoreThanHidden** [comment]
Fixed in bluepower-1.14.4-0.3.160-alpha now available on curse.
