### ISSUE TITLE
[1.14.4] Worldgen Crash - NPE - com.mojang.datafixers.util.Either$Left.map

### ISSUE THREAD

**Issue by ProsperCraft** [Qmunity/BluePower#510]
### What were you doing when the issue happened? ###
My dedicated server keeps crashing since I updated these mods-

Attained Drops, Blue Power, Chinese Workshop, Default Settings, Engineer's Decor, Explorercraft, Gobber2, Kiwi, McJtyLib, Minecolonies, Packing Tape, Placebo, RFTools Base, RFTools Power, SecurityCraft, Tubes Reloaded,

Unfortunately, it doesn't list any of the mods in the stacktrace.

### Crashlog on pastebin/gist ###
https://gist.github.com/ProsperCraft/5b170b37e67234e3eba7ac73318451c5
[crash-2019-11-09_13.18.45-server.txt](https://github.com/Qmunity/BluePower/files/3828434/crash-2019-11-09_13.18.45-server.txt)
[crash-2019-11-09_14.47.58-server.txt](https://github.com/Qmunity/BluePower/files/3828435/crash-2019-11-09_14.47.58-server.txt)
[crash-2019-11-09_15.07.29-server.txt](https://github.com/Qmunity/BluePower/files/3828436/crash-2019-11-09_15.07.29-server.txt)
[crash-2019-11-10_02.57.14-server.txt](https://github.com/Qmunity/BluePower/files/3828437/crash-2019-11-10_02.57.14-server.txt)
[crash-2019-11-10_03.21.41-server.txt](https://github.com/Qmunity/BluePower/files/3828438/crash-2019-11-10_03.21.41-server.txt)
[crash-2019-11-09_13.04.27-server.txt](https://github.com/Qmunity/BluePower/files/3828439/crash-2019-11-09_13.04.27-server.txt)

### Forge and Minecraft version ###
forge-1.14.4-28.1.87

### Bluepower version and build number ###
bluepower-1.14.4-0.3.147-alpha-universal

###Modpack###
https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by MoreThanHidden** [comment]
Not sure that this is a Blue Power issue, have you tired backing up and removing mods to find the cause? Ruins is a possible candidate based on the line at the Chunk Generator: e:classloading,pl:accesstransformer:B,xf:fml:ruins:Ruins chunk decoration Hook

**Comment by ProsperCraft** [comment]
Ruins last update was Oct 24th and has not caused this crash.

The crash started after updating the mods above, yes, I will have to pull the mods one at a time was fishing hoping I would not have to spend four hours troubleshooting it as it just started with this update, but will do.

**Comment by MoreThanHidden** [comment]
Can downgrade to the old version to rule it out, but yeah I feel your problem back when I was making packs was a constant struggle, especially when the logs turn up a blank. I'll still check things out on my side but is hard to find the cause if I can't replicate it, does the server just crash immediately or only while generating chunks.

**Comment by ProsperCraft** [comment]
Only when generating chunks while players are playing, I have not been on the server when it crashes,.

**Comment by MoreThanHidden** [comment]
Sorry haven't been able to replicate this, if you can confirm it's Blue Power causing the crash let me know.
