### ISSUE TITLE
[low priority issue] BluePower enchantment descriptions

### ISSUE THREAD

**Issue by BardGitH** [Qmunity/BluePower#511]
bluepower is currently missing a local enchant description used by mods such as COFH core and Enchantment descriptions
![image](https://user-images.githubusercontent.com/57300546/68582443-03d4fd00-047b-11ea-9be8-7f79558a45b8.png)

bluepower-1.14.4-0.3.147-alpha-universal.jar

**Comment by MoreThanHidden** [comment]
Fixed in bluepower-1.14.4-0.3.154-alpha now available on curse.
