### ISSUE TITLE
Crash: Blue electric Alloy Furnace

### ISSUE THREAD

**Issue by Tarlin83** [Qmunity/BluePower#512]
Game is being forced to close and crash on the server side due to the Alloy Furnace by Blue Electric causing a tick delay that is substantial. It is triggering a watchdog alert due to the ticking time increasing rapidly on the server.

### What were you doing when the issue happened? ###
Player on the server was using the alloy furnace powered by solar panels from blue power mod and vanilla hoppers under it. Began to smelt armor and crashed the server.
### What did you expect to happen? ###
armor to smelt normally
### What happened instead ###
server crashed
### Crashlog on pastebin/gist ###
https://paste.ubuntu.com/p/jZ59srgQSD/
### Forge and Minecraft version ###
Forge 28.1.87
Minecraft 1.14.4
### Bluepower version and build number ###
bluepower-1.14.4-0.3.147-alpha

Crosslink to World of Dragons - New Age mudpack where crash occurred
https://github.com/kreezxil/World-of-Dragons-A-New-Age/issues/52

**Comment by Tarlin83** [comment]
FULL crash report. Seems to be occurring due to a tick issue when the alloy furnace is attached to a hopper it is causing the hopper to tick to the extreme.

Crash report of most recent occurrence
https://paste.ubuntu.com/p/csRZ9kXGK9/

**Comment by MoreThanHidden** [comment]
Ok thanks for reporting, I'll take a look tonight after I get home from work, finally I won't be working from a potato like the past 4 weeks.

**Comment by Tarlin83** [comment]
Hey @MoreThanHidden, thanks for taking the time to look into this. If I can help in any way please let me know.

**Comment by MoreThanHidden** [comment]
Fixed in bluepower-1.14.4-0.3.151-alpha and have uploaded to curse.
