### ISSUE TITLE
WIKI > Planned Feature

### ISSUE THREAD

**Issue by daniel-for-github** [Qmunity/BluePower#513]
What were you doing when the issue happened?  >searching 

What did you expect to happen? > see title

what happened instead > wiki = 1page TheHeadlessMonk edited this page on 9 Aug 2014

**Comment by MoreThanHidden** [comment]
Sorry don't understand what your after here, assuming an updated Wiki, I won't have time for this at least until the base features have been ported and the mod is out of an alpha state.
