### ISSUE TITLE
[1.14.4] Transposer not rotating *Visually*

### ISSUE THREAD

**Issue by Nachtflame** [Qmunity/BluePower#514]
### What did you expect to happen? ###
When placing Transposer in world, expecting Model to rotate in relation to placement direction, same as all other world-interaction blocks.

### What happened instead ###
Transposer model appears to _always face North_ instead of direction block is Actually pointed

### Crashlog on pastebin/gist ###
No Crash involved - but Pictures showing 3 directionaly different Transposers, (according to _Facing_ attribute in F3), all visually facing same, incorrect direction.
https://imgur.com/a/jsOCysx

### Versions ###
Minecraft 1.14.4
forge-28.1.90
bluepower-1.14.4-0.3.151-alpha-universal

**Comment by MoreThanHidden** [comment]
Weird thought I fixed that, will take a look tonight.

**Comment by MoreThanHidden** [comment]
Fixed in bluepower-1.14.4-0.3.154-alpha now available on curse.
