### ISSUE TITLE
[1.14.4] TileMachineBase causes server/client to crash on waila lookup

### ISSUE THREAD

**Issue by Electrofried** [Qmunity/BluePower#515]
### What were you doing when the issue happened? ###

Looking at an engine on a server

### What did you expect to happen? ###

The client and server not to crash and waila info display

### What happened instead ###

client crashed along with server due to NoSuchMethod. (see crash log)

### Crashlog on pastebin/gist ###

[crash-2019-11-19_05.06.36-server.txt](https://github.com/Qmunity/BluePower/files/3860373/crash-2019-11-19_05.06.36-server.txt)

### Forge and Minecraft version ###

1.14.4 and forge 28.1.90

### Bluepower version and build number ###

bluepower-1.14.4-0.3.151-alpha-universal

**Comment by MoreThanHidden** [comment]
Fixed in bluepower-1.14.4-0.3.154-alpha now available on curse.
