### ISSUE TITLE
Seed Bags & Ejector Missing GUI Texture

### ISSUE THREAD

**Issue by WenXin20** [Qmunity/BluePower#517]
### What happened instead ###
- Upon shift-right-clicking on the Seed Bag & opening the Ejector, the GUI opened with only a purple and black missing texture.
- Canvas Bags and Seed Bags are missing the tooltip localization.

### Forge and Minecraft version ###
`Minecraft v1.14.4`
`Forge v28.1.90`

### Bluepower version and build number ###
`Bluepower v0.3.154-alpha`

**Comment by MoreThanHidden** [comment]
They weren't missing the texture so possibly a recurrence of #470

**Comment by WenXin20** [comment]
That looks like it might be the case.

**Comment by MoreThanHidden** [comment]
Fixed in bluepower-1.14.4-0.3.157-alpha uploaded to curse.
