### ISSUE TITLE
Microblocks drop when broken in creative

### ISSUE THREAD

**Issue by WenXin20** [Qmunity/BluePower#518]
### What were you doing when the issue happened? ###
I was in creative, placing down the stone covers.

### What did you expect to happen? ###
Breaking the stone covers should drop nothing.

### What happened instead ###
But instead items will drop despite being broken in creative.

### Forge and Minecraft version ###
`Minecraft v1.14.4`
`Forge v28.1.90`

### Bluepower version and build number ###
`Bluepower v0.3.157-alpha`

**Comment by MoreThanHidden** [comment]
Fixed in bluepower-1.14.4-0.3.160-alpha now available on curse.
