### ISSUE TITLE
Tooltips in GUIs overlap JEIs Favorites List

### ISSUE THREAD

**Issue by WenXin20** [Qmunity/BluePower#519]
### What were you doing when the issue happened? ###
I had added many items to JEIs Favorite List by pressing `A` while hovering over the items I wanted to save. Then I had clicked on the tooltip icon to expand it.

### What did you expect to happen? ###
The JEI item list should move to allow room for the tools.

### What happened instead ###
But instead items will overlap the tooltips, making it difficult to read.

### Forge and Minecraft version ###
`Minecraft v1.14.4`
`Forge v28.1.90`
`JEI v6.0.0.25`

### Bluepower version and build number ###
`Bluepower v0.3.157-alpha`

**Comment by WenXin20** [comment]
Canvas Bags and Seed Bags are also missing the tooltip localization still.

**Comment by MoreThanHidden** [comment]
Widget is now only on machines and needs to be expanded before it conflicts with JEI.
