### ISSUE TITLE
16x Textures

### ISSUE THREAD

**Issue by 88onme** [Qmunity/BluePower#521]
I know this is probably not the issue your team wants to hear, but I would really appreciate if some better textures were used. With 1.14's emphasis being better textures by JAPPA, it would be really fitting for the mod to get an upgrade art-wise to fit in better with the game's new aesthetic.

**Comment by MoreThanHidden** [comment]
There is a 16x Texture Pack available here thanks to @CyanideX: 
https://www.curseforge.com/minecraft/texture-packs/unity-modded
![bp](https://user-images.githubusercontent.com/1351964/69489539-836bbe80-0eb4-11ea-86df-7973af269828.gif)
![image](https://user-images.githubusercontent.com/1351964/69489556-e198a180-0eb4-11ea-88a1-ffce80e67a59.png)


The 32x was an attempt to differentiate the mod somewhat from Red Power, and is a continuation of the 1.7.10 version of the mod.

**Comment by MoreThanHidden** [comment]
Personally I don't mind the 32x textures and I find it still blends well with the new textures and provides flexibility in the design.

Closing for now as this has been discussed before #212 and 16x Texture packs are available.
