### ISSUE TITLE
[Recipe Request] Cracked Basalt

### ISSUE THREAD

**Issue by ghost** [Qmunity/BluePower#523]
Recipe for the cracked basalt block which sometimes spawn on top of volcanoes 

Maybe
Lava Bucket + Basalt = Cracked Basalt

**Comment by MoreThanHidden** [comment]
These are designed to randomly erupt so as such aren't craft-able or silk touch-able, can look at creating a visually similar block without the effect.

**Comment by TheUntamed** [comment]
I would like to have it as harmless block as well.

**Comment by MoreThanHidden** [comment]
Added will be in next release.
