### ISSUE TITLE
[1.14.4] Blockbreaker causes server to crash

### ISSUE THREAD

**Issue by bart1ebee** [Qmunity/BluePower#524]
### What were you doing when the issue happened? ###
Placing block breaker 
### What did you expect to happen? ###
The server not to crash
### What happened instead ###
Server crash. Server will restart but when client connecting it will crash again. 
### Crashlog on pastebin/gist ###
https://pastebin.com/9tyHZqUs
### Forge and Minecraft version ###
Forge 28.190 MC 1.14.4
### Bluepower version and build number ###
bluepower-1.14.4-0.3.160-alpha

Tried this in Single player and it does not crash.

**Comment by MoreThanHidden** [comment]
Hopefully fixed in bluepower-1.14.4-0.3.161-alpha
