### ISSUE TITLE
Request: Cross-mod compatibility

### ISSUE THREAD

**Issue by trevorjd** [Qmunity/BluePower#527]
I have a cut-down pack that started as FTB unstable 1.14. I've removed a bunch of mods and updated all the survivors to the latest versions.

Silent Mechanisms adds a crusher that creates ore 'chunks' at the usual double rate, which can then be further processed or simply thrown in the Furnace to smelt into ingots.  The vanilla furnace and a couple of other modded furnaces are all fine to smelt these, but the Blulectric Furance, sadly, does not recognise the chunks as being a valid item for smelting.

### Forge and Minecraft version ###
1.14.4-28.1.104

### Bluepower version and build number ###
bluepower-1.14.4-0.3.161-alpha-universal

**Comment by MoreThanHidden** [comment]
Recipes can be added with Json Datapacks or with Craft tweaker details here: https://github.com/Qmunity/BluePower/wiki/%5B1.14%5D-Alloy-Furnace-Recipe-Json-Format

I'm working on adding native craft tweaker support but until then the Json scripts work well.

**Comment by trevorjd** [comment]
Can the Blulectric furnace not inherit the vanilla furnace recipes?

**Comment by MoreThanHidden** [comment]
Oh was looking at this on my phone and thought you meant the alloy furnace, Blulectric Furance does inherit smelting recipes. So not sure why these wouldn't work but I'll take a look.

**Comment by trevorjd** [comment]
I have no idea if I was doing something wrong, or if I've updated something which fixed an incompatibility, but the Blulectric Furnace is _Working as Intended_ now. Smelting Silent's crushed ores without a problem. /shrug

Thanks for the snappy reply!
