### ISSUE TITLE
Cant craft the Project Table [1.14]

### ISSUE THREAD

**Issue by PABessero** [Qmunity/BluePower#529]
Since Quark chests are replacing Vanilla chests if installed, the project table cant be crafted since it doesnt use the oreDict chest value

### What were you doing when the issue happened? ###
Trying to craft a project table

### What did you expect to happen? ###
Being able to craft the table with a Quark chest

### What happened instead ###
The project table can only be crafted with vanilla chests found in dungeons / villages

### Forge and Minecraft version ###
MC: 1.14.4
Forge: 2.8.1.107

### Bluepower version and build number ###
Bluepower: 0.3.161-Alpha-Universal (1.14.4)

**Comment by MoreThanHidden** [comment]
Quark overwrites oak chests now? I'll change the recipe to use the tag.

**Comment by PABessero** [comment]
Yup, quark overwrites oak chests no matter which recipe you try to use
