### ISSUE TITLE
[1.15.1] java.lang.NoClassDefFoundError on startup

### ISSUE THREAD

**Issue by TheMCBrothers** [Qmunity/BluePower#530]
### What were you doing when the issue happened? ###
Starting minecraft

### What did you expect to happen? ###
Start normal

### What happened instead ###
Error on startup appeared

### Crashlog on pastebin/gist ###
latest.log : https://gist.github.com/TheMCBrothers/04b5e647b10668c397999ef6fc287ecd

### Forge and Minecraft version ###
Minecraft 1.15.1
Forge 30.0.15

### Bluepower version and build number ###
bluepower-1.15.1-0.4.173-alpha-universal

### Image ###
![screenshot](https://i.imgur.com/TFeflgT.png)

**Comment by MoreThanHidden** [comment]
Forge update broke it, will probably get a few of these kinds of errors until the release branch.
Will update it now.
