### ISSUE TITLE
Quark Bug - Server Crash While Launching

### ISSUE THREAD

**Issue by Darkfiend009** [Qmunity/BluePower#531]
### What were you doing when the issue happened? ###
Launching a server.
### What did you expect to happen? ###
The server to launch.
### What happened instead ###
The server crashed.
### Crashlog on pastebin/gist ###
https://pastebin.com/TLasZhtf
### Forge and Minecraft version ###
Minecraft 1.14.4
Forge 28.1.107
### Bluepower version and build number ###
bluepower-1.14.4-0.3.172-alpha-universal

I know the crash says Quark. However, this crash only occurs when i have .172 of Blue Power installed. The previous version works fine. So i am assuming there is a compatibility issue somewhere. I will be reporting to quark as well.

**Comment by MoreThanHidden** [comment]
No idea, Could you post a full log? 

I've tested running a server with Blue Power Build 172 and Quark without issues.

**Comment by Darkfiend009** [comment]
Yeah, i have no idea why i only pasted part of it. My bad.

https://pastebin.com/fvc6k3rv

**Comment by MoreThanHidden** [comment]
Is there a location I could download your pack from to test? or any further information in the standard log rather then crash log file. Just trying to see what it is crashing on.

**Comment by Darkfiend009** [comment]
I haven't uploaded the modpack as a project yet as i was still working on configurations. If need be, i can make a project page and upload it.

Here is a log generated fresh off a crash. I hope it helps somehow!
[latest.log](https://github.com/Qmunity/BluePower/files/3999316/latest.log)

**Comment by MoreThanHidden** [comment]
Would send the full crash log and the latest log to Quark I'm not sure what is breaking on their side and I can't replicate it.

**Comment by Darkfiend009** [comment]
Thank you for taking time to look into this. Looks like the issue was resolved with the latest update of Quark!
