### ISSUE TITLE
Quark Bug - Duplication with canvas bags

### ISSUE THREAD

**Issue by acorryn** [Qmunity/BluePower#532]
### What were you doing when the issue happened? ###
Actively attempting to dupe with the bags to see if there was a bug, and I found one.

Take a canvas bag, put the items you want more of inside the bag.
Close the bag and re-open it.
Take your bag's items out but keep it open, swap your bag with your off hand by hovering your cursor over the bag and pressing the F key (or whichever key is set to swap main/offhand)
(Also works if you open the bag in the off-hand, use F to swap it into your main inventory.)
The items return as if they never left the bag.  You now have copies of them.
### What did you expect to happen? ###
The bag should update its NBT data on every change made to its inventory, or at the least be unmovable by any means like it is when attempting to move it with number keys.
### What happened instead ###
The bag moved and the data on the bag wasn't updated to reflect the changes made to the bag's contents.
### Crashlog on pastebin/gist ###
No crash log or console log.
### Forge and Minecraft version ###
Forge 28.1.109
Minecraft 1.14.4
### Bluepower version and build number ###
bluepower-1.14.4-0.3.172-alpha-universal

**Comment by MoreThanHidden** [comment]
Not an issue with the base mod as I lock the slot when the inventory is open and it doesn't allow you to switch hands, Quark appears to ignore the locked slot.

**Comment by MoreThanHidden** [comment]
Disabling "F To Switch" in the quark settings stops this particular bug but probably also occurs in other areas, have raised an issue with Quark.

**Comment by MoreThanHidden** [comment]
This has been fixed on the quark side.
