### ISSUE TITLE
1.15.1 Load issue on forge version 30.0.17+

### ISSUE THREAD

**Issue by RayzoRayy** [Qmunity/BluePower#533]
### What were you doing when the issue happened? ###
Loading MC
### What did you expect to happen? ###
MC to load normally
### What happened instead ###
MC did not load and said your mod encountered an error during the complete event phase
### Full Log and Crashlog on pastebin/gist ###
LOG: https://pastebin.com/TD9J3UyQ Crash: N/A
### Forge and Minecraft version ###
1.15.1 MC
30.0.18 Forge
### Bluepower version and build number ###
bluepower-1.15.1-0.4.174-alpha-universal

**Comment by MoreThanHidden** [comment]
Thanks for the report Forge 1.15.1-30.0.17 introduced a breaking change to ClientRegistry.bindTileEntityRenderer will fix this soon, was working on forge up to 30.0.16.
