### ISSUE TITLE
[1.15.1] Crash on startup

### ISSUE THREAD

**Issue by NillerMedDild** [Qmunity/BluePower#534]
### What were you doing when the issue happened? ###
Starting my modpack

### What did you expect to happen? ###
I expected it to load

### What happened instead ###
It kept reloading datapacks, never actually getting ready/reaching the menu.

### Full Log and Crashlog on pastebin/gist ###
https://gist.github.com/NillerMedDild/7202bf4602863fcf23470150fc006ba3

### Forge and Minecraft version ###
- Forge-1.15.1-30.0.30
- Minecraft -1.15.1

### Bluepower version and build number ###
- bluepower-1.15.1-0.4.176-alpha-universal.jar

**Comment by MoreThanHidden** [comment]
Fixed in Blue Power 1.15.1-0.4.179-alpha

**Comment by NillerMedDild** [comment]
Thanks!
