### ISSUE TITLE
Conflict with Silent's Gems/Gear/Lib

### ISSUE THREAD

**Issue by Gamerbolts** [Qmunity/BluePower#536]
### What were you doing when the issue happened? ###
I logged into my server and received a message saying "Something went wrong with chaos buff loading! This may be caused by another broken mod, even those not related to Silent's Gems."
### What did you expect to happen? ###
There not to be an error
### What happened instead ###
That message that happened. Sent it over to SilentChaos and he told me to look into the log and search "Failed to reload data packs" I did that and on line: 3572 I found:

Caused by: java.lang.NullPointerException
	at com.bluepowermod.util.DatapackUtils.generateAlloyFurnaceRecipe(DatapackUtils.java:27) ~[?:0.3.182-alpha]

### Full Log and Crashlog on pastebin/gist ###
[latest-1.log](https://github.com/Qmunity/BluePower/files/4130017/latest-1.log)

### Forge and Minecraft version ###
Forge Version 28.1.111
Minecraft 1.14.4

### Bluepower version and build number ###
0.3.182-alpha

Hope this helps in fixing the issue. Thank you

**Comment by MoreThanHidden** [comment]
Another mod seems to be throwing off the recycling recipes and in turn is causing Blue Power to crash the registry. I wasn't able to replicate the error but I've put a catch in that location so it doesn't crash the registry and cleaned up the way I check for missing inputs.

**Comment by MoreThanHidden** [comment]
Won't break in either of the following builds:
bluepower-1.15.2-0.4.184-alpha
bluepower-1.14.4-0.3.183-alpha

But I still feel like another mod is breaking the registry so see how you go.
