### ISSUE TITLE
[1.15.2] Request for Forge tagged recipes

### ISSUE THREAD

**Issue by kwpugh** [Qmunity/BluePower#537]
Hi

Would you consider adding a few smelting or blast furnace recipes to leverage Forge tags?

In particular:
- a recipe for your copper ingot that uses forge:dusts/copper
- a recipe for your tungsten ingot that uses forge:dusts/tungsten
- a recipe for your tungsten-carbides that uses forge:dusts/tungsten_carbide

Thank you for considering.

Regards.

**Comment by MoreThanHidden** [comment]
Ok but there aren't dusts for copper or tungsten in the mod, so wouldn't mods that add dusts have their own smelted recipes? Not sure if adding our own recipe would conflict with that.

**Comment by kwpugh** [comment]
Ok, never mind.
