### ISSUE TITLE
blue power [1.15.2] java.util.concurrent.ExecutionException: java.lang.RuntimeException: Attempted to load class net/minecraftforge/resource/ReloadRequirements for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by SDUBZ** [Qmunity/BluePower#539]
Forge: forge-1.15.2-31.1.18
blue power: bluepower-1.15.2-0.4.184-alpha-universal

Logs:
[latest.log](https://github.com/Qmunity/BluePower/files/4297180/latest.log)
[debug.log](https://github.com/Qmunity/BluePower/files/4297182/debug.log)

**Comment by MoreThanHidden** [comment]
Please follow the template when reporting, I can't see how this is a Blue Power error, I have a reload listener but aren't using ReloadRequirements anywhere that I can see, have tested this on the forge version specified with no issues.

Assuming this is an error on a dedicated server?

When does the error happen at launch or randomly?

What other mods are installed?

Does this error still happen when removing Blue Power?

If not could you try running /reload and see if it crashes?

**Comment by SDUBZ** [comment]
yeah this error only occurs on dedicated server not sure why, i even tried redownloading jar of mod,
during load up of world on server

**Comment by SDUBZ** [comment]
okay tested without bluepower msg stil shows im just wondering what in forge is causing to run at all 🤔

**Comment by SDUBZ** [comment]
okay found the 2 mods responsibie for the trigger if you get this error from another user check to see if they have the interior mod or flux mod installed tell them to disable to see if it fixes the issue, i know flux has fixed this issue but interior mod hasnt dont any patching to fix occuring

**Comment by ProsperCraft** [comment]
Same issue, COMBAT is disabled.
https://gist.github.com/ProsperCraft/b48a9e6a0b7ccd5d0e47f7a111e60eec

I had the interior mod as well, trying without interior mod.
