### ISSUE TITLE
[1.15.2-0.4.184] Breaking grass doesn't let other mods drop their seeds

### ISSUE THREAD

**Issue by shortybsd** [Qmunity/BluePower#540]
### What were you doing when the issue happened? ###
Breaking grass

### What did you expect to happen? ###
Get seeds from other mods, even my own.

### What happened instead ###
Only drops Wheat Seeds and your Flax seeds due to your `data\minecraft\loot_tables\blocks\tall_grass.json` overriding all grass and tall grass with only Wheat seeds and Flax seeds. Also with chance being 0.125 makes it roughly 5 times more. Set my mod to 0.025 and is not as much overkill with seeds hehe. 
**To fix this**, move your tall_grass.json to `data\bluepower\loot_tables\blocks\tall_grass.json` then it will not override all seeds from all other mods but simply add your seeds to the grass.

### Full Log and Crashlog on pastebin/gist ###
N/A

### Forge and Minecraft version ###
31.1.25
### Bluepower version and build number ###
1.15.2-0.184

**Comment by MoreThanHidden** [comment]
Don't think its that simple last I checked, moving tall_grass.json to the bluepower namespace will cause it just not to work as we are changing the loot of vanilla tall grass.

**Comment by shortybsd** [comment]
Using the minecraft ModID overrides all grass besides tall grass. I remove your mod, my seeds drop and every other mod seeds drop. Check out Ray's Dongles [on how he did it](https://github.com/RayzoRayy/RaysDongles/blob/1.15.x/src/main/java/com/rbs/slurpiesdongles/events/SeedsDropFromGrass.java). His doesn't interfere with other mods nor block every other mod's seed from dropping from grass.
I will edit the jar on the server and move where you are globally replacing all existing seeds with yours and vanilla only via (data\minecraft) and move it to (data\bluepower). I'll let you know the outcome shortly.

**Comment by MoreThanHidden** [comment]
The way Ray's Dongles is doing it is how it was done in 1.12 this no longer works in 1.13+ there are ways to do this I just need to spend some time on it.

**Comment by shortybsd** [comment]
Rays's 1.15 code works though. Same goes for [Simple Farming](https://github.com/enemeez/simplefarming/blob/1.15/src/main/resources/data/simplefarming/loot_tables/blocks/grass_drops.json) and [XL Food Mod](https://github.com/mariot7/XL-Food-Mod/blob/1.15/src/main/resources/data/xlfoodmod/loot_tables/blocks/grass.json)

**Comment by MoreThanHidden** [comment]
No that git isn't updated to 1.15, don't worry I know how to fix it I just need to inject the loot table.

**Comment by shortybsd** [comment]
Thank you my seeds drop now as well as all other mods lol ! <3
