### ISSUE TITLE
Disabled wireless transmitter ?

### ISSUE THREAD

**Issue by undeadgod47** [Qmunity/BluePower#542]
### What were you doing when the issue happened? ### 
playing technic legends.

### What did you expect to happen? ###
was trying to build with the wireless transmitter and wireless receiver, tried to place. 

### What happened instead ###
doesn't let me place either. so I check in my inventory and says they both are disabled.

### Forge and Minecraft version ###
1.7.10 / 1.7.10

### Bluepower version and build number ###
1.7.10 / 0.2.962

**Comment by MoreThanHidden** [comment]
Sorry I can't support the 1.7.10 version, and this feature wasn't fully implemented.
