### ISSUE TITLE
New Feature: Implement crafting chips

### ISSUE THREAD

**Issue by zaped212** [Qmunity/BluePower#543]
### What were you doing when the issue happened? ###
ProjectRed had crafting chips that would be used for form networks allowing the user to create complex automatic crafting setups.

The different chips allow saying that a given node will craft a certain item using a "recipe"
For example, you could say that a furnace can "craft" iron ingots, by receiving iron ore.

The pipes also allowed access to all storage blocks in the system. Meaning the user could access a specific tube type and be able to request from any of the available items ( including ones that could be crafted ) and have it dispensed for them.

**Comment by MoreThanHidden** [comment]
Yeah don't think that is right for this mod will have similar functionality with tubes and sorting systems once they are ported.
