### ISSUE TITLE
Update installation documention

### ISSUE THREAD

**Issue by zaped212** [Qmunity/BluePower#544]
### What were you doing when the issue happened? ###
When doing a fresh checkout of the master branch, I followed the installation instructions however some of the commands are no longer necessary.

For my purposes I only needed to use the commands:

"gradlew build"
and
"gradlew runClient"

Updating the documentation will make it easier for new users to help contribute to the code base.

**Comment by MoreThanHidden** [comment]
If you'd like to contribute this is one of they ways, can write a PR to update the README.md

**Comment by MoreThanHidden** [comment]
Fixed in #546
