### ISSUE TITLE
[1.15.2] Weird bug with recipes and item tags

### ISSUE THREAD

**Issue by TheUntamed** [Qmunity/BluePower#545]
### What were you doing when the issue happened? ###
I included a script for crafttweaker into my modpack that removes item tags of different items (e.g. the <tag:forge:ingots/copper> tag is removed of any copper ingot except one).

### What did you expect to happen? ###
I know that script works because another modpack author uses it in his modpack without problems (bluepower is not included in his pack). The tags should be removed and the items not longer be accepted by recipes using that tag.

### What happened instead ###
In my case the tags were removed of the items but the items were still accepted by the recipes using that removed tag (e.g. a copper ingot I removed the <tag:forge:ingots/copper> tag of could still be used for recipes expecting an item with that tag as input. This includes recipes of all mods and all crafting tables/machines).

I invested a lot of time debugging this problem and found out that it has to be a mod causing this problem and not a script. I could narrow it down to this mod. If I remove this mod everything works as expected. If I include it back in, it's broken again. And it doesn't matter if I include this mod in the script (e.g. remove tags of items from this mod) or not.

### Full Log and Crashlog on pastebin/gist ###
No errors or crashes. Game and script were loading fine except for the result.
I know that makes it hard to find the source of the problem, but you know your code and maybe you have an idea where (maybe during startup) your mod interacts with recipes or item tags in a way that might cause this problem.
An idea to reproduce would be to include bluepower + crafttweaker + X and write a script with e.g.
<tag:forge:ingots/copper>.removeItems([<item:bluepower:copper_ingot>]); (the item can also be from a different mod).

### Forge and Minecraft version ###
Tested with 31.1.43 and 31.1.37

### Bluepower version and build number ###
I tried the two latest versions: 0.4.186-alpha and 0.4.184-alpha
Same problem with both.

**Comment by MoreThanHidden** [comment]
I'll need to do some testing but I'm not doing anything fancy with tags just defining them, maybe the same issue occurs after a reload as I'm forcing a /reload if recycling recipes are enabled, I'll check if that is the case and if so is probably a craft tweaker or tag reload bug.
