### ISSUE TITLE
Game crash when placing Sortron

### ISSUE THREAD

**Issue by charmesal** [Qmunity/BluePower#548]
### What were you doing when the issue happened? ###
I placed a Sortron block with missing texture

### What did you expect to happen? ###
For a Sortron block to be placed with a missing texture

### What happened instead ###
The game froze (after a force shutdown and restart MC crashes on world load)

### Full Log and Crashlog on pastebin/gist ###
Lastest.log(after freeze): https://gist.github.com/charmesal/2439ac038f1ccc92385d669d16f6b8b5
Latest.log(after restarting MC and loading the world): https://gist.github.com/charmesal/ffa92283dc91c4111277140f9a6c02dc
Crash report: https://gist.github.com/charmesal/c91b6a42526a949e13b38f37b11c9d9b

### Forge and Minecraft version ###
Minecraft 1.15.2
Forge 1.15.2-forge-31.1.43

### Bluepower version and build number ###
bluepower-1.15.2-0.4.186-alpha-universal (logfiles say 184 but I updated to 186 and the problem is the same)

**Comment by charmesal** [comment]
I have also noticed that I'm unable to place most of the redstone/bluestone items. The game does not crash or log anything but it just doesn't place anything tiles besides the AND and NAND gates. So this goes for all the tiles (Redstone/Bluestone wire, Redstone/Bluestone Anode Tile, Silicon Chip Tile, Etc.)

**Comment by MoreThanHidden** [comment]
Sorry, None of these items have been implemented yet
