### ISSUE TITLE
BlueElectricCable onBlockPlacedBy neighbor pos values possible wrong

### ISSUE THREAD

**Issue by zaped212** [Qmunity/BluePower#550]
### What were you doing when the issue happened? ###
While investigating behavior when blocks are added, I noticed BlueElectricCable's onBlockPlacedBy function was calculating odd values for the neighbor pos.

When placing a block at 0 : 56 : 0 I see neighbors being calculated at:
0 : 55 : -1
1 : 55 : 0
0 : 55 : 1
-1 : 55 : 0
0 : 56 : 0
0 : 54 : 0

It seems to be calculating neighbor position values for the block underneath it. causing it to call "neighborChanged" on itself.

### What did you expect to happen? ###
I expected to see the neighborChanged function called on each of the 6 neighbors of the placed block.

It may just be a missunderstanding on my part it just seems odd that it would update itself.
### Forge and Minecraft version ###
Minecraft 1.15.2

### Bluepower version and build number ###
Tips of master branch.

**Comment by zaped212** [comment]
Yeah I can see where multipart can be very complex.
The part that seems very weird / wrong is that it triggers a "neighbor changed" on itself.

**Comment by MoreThanHidden** [comment]
Changing the way this works anyhow, just ironing out a few bugs in the multipart.
