### ISSUE TITLE
Lamps don't glow properly

### ISSUE THREAD

**Issue by Aurailus** [Qmunity/BluePower#551]
### What were you doing when the issue happened? ###

I crafted some White Inverted Lamps, and placed them.

### What did you expect to happen? ###

They would have a semi-transparent white texture placed around the lamp to make the appear brighter.

### What happened instead ###

The texture did appear for a moment but then disappeared a few moments after. The lamp then looked darker but was still "on".

This is on All the Mods 4, Minecraft 1.14.4.

**Comment by MoreThanHidden** [comment]
Fixed in bluepower-1.14.4-0.3.189-alpha
