### ISSUE TITLE
[1.14.4] Unable to disable volcano generation

### ISSUE THREAD

**Issue by Sandriell** [Qmunity/BluePower#553]
Setting "volcanoSpawnChance" to 0 resets it to 0.005 on world generation which is still causing volcanoes to generate in the world, and still fairly often for such a low number.

Minecraft: 1.14.4
bluepower-1.14.4-0.3.183-alpha-universal

**Comment by MoreThanHidden** [comment]
Does require a double so '0.0' should work.
