### ISSUE TITLE
There's no option for marble generation?

### ISSUE THREAD

**Issue by STOKE-STER** [Qmunity/BluePower#555]
### What were you doing when the issue happened? ###
Trying to stop marble from generating
### What did you expect to happen? ###
Disable marble generation in the config
### What happened instead ###
There was no option to disable marble generation

### Forge and Minecraft version ###
Forge:31.2.30
Minecraft: 1.15.2
### Bluepower version and build number ###
1.15.2-0.4.190-alpha-universal

**Comment by MoreThanHidden** [comment]
Setting veinSizeMarble to 0 doesn't work?

**Comment by MoreThanHidden** [comment]
I'll add a option for generateMarble anyhow.

**Comment by STOKE-STER** [comment]
Setting it to 0 did work, was just odd that it was missing the boolean when everything else had one 😅
