### ISSUE TITLE
[1.16.1] Crash on screwdriver use

### ISSUE THREAD

**Issue by Ars2014** [Qmunity/BluePower#558]
### What were you doing when the issue happened? ###
Used screwdriver on a block breaker

### What did you expect to happen? ###
Rotated block breaker

### What happened instead ###
Game has crashed

### Full Log and Crashlog on pastebin/gist ###
https://gist.github.com/Ars2014/10ce28aa006a6b0bdf3db3974c002f51

### Forge and Minecraft version ###
Forge: 32.0.75
Minecraft: 1.16.1

### Bluepower version and build number ###
0.5.200-alpha-universal

**Comment by MoreThanHidden** [comment]
Forge is currently changing rapidly so is hard to keep up with the breaking changes whilst adding new features. I'll see how long it will take me to get the major changes finished or implement a hotfix soon.

**Comment by davqvist** [comment]
Not sure if I should make another issue, but I get the same crash on 1.15.2
I wonder if this fix could get implemented there too?
