### ISSUE TITLE
Tungsten carbide litterally has no recipe to make it?

### ISSUE THREAD

**Issue by STOKE-STER** [Qmunity/BluePower#559]
Am I missing something or is there no way to make tungsten carbide?

Also, is smelting tungsten ore into tungsten nuggets intentional?

**Comment by MoreThanHidden** [comment]
Sorry yes there are many things WIP see #466, these haven't been implemented yet and the tools are currently just a clone of the gem tools anyhow, same with the silky screwdriver. When these are implemented will review the production of tungsten carbide etc.
