### ISSUE TITLE
[1.15.2] Microblocks break instantly

### ISSUE THREAD

**Issue by mechobree** [Qmunity/BluePower#562]
### What were you doing when the issue happened? ###

Using the microblocks

### What did you expect to happen? ###

I expected the microblocks to have the same time to break as it's original counterpart.

### What happened instead ###

They break instantly, which makes it so that accidentally clicking is just enough to break them.

### Forge and Minecraft version ###

Minecraft 1.15.2

Forge: 31.2.31

### Bluepower version and build number ###

1.15.2-04.190-alpha-universal

**Comment by MoreThanHidden** [comment]
Fixed in 1.16.1+ still need to backport this.

**Comment by MoreThanHidden** [comment]
Should be fixed in bluepower-1.15.2-0.4.226-alpha-universal.jar
