### ISSUE TITLE
Mahou & Blue Power dupe issue

### ISSUE THREAD

**Issue by stepsword** [Qmunity/BluePower#563]
https://github.com/AllTheMods/ATM-5/issues/224

Basically somehow my powdered stuff in Mahou is getting added to Blue Power's recipe thing which seems a bit weird since my powders don't have any tags or anything. Apparently something is undesirable about the config I proposed, which you might be able to make easier, or maybe it's just impossible for now on current Forge?

**Comment by MoreThanHidden** [comment]
Config seems correct but I'll check it out, basically  I'm checking the recipes that use iron and gold and adding them to the recycling list, does already have some anti dupe logic but must have bypassed it somehow.

**Comment by MoreThanHidden** [comment]
Fixed in bluepower-1.16.4-0.5.230-alpha
