### ISSUE TITLE
ProjectTable dupe.

### ISSUE THREAD

**Issue by 2xMJet** [Qmunity/BluePower#564]
Tried to set recipe and accidentialy duped stack of pumpkins and server threw massive wall of errors in console.

It threw that kinda errors when it happened:
https://pastebin.com/SjMF9tTf 

Forge 32.0.108 , Minecraft 1.16.1

bluepower-1.16.1-0.5.216-alpha

Full log (immidiately took off server after it happened)
[latest.log](https://github.com/Qmunity/BluePower/files/5124963/latest.log)

P.S. if it'll help played All the mods 6 modpack (ver 0.28a)

if need something more (can even record it) just ask

**Comment by MoreThanHidden** [comment]
Fixed in 1.16.2-0.5.218 will look at backporting to 1.16.1 soon if 1.16.2 continues to lack easy biome feature manipulation, as things stand is hard for modders to port to 1.16.2 without resorting to hacky methods.
