### ISSUE TITLE
BluePower not Compatible with Advanced Mining Dimension

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Qmunity/BluePower#566]
I'm making a modpack using BluePower and ores are not generating within the [Advanced Mining Dimension](https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension/files/3061058) as expected. I have posted this issue with henkelmax (dev for mining dimension) as shown [here](https://github.com/henkelmax/advanced-mining-dimension/issues/9). He suggested a datapack, which I have tried without success. Since both your mod and the mining dimension are popular mods, it would be nice if your mod could generate ores in the mining dimension.

The pack is not published yet, but here is the latest Twitch/MultiMC install: 
[Paradise in Chaos-0.2.0.zip](https://github.com/Qmunity/BluePower/files/5258358/Paradise.in.Chaos-0.2.0.zip)

### Forge and Minecraft version ###
Forge: 34.0.9
Minecraft: 1.16.3

### Bluepower version and build number ###
bluepower-1.16.3-0.5.219-alpha-universal

Thank you,
CM

**Comment by MoreThanHidden** [comment]
Fixed in bluepower-1.16.4-0.5.230-alpha
