### ISSUE TITLE
Lamps not glowing

### ISSUE THREAD

**Issue by Andibyts** [Qmunity/BluePower#568]
### What were you doing when the issue happened? ###
Placing white Lamps
### What did you expect to happen? ###
Light to appear
### What happened instead ###
It stayed dark
### Forge and Minecraft version ###
34.1.12, 1.16.3
### Bluepower version and build number ###
bluepower-1.16.3-0.5.219-alpha
![2020-10-13_16 03 46](https://user-images.githubusercontent.com/66882472/95873141-e76ad000-0d6f-11eb-8d25-074c864aebea.png)
![2020-10-13_16 03 51](https://user-images.githubusercontent.com/66882472/95873145-e8036680-0d6f-11eb-8d2c-6a3aa82082bb.png)

Appears to just happen with Optifine installed.

**Comment by Andibyts** [comment]
Sometimes it works and the Lamp glows. a few blocks away it doesnt

**Comment by MoreThanHidden** [comment]
Sorry seems to be an issue on the Optifine side not checking the forge light level.
