### ISSUE TITLE
[1.16.4] Issue with config option alloyFurnaceDatapackGenerator  

### ISSUE THREAD

**Issue by Terpo** [Qmunity/BluePower#570]
### What were you doing when the issue happened? ###
bluepower-common.cfg
set alloyFurnaceDatapackGenerator  to false

### What did you expect to happen? ###
World loads fine without creating any recycling recipes.

### What happened instead ###
When loading a single player instance a warning screen of minecraft pops up and tells that something went wrong with loading datapacks. Even clicken "load in safe mode" does not work.

![grafik](https://user-images.githubusercontent.com/4256058/99401618-ad4d9a80-28e8-11eb-8c5a-e5da5525db1a.png)

### Full Log and Crashlog on pastebin/gist ###
[Gist](https://gist.github.com/Terpo/c43ce9ddb31e09fabe46c2cc3d4a6917#file-gistfile1-txt-L4683)

### Forge and Minecraft version ###
MC 1.16.4
Forge 35.0.3

### Bluepower version and build number ###
bluepower-1.16.3-0.5.221-alpha-universal.jar

**Comment by Terpo** [comment]
I tried a quickfix for myself because my first idea was, that the path is simply null but
it seems that the server field is still null when joining the world. The FMLServerAboutToStartEvent states, that it should be fired when loading a single player world too.

**Comment by MoreThanHidden** [comment]
Fixed, Still requires 2 reloads to disable / enable Recycling Recipes at the moment so I'll look into that later, don't want to break other mods and need to work in with Craft Tweaker / JEI for order of events.
