### ISSUE TITLE
Multi player project table dup bug

### ISSUE THREAD

**Issue by W1nter-isHere** [Qmunity/BluePower#571]
### What were you doing when the issue happened? ###
When you craft an item in the project table in multiplayer, when you hover over the output item and another player take the ingredient out, you are still able to craft the item

### Forge and Minecraft version ###
1.15.2
31.2.31

### Bluepower version and build number ###
0.4

**Comment by MoreThanHidden** [comment]
Fixed in 1.16.4, I'll backport the fix tonight as it is a dupe bug, but not planning on backporting features, as there is plenty yet to be ported.

**Comment by W1nter-isHere** [comment]
Ah ok cool, found it while playing qtech :p

**Comment by MoreThanHidden** [comment]
Should be fixed in bluepower-1.15.2-0.4.226-alpha-universal.jar
