### ISSUE TITLE
[1.16.4] Dimensions whitelist/blacklist

### ISSUE THREAD

**Issue by YOYOK9** [Qmunity/BluePower#572]
Hello, I am just wondering if it is currently possible to whitelist or blacklist specified dims for world gen to occur in? If not would it be possible to add this feature?
 I am currently making a mod pack and the volcanos are spawning in worlds they really shouldn't be. An example of this is the Space-BossTools mod. The mod adds space dims and I found that in the "void" style worlds volcanos would spawn. 

I've already talked to the author of the mod, long story short it was to just disable features in other mods..

**Comment by loa-in-** [comment]
> I've already talked to the author of the mod, long story short

Which mod?

**Comment by MoreThanHidden** [comment]
Added Biome Whitelist to bluepower-1.16.4-0.5.227-alpha-universal.jar

**Comment by YOYOK9** [comment]
Sweet! Thank you soo much
