### ISSUE TITLE
1.16.4 Crash with Alloy Furnace

### ISSUE THREAD

**Issue by Terpo** [Qmunity/BluePower#573]
### What were you doing when the issue happened? ###
I created a new recipe with CraftTweaker. The crash happened on a server <-> client environment. 

`
<recipetype:bluepower:alloy_smelting>.addJSONRecipe("nameless_bluepower_alloy_bronze_nugget",
{
  "type": "bluepower:alloy_smelting",
  "ingredients": [
    {
      "tag": "forge:nuggets/copper",
      "count": 3
    },
    {
      "tag": "forge:nuggets/tin"
    }
  ],
  "result": {
    "item": prefferedBronzeNugget.registryName,
    "count": 4
  }
}
);
`
I added some copper nuggets, tin nuggets and coal into the furnace. After a while the server simply crashed.
I think the crash may happened after one craft was done and it was calculating the next, but the copper was emtpy by now.
![grafik](https://user-images.githubusercontent.com/4256058/103412436-61437600-4b75-11eb-86df-3839622bbbbd.png)

### What did you expect to happen? ###
no crash

### What happened instead ###
--

### Full Log and Crashlog on pastebin/gist ###
https://gist.github.com/Terpo/e3e79eb7441cbc23d2932c483de488ca --> main crash
The server did not crash completly but was hanging after the issue:
https://gist.github.com/Terpo/291ab181a83e40bff55c8fa2d0c1e914

### Forge and Minecraft version ###
MC 1.16.4
Forge 1.16.4-35.1.11
CraftTweaker: CraftTweaker-1.16.4-7.0.0.56

### Bluepower version and build number ###
bluepower-1.16.4-0.5.227-alpha-universal

**Comment by MoreThanHidden** [comment]
Fixed in bluepower-1.16.4-0.5.231-alpha, let me know if you notice any oddities with it but that craft tweaker recipe was working for me.

**Comment by Terpo** [comment]
I will install the bluepower update in one of the next days and tell you if there are any oddities.
