### ISSUE TITLE
Alloy furnace datapack generates every world load

### ISSUE THREAD

**Issue by ZeekDaGeek** [Qmunity/BluePower#574]
*Version:* 0.5.231-alpha

With the `alloyFurnaceDatapackGenerator` setting turned on it adds roughly 60 to 90 seconds to EVERY world load, which I'm sure is not desirable for most users. It would be nice if it would cache and only generate once.

I attempted to create this functionality by generating it once and then turning the setting off and instead it cleared out the related datapack folder, which seems unintended.

**Comment by MoreThanHidden** [comment]
Issue is that if mods or recipes change it needs to regenerate the data pack, only adds 5 seconds to load in testing, but with a larger mod pack could take time, have noticed this myself when trying to reload large mod packs. I can pull it out of the reload but will need to reload if there have been any changes. I know it's not the best system but data packs have stopped mods from adding recipes directly, some of these nice to haves are hard to accomplish without hacking it in and potentially causing conflicts with other mods.

I'll do some more testing and at a minimum count the number of recipes and not reload if they haven't changed.
