### ISSUE TITLE
[1.16.4] Malachite doesn't generate

### ISSUE THREAD

**Issue by Flexico** [Qmunity/BluePower#576]
### What were you doing when the issue happened? ###
Mining

### What did you expect to happen? ###
Find Malacite Ore

### What happened instead ###
Didn't find any Malachite Ore

### Full Log and Crashlog on pastebin/gist ###
Didn't crash

### Forge and Minecraft version ###
MC 1.16.4
Forge 45.1.11

### Bluepower version and build number ###
0.5.231-alpha

**Comment by MoreThanHidden** [comment]
Wasn't yet implemented has been implemented in the next version as Green Sapphires

**Comment by MoreThanHidden** [comment]
Released in bluepower-1.16.4-0.5.233-alpha
