### ISSUE TITLE
Crash on rendering specific micro-blocks

### ISSUE THREAD

**Issue by Freebi85** [Qmunity/BluePower#580]
### What were you doing when the issue happened? ###
Browsing trough JEI for myalite blocks (Quark)
### What did you expect to happen? ###
To not crash^^
### What happened instead ###
Crash because of rendering myalite microblocks variant.
### Full Log and Crashlog on pastebin/gist ###
[crash-2021-02-10_14.01.37-client.txt](https://github.com/Qmunity/BluePower/files/5958341/crash-2021-02-10_14.01.37-client.txt)
### Forge and Minecraft version ###
Minecraft 1.16.5
Forge 36.0.21
### Bluepower version and build number ###
0.5.223-alpha-universal

**Comment by MoreThanHidden** [comment]
Well confirmed it is definitely an issue on the Quark side as BlockPos is supposed to be able to be null (Nullable) on getColor but I'll see if I can avoid a crash on my side.

**Comment by Freebi85** [comment]
Thank you very much sir <3
