### ISSUE TITLE
incomplete set of tags received from server

### ISSUE THREAD

**Issue by leytilera** [Qmunity/BluePower#581]
### What were you doing when the issue happened? ###
After leaving a server and rejoining it, it says "incomplete set of tags received from server". Without Bluepower everything works fine.

### Java Debugger output ###
Render thread[1] # catch all java.lang.IllegalStateException
Render thread[1] # now continue until the right exception is hit
Exception occurred: java.lang.IllegalStateException (to be caught at: mezz.jei.load.PluginCaller.callOnPlugins(), line=28 bci=91)"thread=Render thread", net.minecraft.tags.TagRegistry$NamedTag.func_232944_c_(), line=131 bci=41
Render thread[1] dump this
 this = {
    defaults: null
    defaulted: false
    net.minecraft.tags.TagRegistry$NamedTag.field_232942_b_: null
    net.minecraft.tags.TagRegistry$NamedTag.field_232941_a_: instance of net.minecraft.util.ResourceLocation(id=62444)
}
Render thread[1] dump this.field_232941_a_
 this.field_232941_a_ = {
    field_240908_a_: instance of com.mojang.serialization.Codec$1(id=62445)
    field_200118_c: instance of com.mojang.brigadier.exceptions.SimpleCommandExceptionType(id=62446)
    field_110626_a: "bluepower"
    field_110625_b: "saw"
}

### Forge and Minecraft version ###
1.16.4 - 35.1.37
### Bluepower version and build number ###
1.16.4-0.5.223-alpha

**Comment by MoreThanHidden** [comment]
Your using a very old version here but I've been unable to replicate this issue, please provide the full log file?

**Comment by MoreThanHidden** [comment]
Downloaded your Modpack and was able to replicate the issue, updating bluepower and the other mods fixed the issue, I wasn't able to narrow it down to a specific mod but potentially JEI.
