### ISSUE TITLE
[1.16.5] Crash with Environmental Tech

### ISSUE THREAD

**Issue by Alkasym** [Qmunity/BluePower#582]
Hi, 

The game crash when I right click on the Environmental Tech ore miner on JEI and the crash report to BluePower.
I already report the issue to Env tech discord but the problem come from BluePower according to them.

Pastbin : https://pastebin.com/053ikEFy

Forge : 36.0.45
BluePower : 0.5.240
JEI : 7.6.1.71
EnvTech : 3.0.7.2
EnvCore : 3.0.7.1

**Comment by MoreThanHidden** [comment]
Fixed in bluepower-1.16.4-0.5.241-alpha
