### ISSUE TITLE
1.16.5 -- Come Back of MicroBlocks?

### ISSUE THREAD

**Issue by papaworld** [Qmunity/BluePower#584]
Use microblocks alot... will it come back? BTW: I have over 250 mods in my custom packs... never had a problem. Maybe a config option to enable/disable?

If it is helpful... I can send you my mod lists for Creative Test World and Game Play Survival World... also, I'm willing to be a test rat for ya.

Thank You

**Comment by MoreThanHidden** [comment]
Microblocks are still in the Mod just disabled for those with tile entities (like machines)?
