### ISSUE TITLE
Lamps do not glow

### ISSUE THREAD

**Issue by emanuele246gi** [Qmunity/BluePower#585]
### What were you doing when the issue happened? ###
Placing the lamps

### What did you expect to happen? ###
I was expecting the lamps to glow

### Forge and Minecraft version ###
Forge: 36.1.32
Minecraft: 1.16.5

### Bluepower version and build number ###
bluepower-1.16.5-0.5.244-alpha

**Comment by MoreThanHidden** [comment]
Lamps seem to be working correctly. please make sure you have a Redstone signal applied or use the Inverted Variants.
![image](https://user-images.githubusercontent.com/1351964/125290552-045e1f00-e353-11eb-9cf8-6d329f25bf7a.png)

**Comment by emanuele246gi** [comment]
@MoreThanHidden I indeed placed the one with inverted redstone. May it be Optifine?

**Comment by MoreThanHidden** [comment]
Probably not much I can do if it is, although I have tested on the latest Optifine Version with no issues, could be a shader problem though.

**Comment by emanuele246gi** [comment]
I have shaders too, but it's not only a visual thing, even when I press f3 it doesn't show the right light level (always at 0)
