### ISSUE TITLE
Bluepower Breaks JEI [1.16.5]

### ISSUE THREAD

**Issue by CrazedslawDev** [Qmunity/BluePower#587]
### What were you doing when the issue happened? ###

Just joined my world to find that JEI was broken and not appearing when pressing E

### What did you expect to happen? ###

the JEI Menu to appear with bluepower items being in the menu

### What happened instead ###

Inventory screen looks like vanilla minecraft

### Full Log and Crashlog on pastebin/gist ###

https://pastebin.com/A39b7Y0w

### Forge and Minecraft version ###
Minecraft 1.16.5 - Forge 36.2.0

### Bluepower version and build number ###

0.5.241-alpha

**Comment by MoreThanHidden** [comment]
Same as #583 but will see if there is something that can be done to prevent it I just haven't been able to replicate it.

**Comment by MoreThanHidden** [comment]
Potentially fixed in bluepower-1.16.5-0.5.250-alpha I just haven't been able to replicate the issue, let me know if it is still an issue and what mods you are using.
