### ISSUE TITLE
Blue Power update made server crash

### ISSUE THREAD

**Issue by GreninjaSan** [Qmunity/BluePower#589]
### What were you doing when the issue happened? ###

Launching a server after the last update of BLue Power

### What did you expect to happen? ###

Simply successfuly launch the server.

### What happened instead ###

Server crashed, returning a crash log concerning blue power.

### Full Log and Crashlog on pastebin/gist ###

https://pastebin.com/hCZZPRG9

### Forge and Minecraft version ###

Forge : 36.2.0
Minecraft : 1.16.5

### Bluepower version and build number ###

bluepower-1.16.5-0.5.253-alpha-universal.jar | 0.5.253-alpha

**Comment by MoreThanHidden** [comment]
Ok I see the issue will fix this up shortly.

**Comment by GreninjaSan** [comment]
Thank you <3

**Comment by MoreThanHidden** [comment]
Should be fixed in **bluepower-1.16.5-0.5.256-alpha** let me know if still having issues.
