### ISSUE TITLE
Recycling Recipes causing Fairylight mod to use forge tags before they are defined.

### ISSUE THREAD

**Issue by PlatiniumOfficial** [Qmunity/BluePower#591]
Blue Power doesn't seem to like the forge tag that the fairylight mods use.

Here is the report: https://gist.github.com/PlatiniumOfficial/0c3d1f265c6f15510a775e115eda522e

**Comment by MoreThanHidden** [comment]
Fixed in bluepower-1.16.5-0.5.258-alpha
