### ISSUE TITLE
[1.16] Disjunction enchant

### ISSUE THREAD

**Issue by dedolegrec** [Qmunity/BluePower#592]
### What were you doing when the issue happened? ###

Fighting Ender Dragon with sword enchant with disjunction

### What did you expect to happen? ###

Dragon taking damage

### What happened instead ###

Dragon doesn't take damge

### Full Log and Crashlog on pastebin/gist ###

Ø

### Forge and Minecraft version ###

minecraft 1.16.5
forge 36.2.0

### Bluepower version and build number ###

Blue Power version 0.5.259-alpha

**Comment by MoreThanHidden** [comment]
Fixed in bluepower-1.16.5-0.5.262-alpha-universal
