### ISSUE TITLE
1.18.1 Alloy furnace crashes server and singplayer when placed then right clicked

### ISSUE THREAD

**Issue by IchigoGames** [Qmunity/BluePower#597]
Placing a alloy furnace and clicking on it to use it

Alloy furnace to work like normal

Alloy furnace crashes server and singplayer when placed then right clicked.

crash report https://pastebin.com/CZvNyD9F

1.18.1
Forge 39.0.64

bluepower-1.18.1-0.6.274-alpha-universal

**Comment by MoreThanHidden** [comment]
Fixed in 696b82b
