### ISSUE TITLE
Minecolonies incompatibility

### ISSUE THREAD

**Issue by emanuele246gi** [Qmunity/BluePower#598]
### What were you doing when the issue happened? ###
I was playing Minecolonies in my modpack, with customized buildings.

### What did you expect to happen? ###
I was expecting lamps to be in the right rotation, against the wall.

### What happened instead ###
I noticed that there are some rotation issues with Minecolonies and customized buildings, they keep facing the original schematic direction instead of following this specific rotation of the building:

![2022-03-06_16 01 38](https://user-images.githubusercontent.com/61762317/156929214-230e3c8d-b685-4cd3-847f-2981bb76fde0.png)

### Forge and Minecraft version ###
36.2.29 - 1.16.5

### Bluepower version and build number ###
0.5.262-alpha

**Comment by MoreThanHidden** [comment]
Similar to #590 will need to look into rotation.

**Comment by emanuele246gi** [comment]
Thank you

**Comment by MoreThanHidden** [comment]
I'll just close this as a duplicate for now and add to pending features.
