### ISSUE TITLE
Crashing because 1.18.1 isn't compatible with 1.18.2

### ISSUE THREAD

**Issue by halvors** [Qmunity/BluePower#599]
### What were you doing when the issue happened? ###
Starting the game

### What did you expect to happen? ###
Finish loading mod without crash

### What happened instead ###
Failes to load mod

### Full Log and Crashlog on pastebin/gist ###
https://pastebin.com/riMA64Sg

### Forge and Minecraft version ###
1.18.2, forge 40.0.45

### Bluepower version and build number ###
1.18.1-0.6.275

**Comment by Flexico** [comment]
Same here!

**Comment by MoreThanHidden** [comment]
Haven't finished porting to 1.18.2 yet is a large update.

**Comment by halvors** [comment]
thx :)

**Comment by Flexico** [comment]
"Pending release"... Are we getting close? ^^

**Comment by MoreThanHidden** [comment]
Found a weird crash I'm just trying to resolve before releasing. 🤞

**Comment by Flexico** [comment]
Any news? ^^

**Comment by MoreThanHidden** [comment]
Sorry took me ages to get this one organized, one hell of a minor update from a modding standpoint. Hopefully should make porting to 1.19 a lot easier. Just doing some final testing before I release.

**Comment by MoreThanHidden** [comment]
bluepower-1.18.2-0.6.281-alpha released on curse forge.
