### ISSUE TITLE
Wires and gates missing recepi says : wip 1.12.2

### ISSUE THREAD

**Issue by redfoxrommy** [Qmunity/BluePower#600]
First Thank you this mod especially for alloy furnece.

when i was looking for recepies blue and red alloy wires and gates recepies missing . its says wip . i can craft red and blue alloys lamps ignter ect. What this is mean

**Comment by MoreThanHidden** [comment]
Is a Work in progress (WIP), hasn't yet been ported to Modern Versions of Minecraft.

**Comment by redfoxrommy** [comment]
oh thank for fast answer :) . İ hope it will done . tnx again for tihis mod . bye.
