### ISSUE TITLE
I was just using the lamp blocks in my build.

### ISSUE THREAD

**Issue by unclar1ty** [Qmunity/BluePower#601]
### What were you doing when the issue happened? ###
Building with the inverted lamp blocks
### What did you expect to happen? ###
Light up like normal
### What happened instead ###
Turns on but if I turn the light turn off and flicker
### Full Log and Crashlog on pastebin/gist ###
https://pastebin.com/9UVXTsRC
### Forge and Minecraft version ###
Forge version - 14.23.5.2854     Minecraft Version: 1.12.2

**Comment by MoreThanHidden** [comment]
Sorry log file is garbled so I can't get much information from it, might be Optifine or something conflicting?
