### ISSUE TITLE
Blue power not have generators and cabbles for machines 1.7.10

### ISSUE THREAD

**Issue by Mariner21CZ** [Qmunity/BluePower#606]
Hi, I have a problem with the blue power version( BluePower-1.7.10-0.2.962-universal.jar ) in creative, I wanted to build an automatic sorting machine using a sorting machine, but there is no electricity to drive it, nor electricity generators, nor electricity cables, will you make an addon or ubdate where you will add generators, cables for those machines, please thanks

**Comment by Mariner21CZ** [comment]
minecraft 1.7.10

**Comment by MoreThanHidden** [comment]
Sorry I don't have enough time to finish the newer versions, let alone an 8 year old version, anyone is welcome to Pull Request these in.
