### ISSUE TITLE
Crash at the startup

### ISSUE THREAD

**Issue by emanuele246gi** [Qmunity/BluePower#607]
### What were you doing when the issue happened? ###
Launching the game

### Full Log and Crashlog on pastebin/gist ###
https://pastebin.com/mEpJ3qp6

### Forge and Minecraft version ###
41.1.0 and 1.19

### Bluepower version and build number ###
0.7.293-alpha

**Comment by MoreThanHidden** [comment]
Sorry, aware of this, forge made some major changes before release on 1.19 so I will need to fix these.

**Comment by emanuele246gi** [comment]
Thanks for you efforts, take your time man!

**Comment by MoreThanHidden** [comment]
Alpha released for 1.19.2 on CurseForge [bluepower-1.19.2-0.8.299-alpha-universal](https://www.curseforge.com/minecraft/mc-mods/blue-power/files/4008324)
