### ISSUE TITLE
Alloy furnace continues to increase progress when output is full, causing rendering bug

### ISSUE THREAD

**Issue by PORTB** [Qmunity/BluePower#608]
### What were you doing when the issue happened? ###
Using the alloy furnace and letting the output slot fill up. Also happens with the blueletric version
### What did you expect to happen? ###
It should stop smelting/using fuel when the output is full

### What happened instead ###
![2022-10-12_08 42 38](https://user-images.githubusercontent.com/34615701/195203903-5863a623-3485-4f5e-8df7-9ccb04743c4c.png)
![2022-10-12_08 42 50](https://user-images.githubusercontent.com/34615701/195203919-51b3f954-c2b8-42ca-94f4-505d8a8193a7.png)

### Forge and Minecraft version ###
1.19.2
forge 43.1.32 

### Bluepower version and build number ###
0.8.300-alpha

**Comment by MoreThanHidden** [comment]
Thanks for reporting, fixed in [bluepower-1.19.2-0.8.301-alpha-universal.jar](https://www.curseforge.com/minecraft/mc-mods/blue-power/files/4027575)
