### ISSUE TITLE
[1.18] World generation crash - Casting to WorldgenRandom

### ISSUE THREAD

**Issue by Officialy** [Qmunity/BluePower#609]
### What were you doing when the issue happened? ###
Generating world

### What did you expect to happen? ###
World to generate

### What happened instead ###
Crashed

### Full Log and Crashlog on pastebin/gist ###
https://hastebin.com/rasuvivede.properties

### Forge and Minecraft version ###
40.1.85 - 1.18.2

### Bluepower version and build number ###

1.18.2-0.6.288-alpha

**Comment by MoreThanHidden** [comment]
Sorry the log file isn't working so not much to go off here.
