### ISSUE TITLE
Incompatibility with Terraincognita breaks JEI - 1.16.5

### ISSUE THREAD

**Issue by SiliconAshes** [Qmunity/BluePower#612]
Thank you for this mod.  I've used it over many Minecraft versions, and really like it.  I don't believe this has been reported in the issue tracker.  If this is a duplicate, I apologize.

   There seems to be an incompatibility between bluepower and terraincognita that breaks JEI.  It is very easy to reproduce:

1. Create a new 1.16.5 minecraft instance
2. install latest forge (36.2.39 or 36.2.34 - latest starred)
3. add latest jei (jei-1.16.5-7.7.1.153.jar)
4. add latest bluepower (bluepower-1.16.5-0.5.262-alpha-universal.jar)
5. add latest terraincognita and dependency (cuneiform-1.16.3-1.2.5.jar, terraincognita-1.16.3-1.7.3.jar)
6. Start a new world.

Result: JEI does not show up.  If either bluepower or terraincognita is taken out, JEI works as expected.

Here is a pastbin link to a latest.log for an affected attempt:
https://pastebin.com/6ZryVMVL

### What were you doing when the issue happened? ###

Constant Bug - doesn't require any specific action.

### What did you expect to happen? ###

   Upon opening inventory screen, JEI interface should show up.

### What happened instead ###

   Upon opening inventory screen, JEI interface does not show up.

### Full Log and Crashlog on pastebin/gist ###

latest.log: https://pastebin.com/6ZryVMVL
crashlog: not applicable

### Forge and Minecraft version ###

Forge: 36.2.34/36.2.39

### Bluepower version and build number ###

bluepower-1.16.5-0.5.262-alpha-universal.jar

**Comment by MoreThanHidden** [comment]
Looks like Terra Incognita is trying to cast IndigoDye to the Vanilla DyeItem for some reason so issue looks to be on their side. Can see the open issue here: https://github.com/Azmalent/terra-incognita/issues/72

If I've done something weird to cause this interaction the mod author can let me know but seems like they have found it based on the name or tag in which case other modded dyes will break if they don't extend DyeItem.

**Comment by Azmalent** [comment]
Terra Incognita dev here. The issue was indeed on my side, and it should be fixed in the newly released 2.0 version.

**Comment by MoreThanHidden** [comment]
Thanks for that, partially my fault, as is technically just an alternative blue dye.

**Comment by MoreThanHidden** [comment]
Fixed in Version 2.0 of Terra Incognita, will also look at extending the Dye Item to avoid this kind of issue in the future.
