### ISSUE TITLE
Alloy Smelter only showing 1 input item in JEI

### ISSUE THREAD

**Issue by TheNimbleNinja** [Qmunity/BluePower#613]
alloy smelter recipes dont show more than 1 item when they should

### Full Log and Crashlog on pastebin/gist ###
craftweaker log: https://gist.github.com/TheNimbleNinja/5b773b0e1947aa42cbb187939b3a7f6a
log: https://gist.github.com/TheNimbleNinja/59a73e18fcb8593848427015abdcf9f7

1.19.2 
forge  43.2.4
bluepower-1.19.2-0.8.301-alpha-universal.jar

**Comment by MoreThanHidden** [comment]
Doesn't show the correct number of input items or output?
If you could show a recipe / screenshot would be helpful, think I found it. 

Output items in JEI seem fine:
![image](https://user-images.githubusercontent.com/1351964/215250001-5812f7f8-d24d-4e70-885b-fbeb2afe6d5b.png)

Looks like Input in JEI is wrong:
![image](https://user-images.githubusercontent.com/1351964/215250075-dd6b6a7a-91b9-4801-b4ae-52009e05fb3f.png)

Should be:
![image](https://user-images.githubusercontent.com/1351964/215250440-46969b07-478a-42c1-b48d-49413e5c27bc.png)

**Comment by MoreThanHidden** [comment]
Updated for 1.19.2 and 1.19.3 (Weird Supporting 2 Minor Versions but here we are again feels like 1.7 all over again...)
[bluepower-1.19.2-0.8.309-alpha-universal.jar](https://www.curseforge.com/minecraft/mc-mods/blue-power/files/4368880)
[bluepower-1.19.3-0.9.310-alpha-universal.jar](https://www.curseforge.com/minecraft/mc-mods/blue-power/files/4368881)

**Comment by TheNimbleNinja** [comment]
thanks :)
