### ISSUE TITLE
[1.18] Fluidlogged Mod causing crash when rendering Microblocks.

### ISSUE THREAD

**Issue by JJSax** [Qmunity/BluePower#614]
### What were you doing when the issue happened? ###
See https://github.com/mezz/JustEnoughItems/issues/3059

Looking up certain items in JEI causes a crash.  We seem to be getting the crash with a Blue Power item.  Likely the 3x3 amethyst.

### What did you expect to happen? ###
No Crash

### What happened instead ###
Crash

### Full Log and Crashlog on pastebin/gist ###
(same log as in the linked issue above)
[log.txt](https://github.com/Qmunity/BluePower/files/10541100/message.txt)

### Forge and Minecraft version ###
Using Create+ modpack with some custom mod changes.
Modpack version (4.8.1)
MC version: 1.18.2
Forge 40.1.86

### Bluepower version and build number ###
BluePower version: 0.6.288-alpha-universal

**Comment by MoreThanHidden** [comment]
I'll have a look after work, could be, I thought I'd added a catch for that though.

**Comment by MoreThanHidden** [comment]
Not sure does seem to be something specific to this pack as is not letting it load the Baked Model, have been able to replicate the issue on the modpack you mentioned but still not sure what mod is breaking the baked model registry.

**Comment by MoreThanHidden** [comment]
Ok took me a while to figure out which mod was causing the issues, seems to be fluidlogged mod, assuming it is modifying the microblocks because they are water-loggable, which is breaking the renderer.

**Comment by MoreThanHidden** [comment]
Fixed in bluepower-1.18.2-0.6.314-alpha-universal
