### ISSUE TITLE
[1.18] Missing Ruby and Sapphire tags with Janoeo Foundation mod

### ISSUE THREAD

**Issue by emanuele246gi** [Qmunity/BluePower#615]
### What were you doing when the issue happened? ###
Just looking at the crafting recipes

### What did you expect to happen? ###
Being able to craft them

### What happened instead ###
![2023-02-04_17 09 20](https://user-images.githubusercontent.com/61762317/216777729-d27a1668-1534-454c-bfbd-f8605ca995bb.png)
![2023-02-04_17 09 29](https://user-images.githubusercontent.com/61762317/216777730-d91c3ac6-eeb9-4fbf-a627-16275041e1f9.png)

I also tried to fix it manually from datapack, but it still doesn't work

### Full Log and Crashlog on pastebin/gist ###
-

### Forge and Minecraft version ###
Forge 3.0.34, Minecraft 1.18.2
### Bluepower version and build number ###
bluepower-1.18.2-0.6.288-alpha-universal

**Comment by MoreThanHidden** [comment]
Recipes are fine natively:
![image](https://user-images.githubusercontent.com/1351964/216778024-bc2f15d7-01d7-4a3b-9c4d-f17bb7a576fe.png)
![image](https://user-images.githubusercontent.com/1351964/216778030-696907ba-389e-4744-a251-a72407713b85.png)
Must be a mod / datapack / script conflict, if you could attach the log file?

**Comment by emanuele246gi** [comment]
Oh well, I'll have to remove the datapack fix I made after this post, I'll be back in a while

**Comment by emanuele246gi** [comment]
[debug.log](https://github.com/Qmunity/BluePower/files/10610722/debug.log)
[latest.log](https://github.com/Qmunity/BluePower/files/10610723/latest.log)

**Comment by emanuele246gi** [comment]
I also wrote about the datapack that didn't work, what I meant is that it didn't work when still using the tags, but I managed to fix it with a datapack that specified the items

**Comment by MoreThanHidden** [comment]
Seems to be caused by the janoeo mod looks like they add ruby and sapphire tags, but the items don't exist in game, causing an error during the tag registration:
![image](https://user-images.githubusercontent.com/1351964/216817444-940b080d-5028-429c-84c4-df4fa0a04481.png)
Your pack took ages to load by the way 😅 was quite hard to troubleshoot.

**Comment by emanuele246gi** [comment]
Thank you for the response, yeah I know about that but I can't do otherwise 😅

**Comment by emanuele246gi** [comment]
I will try to fix it by looking at Janoeo instead, thank you again ^^

**Comment by MoreThanHidden** [comment]
No worries, the tag registry isn't always straight forward to tell what mod / recipe is breaking it, so get this kind of issue fairly regularly, in this case noticed this error when I was launching the pack:

```log
[19:52:45] [Worker-Main-24/ERROR]: Couldn't load tag forge:ores/sapphire as it is missing following references: janoeo:sapphire_ore (from Janoeo Foundation-7.10.3.84.jar)
[19:52:45] [Worker-Main-24/ERROR]: Couldn't load tag forge:ores/ruby as it is missing following references: janoeo:ruby_ore (from Janoeo Foundation-7.10.3.84.jar)
```

**Comment by emanuele246gi** [comment]
Good to know, thank you for your help!
