### ISSUE TITLE
Missing rubber tree, BUT-

### ISSUE THREAD

**Issue by emanuele246gi** [Qmunity/BluePower#616]
### What were you doing when the issue happened? ###
Just using the bone meal on the sapling

### What did you expect to happen? ###
To grow a rubber tree

### What happened instead ###
There was an oak tree, I thought on making a datapack (I was told that it wasn't the case for a datapack) to make it by myself as I'm creating a lot of compatibility in my modpack between mods: I made latex production, from Thermal Series and Industrial Foregoing, possible from its log (as you can see in the screenshots below), and I made the sapling obtainable from the Farming for Blockheads market, the only thing I just need is to replace the oak logs and leaves from the tree to their rubber variant and I don't really care about the shape. Is it possible to edit something or what? (By the way, I'm the same person who created the forge tag issue's post)

![2023-02-23_16 22 31](https://user-images.githubusercontent.com/61762317/220950517-a5486172-d2bf-48a8-85f3-dbb3e1519fc9.png)
![2023-02-23_16 22 26](https://user-images.githubusercontent.com/61762317/220950576-e318754e-36ad-4df3-a630-3a5672731e7a.png)

### Forge and Minecraft version ###
40.2.1-1.18.2

### Bluepower version and build number ###
1.18.2-0.6.314-alpha

**Comment by emanuele246gi** [comment]
But I didn't ask for a rapid implementation, I just wanted to know if I could just do that replacing thing

**Comment by MoreThanHidden** [comment]
I think I would need to implement it somewhat to be able to do it with a data pack but I'm not familiar with the modern way of making modded trees, at the moment I think the sapling is just an oak sapling with a different icon, but I'll look into it.

**Comment by emanuele246gi** [comment]
Well... thank you anyway for your efforts, I hope we'll figure it out
