### ISSUE TITLE
[1.19.2 Bug] Alloy Furnace ignore pattern of same item on custom recipes 

### ISSUE THREAD

**Issue by DevDyna** [Qmunity/BluePower#620]
Creating a custom recipe via json / kubejs when many slots of alloy furnace have same item (like iron ingot + iron ingot = iron door) , alloy furnace ignore the other slots and when have one of them start the recipe without need of all other slot with ingredients

[examples are only to describe]
1x iron ingot +1x iron ingot  =1x iron door

1x iron ingot + (slot ignored) =1x iron door 
when on recipe was 1x iron ingot +1x iron ingot =1x iron door without any "1x iron ingot =1x iron door"

Modpack (maybe can be useful or not)
https://legacy.curseforge.com/minecraft/modpacks/ironberry-expert -> 0.4A Hotfix -> recipe of T0 upgrade | wood to copper chest upgrade

Minecraft 1.19.2
Forge 43.2.8

bluepower-1.19.2-0.8.315-alpha-universal

**Comment by DevDyna** [comment]
this include itemcount and slotid :
//itemcount
[recipe] 
64x iron ingot + 64x iron ingot =1x iron door

[what alloyfurnace use]
64x iron ingot =1x iron door  (-64x iron ingot)

//slotid
[recipe] 
64x iron ingot + 64x iron ingot + 64x iron ingot + 
64x iron ingot + 64x iron ingot + 64x iron ingot +
64x iron ingot + 64x iron ingot + 64x iron ingot =1x iron door

[what alloyfurnace use]
64x iron ingot =1x iron door (-64x8 iron ingot)

**Comment by MoreThanHidden** [comment]
Yeah sorry this is somewhat intentional, the allow furnace doesn't support shaped recipes, it will pull them from anywhere, as it's not a crafting table, so you'll need to limit the recipes to less than 64 of an item, or maybe 320x would work I haven't tried going that far.
