### ISSUE TITLE
[1.20.1] Sickle has no 3x3 function on nether's exoticism leaves, and doesn't use durability when breaking them

### ISSUE THREAD

**Issue by zrebarchak** [Qmunity/BluePower#625]
nethers_exoticism:kiwano_leaves, nethers_exoticism:rambutan_leaves nethers_exoticism:jaboticaba_leaves do not register as a valid block for the 3x3 mining feature of the sickle

expected sickle to area mine the leaves like they do on vanilla

one leaf block was mined at regular speed and no tool durability used

1.20.1-47.1.3

bluepower-1.20.1-0.10.323-alpha-universal
(nether-s-exoticism-1.20.1-1.2.7)

**Comment by MoreThanHidden** [comment]
Hey There,

Sorry this seems to be an issue for nethers_exoticism as they aren't registering their leaves as BlockTag "leaves" and they don't extend the Vanilla LeavesBlock.

You should also be able to do this with Datapack, CraftTweaker or KubeJS if required.
Durability would be unchanged as is currently the same as hitting it with your hand.

**Comment by zrebarchak** [comment]
thank you for the response, ill see if I can add compatibility using one of the methods suggested
