### ISSUE TITLE
[1.21] NeoForge crashe when loading due to IPlantable

### ISSUE THREAD

**Issue by Periam** [Qmunity/BluePower#631]
### What were you doing when the issue happened? ###

Just launching the game.

### What did you expect to happen? ###

That the game launch normally

### What happened instead ###

An error occurred referred to IPlantable

### Full Log and Crashlog on pastebin/gist ###

[crash-2024-07-04_21.49.08-fml.txt](https://github.com/user-attachments/files/16103651/crash-2024-07-04_21.49.08-fml.txt)

### Forge and Minecraft version ###
neoforge 21.0.56

### Bluepower version and build number ###
bluepower-1.21-0.11.338-alpha-neoforge.jar

**Comment by MoreThanHidden** [comment]
Fixed in: bluepower-1.21-0.11.339-alpha
